#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i991-coords-2d-gan-p05-s42-20261005-v2
# provider=codex session=01a10697-63da-75b2-ae84-f2980da51c23 issue=991 resource=half logical_slot=0
set -uo pipefail
export TENNIS_GPU_RESOURCE=half
export TENNIS_GPU_SLOT=0
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/coordinate-ball-refiners-991-1014}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 0bdeb9514ae1e780f1d8e8e08a431b2aa9f5143c (branch codex/coordinate-ball-refiners-991-1014)"
git checkout 0bdeb9514ae1e780f1d8e8e08a431b2aa9f5143c 2>/dev/null || echo "[repro] WARN: checkout 0bdeb9514ae1e780f1d8e8e08a431b2aa9f5143c failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 .venv/bin/python -m src.tasks.ball_refiner.scripts.train_coordinates model.dimensions=2 model.architecture=regression corruption.event_probability=0.5 training.gan_weight=0.002 run.output_dir=ball_refiner/train/coordinates-2d-gan-p05/20261005-v2-s42
