#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-real-rgb-build-meiji
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 30a7eeb04714fd548f28d0a58c9813cdfea6ee1b (branch codex/slcs-real-rgb)"
git checkout 30a7eeb04714fd548f28d0a58c9813cdfea6ee1b 2>/dev/null || echo "[repro] WARN: checkout 30a7eeb04714fd548f28d0a58c9813cdfea6ee1b failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env TENNIS_RGB_GPU=0 bash /home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb/scripts/datasets/build_real_rgb.sh --execute meiji clip_ids=\[video_000/clip_007\,video_001/clip_001\,video_000/clip_001\,video_000/clip_009\,video_001/clip_000\] 
