#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: appearance-b00-clay-flare-100-30k-v001-30000
# provider=codex session=01a0bd70-e78d-7732-ba19-1a4595e91a32 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/b00-clay-variant}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 893d0ca4129e9e69f8e8c850d89c6200cf2df2e3 (branch codex/b00-clay-variant)"
git checkout 893d0ca4129e9e69f8e8c850d89c6200cf2df2e3 2>/dev/null || echo "[repro] WARN: checkout 893d0ca4129e9e69f8e8c850d89c6200cf2df2e3 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
/home/kamimura/projects/tennis-lab/.claude/worktrees/b00-clay-variant/.venv/bin/python -m src.synthetic_data_generation.scripts.run_appearance_variant action=execute_training variant.output_root=/home/kamimura/projects/tennis-lab/data/synthetic_data_generation/scene_variants/B00/clay-flare-100-30k-v001
