#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-evidence-ft-e13-trainval-r3-20260928
# provider=codex session=01a0e774-c56b-7721-b7a3-bd247184720b issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-3-cache-training}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: c873f0b8e2b8e2c683d3a19ae83bfc74272431a9 (branch campaign930/i935-3-cache-training)"
git checkout c873f0b8e2b8e2c683d3a19ae83bfc74272431a9 2>/dev/null || echo "[repro] WARN: checkout c873f0b8e2b8e2c683d3a19ae83bfc74272431a9 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-3-cache-training OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-3-cache-training/.venv/bin/python -u -m src.tasks.ball_refiner.scripts.generate_evidence --store /home/kamimura/projects/tennis-lab/data/ball_detection/ball-mix-v1 --checkpoint /home/kamimura/projects/tennis-lab/ckpt/ball_detection/run-i618-convnext-v2-ft-epoch13.ckpt --output /home/kamimura/projects/tennis-lab/data/ball_refiner/detector-ft-e13-trainval-r3-20260928 --sources tracknet meiji chat_annotation --splits train val --device cuda --stride 4 --batch-size 4 --max-candidates 8 --nms-kernel 5 --patch-size 5 --subpixel-refine
