#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: court_b00_regenerate_terminal
# provider=codex session=01a088da-0867-7e43-99b5-415e56dc292d issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab-worktrees/court-sfm-bounded}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: ad5554ab0cfdc433408b5762f3eb8792a30e6698 (branch codex/court-sfm-bounded)"
git checkout ad5554ab0cfdc433408b5762f3eb8792a30e6698 2>/dev/null || echo "[repro] WARN: checkout ad5554ab0cfdc433408b5762f3eb8792a30e6698 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# #931: the original command read these files from outputs/ (since deleted); the bundle copies are used instead.
# This bundle did not save them; ../run-court-b00-alignment-v14/run_requested.py was saved by a run at the same commit and path.
# --- original training command ---
PYTHONPATH=. .venv/bin/python "$SCRIPT_DIR/../run-court-b00-alignment-v14/run_requested.py" "$SCRIPT_DIR/B00-requested.yaml"
