#!/usr/bin/env python
r"""Summarize scalar CSV exported from TensorBoard event files.

This script reads a CSV file generated by ``parse_events.py``
(tag, step, wall_time, value) and prints per-tag statistics so that you can
quickly grasp overall training behavior.

Example:
    python scripts/tensorborad/summarize_scalars.py \
        --csv runs/tennis_mvpose_dev/version_1/\\
    events.out.tfevents.1763552511.DESKTOP-SPHMOVM.2336373.0.scalars.csv

"""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path


@dataclass
class TagStats:
    """Running statistics for a single scalar tag."""

    count: int = 0
    first_step: int | None = None
    first_value: float | None = None
    last_step: int | None = None
    last_value: float | None = None
    min_value: float | None = None
    min_step: int | None = None
    max_value: float | None = None
    max_step: int | None = None
    sum_value: float = 0.0
    sum_sq_value: float = 0.0


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Summarize scalar CSV exported from TensorBoard events. "
            "The CSV is expected to have columns: tag,step,wall_time,value."
        )
    )
    parser.add_argument(
        "--csv",
        type=Path,
        required=True,
        help="Path to a scalar CSV file produced by parse_events.py.",
    )
    parser.add_argument(
        "--markdown",
        action="store_true",
        help="Print summary as a Markdown table instead of plain text.",
    )
    return parser.parse_args()


def _update_stats(stats: TagStats, step: int, value: float) -> None:
    """Update running statistics for a single observation."""
    stats.count += 1

    if stats.count == 1:
        stats.first_step = step
        stats.first_value = value

    stats.last_step = step
    stats.last_value = value

    if stats.min_value is None or value < stats.min_value:
        stats.min_value = value
        stats.min_step = step

    if stats.max_value is None or value > stats.max_value:
        stats.max_value = value
        stats.max_step = step

    stats.sum_value += value
    stats.sum_sq_value += value * value


def load_tag_stats(csv_path: Path) -> dict[str, TagStats]:
    """Load scalar CSV and compute per-tag statistics.

    Args:
        csv_path (Path): Path to the scalar CSV file.

    Returns:
        dict[str, TagStats]: A mapping from tag name to TagStats.

    Raises:
        FileNotFoundError: If the CSV file does not exist.
        ValueError: If the CSV file does not contain required columns.

    """
    if not csv_path.is_file():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    stats_by_tag: dict[str, TagStats] = defaultdict(TagStats)

    with csv_path.open("r", newline="") as f:
        reader = csv.DictReader(f)

        required_columns = {"tag", "step", "wall_time", "value"}
        if not required_columns.issubset(reader.fieldnames or []):
            raise ValueError(
                "CSV must contain columns: tag, step, wall_time, value. "
                f"Found: {reader.fieldnames}"
            )

        for row in reader:
            tag = row["tag"]
            if tag is None:
                continue

            try:
                step = int(row["step"])
                value = float(row["value"])
            except (TypeError, ValueError):
                # Skip malformed rows.
                continue

            _update_stats(stats_by_tag[tag], step, value)

    return stats_by_tag


def infer_direction(tag: str) -> str:
    """Heuristically infer whether lower or higher is better for a tag.

    Args:
        tag (str): Tag name to analyze.

    Returns:
        str: "min" if the tag seems like a loss/error, otherwise "max".

    """
    lowered = tag.lower()
    keywords_min = ["loss", "error", "err", "l1", "l2"]
    if any(k in lowered for k in keywords_min):
        return "min"
    return "max"


def iter_summary_rows(stats_by_tag: dict[str, TagStats]) -> Iterable[dict]:
    """Yield per-tag summary rows with derived metrics."""
    for tag in sorted(stats_by_tag.keys()):
        s = stats_by_tag[tag]
        if s.count == 0:
            continue

        mean = s.sum_value / s.count
        var = s.sum_sq_value / s.count - mean * mean
        std = math.sqrt(var) if var > 0.0 else 0.0

        direction = infer_direction(tag)
        if direction == "min":
            best_value = s.min_value
            best_step = s.min_step
        else:
            best_value = s.max_value
            best_step = s.max_step

        yield {
            "tag": tag,
            "count": s.count,
            "first_step": s.first_step,
            "first_value": s.first_value,
            "last_step": s.last_step,
            "last_value": s.last_value,
            "min_value": s.min_value,
            "max_value": s.max_value,
            "mean": mean,
            "std": std,
            "direction": direction,
            "best_value": best_value,
            "best_step": best_step,
        }


def format_plain_table(rows: Iterable[dict]) -> str:
    """Format summary rows as a plain-text table."""
    rows = list(rows)
    if not rows:
        return "No data to summarize."

    headers = [
        "tag",
        "count",
        "first_step",
        "first_value",
        "last_step",
        "last_value",
        "min",
        "max",
        "mean",
        "std",
        "best",
        "best_step",
        "dir",
    ]

    def row_to_strs(r: dict) -> list[str]:
        return [
            r["tag"],
            f"{r['count']}",
            f"{r['first_step']}",
            f"{r['first_value']:.4g}" if r["first_value"] is not None else "-",
            f"{r['last_step']}",
            f"{r['last_value']:.4g}" if r["last_value"] is not None else "-",
            f"{r['min_value']:.4g}" if r["min_value"] is not None else "-",
            f"{r['max_value']:.4g}" if r["max_value"] is not None else "-",
            f"{r['mean']:.4g}",
            f"{r['std']:.3g}",
            f"{r['best_value']:.4g}" if r["best_value"] is not None else "-",
            f"{r['best_step']}",
            r["direction"],
        ]

    body = [row_to_strs(r) for r in rows]
    all_rows = [headers] + body

    # Compute column widths.
    widths = [max(len(str(row[i])) for row in all_rows) for i in range(len(headers))]

    def fmt_row(columns: list[str]) -> str:
        return "  ".join(col.ljust(widths[i]) for i, col in enumerate(columns))

    lines = [fmt_row(headers), "-" * (sum(widths) + 2 * (len(widths) - 1))]
    lines.extend(fmt_row(r) for r in body)
    return "\n".join(lines)


def format_markdown_table(rows: Iterable[dict]) -> str:
    """Format summary rows as a Markdown table."""
    rows = list(rows)
    if not rows:
        return "No data to summarize."

    headers = [
        "tag",
        "count",
        "first_step",
        "first_value",
        "last_step",
        "last_value",
        "min",
        "max",
        "mean",
        "std",
        "best",
        "best_step",
        "dir",
    ]

    def row_to_strs(r: dict) -> list[str]:
        return [
            r["tag"],
            f"{r['count']}",
            f"{r['first_step']}",
            f"{r['first_value']:.4g}" if r["first_value"] is not None else "-",
            f"{r['last_step']}",
            f"{r['last_value']:.4g}" if r["last_value"] is not None else "-",
            f"{r['min_value']:.4g}" if r["min_value"] is not None else "-",
            f"{r['max_value']:.4g}" if r["max_value"] is not None else "-",
            f"{r['mean']:.4g}",
            f"{r['std']:.3g}",
            f"{r['best_value']:.4g}" if r["best_value"] is not None else "-",
            f"{r['best_step']}",
            r["direction"],
        ]

    body = [row_to_strs(r) for r in rows]

    lines = []
    lines.append("| " + " | ".join(headers) + " |")
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")

    for r in body:
        lines.append("| " + " | ".join(r) + " |")

    return "\n".join(lines)


def main() -> None:
    """Entry point for the CLI utility."""
    args = parse_args()

    stats_by_tag = load_tag_stats(args.csv)
    rows = list(iter_summary_rows(stats_by_tag))

    if not rows:
        print(f"No scalar data found in CSV: {args.csv}")
        return

    print(f"Summary for scalar CSV: {args.csv}\n")

    table = format_markdown_table(rows) if args.markdown else format_plain_table(rows)

    print(table)


if __name__ == "__main__":  # pragma: no cover
    main()
