#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: ball_detection-web-inference
# provider=codex session=01a09e9c-5c30-7bf3-8e7b-9d2f9d6d3bd8 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/dataset-scene-review}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 003334e04821fd6a04f8e96c6c5b2a6c1a0aeb3b (branch codex/dataset-scene-review)"
# #931: the run used 782fc137 plus untracked source files (src/tasks/base/visualization/inference_queue.py and the review/inference UIs), which the bundle did not capture.
# They were first committed in 003334e0; the repro checks out that commit (the patch may not apply).
git checkout 003334e04821fd6a04f8e96c6c5b2a6c1a0aeb3b 2>/dev/null || echo "[repro] WARN: checkout 003334e04821fd6a04f8e96c6c5b2a6c1a0aeb3b failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
/home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.base.visualization.inference_queue /home/kamimura/projects/tennis-lab/.training_queue/ui_requests/ball_detection-915azon0/request.json
