#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i964-far-diagnosis-r3-20260929
# provider=codex session=01a0ec48-12c5-7920-b00e-3b2ecd8d82fa issue=964 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-2-tracking}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 53c292ecf6c5670d632528ce97e236d2a5e440f0 (branch campaign930/i964-2-tracking)"
git checkout 53c292ecf6c5670d632528ce97e236d2a5e440f0 2>/dev/null || echo "[repro] WARN: checkout 53c292ecf6c5670d632528ce97e236d2a5e440f0 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
bash /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-2-tracking/tests/benchmarks/player_detection_far_diagnosis.sh /home/kamimura/projects/tennis-lab /home/kamimura/projects/tennis-lab/outputs/player_detection/evaluate/pipeline_switch/i964-detectors-r1-20260929/meiji/comparison.json /home/kamimura/projects/tennis-lab/outputs/player_detection/evaluate/far_diagnosis/i964-far-r3-20260929
