#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-context-fullframe-pilot-r10-20260928
# provider=codex session=01a0e84e-36f0-7203-bec2-b324e2db9aa0 issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: c90b6153b3588cc1a73c238e93ee4e7030dc4304 (branch campaign930/i935-8-context-cache)"
git checkout c90b6153b3588cc1a73c238e93ee4e7030dc4304 2>/dev/null || echo "[repro] WARN: checkout c90b6153b3588cc1a73c238e93ee4e7030dc4304 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --signal=TERM --kill-after=15s 18m bash /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache/tests/benchmarks/ball_refiner_context_pilot.sh /home/kamimura/projects/tennis-lab /home/kamimura/projects/tennis-lab/data/ball_refiner/detector-ft-e13-trainval-r3-20260928 /home/kamimura/projects/tennis-lab/data/ball_refiner/context-fullframe-pilot-r10-20260928 /home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/context/i935-context-fullframe-pilot-r10-20260928
