#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i618_3dgs_blcs_v1_treatment_s731
# provider=codex session=019f984c-8bc1-7041-8e1d-362a5b11daa2 issue=618
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: ac9e640903a6dfaecb65fc980f5dcf408bbcd589 (branch main)"
git checkout ac9e640903a6dfaecb65fc980f5dcf408bbcd589 2>/dev/null || echo "[repro] WARN: checkout ac9e640903a6dfaecb65fc980f5dcf408bbcd589 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
.venv/bin/python -m src.tasks.ball_detection.scripts.train --config-name train_3dgs_blcs_v1
