"""PyTorch Lightning DataModule for BLCS."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import pytorch_lightning as pl
from torch.utils.data import DataLoader

from src.blcs.data.dataset import (
    BallTrajectoryDataset,
    collate_multiview_trajectories,
    collate_trajectories,
)
from src.common.data.scene_batch_sampler import (
    build_scene_sampler,
    resolve_scene_sampler_mode,
)

if TYPE_CHECKING:
    from omegaconf import DictConfig


class BLCSDataModule(pl.LightningDataModule):
    """Lightning DataModule for BLCS training.

    This module handles the creation of training, validation, and test
    dataloaders for ball trajectory data. Uses split files (train.txt,
    val.txt, test.txt) generated by BLCSDatasetWriter.
    """

    def __init__(self, config: DictConfig | None = None) -> None:
        """Initialize the DataModule.

        Args:
            config: Configuration dictionary with data parameters.

        """
        super().__init__()
        self.config = config or {}

        data_cfg = self.config.get("data", {})
        self.batch_size = data_cfg.get("batch_size", 32)
        self.num_workers = data_cfg.get("num_workers", 4)
        self.pin_memory = bool(data_cfg.get("pin_memory", True))
        self.scene_dir = Path(data_cfg.get("scene_dir", "data/blcs"))
        self.scene_sampler_mode = resolve_scene_sampler_mode(data_cfg)
        self.scenes_per_batch = int(data_cfg.get("scenes_per_batch", 1))
        self.chunk_max_scenes = int(data_cfg.get("chunk_max_scenes", 64))

        self.train_dataset: BallTrajectoryDataset | None = None
        self.val_dataset: BallTrajectoryDataset | None = None
        self.test_dataset: BallTrajectoryDataset | None = None

    def setup(self, stage: str | None = None) -> None:
        """Set up datasets for the given stage.

        Args:
            stage: Either 'fit', 'validate', 'test', or None for all.

        """
        if not self.scene_dir.exists():
            raise RuntimeError(
                f"Scene directory not found: {self.scene_dir}. "
                "Run blcs.scripts.generate_dataset to create the dataset."
            )

        if stage == "fit" or stage is None:
            # Training dataset with augmentation
            train_split = self.scene_dir / "train.txt"
            if train_split.exists():
                self.train_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    split_file="train.txt",
                    config=self.config,
                    augment=True,
                    output_mode="single",
                )
            else:
                # Fallback: use all data
                self.train_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    config=self.config,
                    augment=True,
                    output_mode="single",
                )

            # Validation dataset without augmentation
            val_split = self.scene_dir / "val.txt"
            if val_split.exists():
                self.val_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    split_file="val.txt",
                    config=self.config,
                    augment=False,
                    output_mode="single",
                )
            else:
                self.val_dataset = self.train_dataset

        if stage == "test" or stage is None:
            # Test dataset without augmentation
            test_split = self.scene_dir / "test.txt"
            if test_split.exists():
                self.test_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    split_file="test.txt",
                    config=self.config,
                    augment=False,
                    output_mode="single",
                )
            else:
                self.test_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    config=self.config,
                    augment=False,
                    output_mode="single",
                )

    def train_dataloader(self) -> DataLoader:
        """Create training dataloader.

        Returns:
            DataLoader: Training dataloader.

        """
        if self.train_dataset is None:
            raise RuntimeError("Call setup('fit') before train_dataloader()")

        batch_sampler = build_scene_sampler(
            self.train_dataset,
            batch_size=self.batch_size,
            mode=self.scene_sampler_mode,
            scenes_per_batch=self.scenes_per_batch,
            chunk_max_scenes=self.chunk_max_scenes,
            drop_last=True,
            shuffle=True,
        )
        if batch_sampler is not None:
            return DataLoader(
                self.train_dataset,
                batch_sampler=batch_sampler,
                num_workers=self.num_workers,
                pin_memory=True,
                collate_fn=collate_trajectories,
            )

        return DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            drop_last=True,
            collate_fn=collate_trajectories,
        )

    def val_dataloader(self) -> DataLoader:
        """Create validation dataloader.

        Returns:
            DataLoader: Validation dataloader.

        """
        if self.val_dataset is None:
            raise RuntimeError("Call setup('fit') before val_dataloader()")

        batch_sampler = build_scene_sampler(
            self.val_dataset,
            batch_size=self.batch_size,
            mode=self.scene_sampler_mode,
            scenes_per_batch=self.scenes_per_batch,
            chunk_max_scenes=self.chunk_max_scenes,
            drop_last=False,
            shuffle=False,
        )
        if batch_sampler is not None:
            return DataLoader(
                self.val_dataset,
                batch_sampler=batch_sampler,
                num_workers=self.num_workers,
                pin_memory=True,
                collate_fn=collate_trajectories,
            )

        return DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            collate_fn=collate_trajectories,
        )

    def test_dataloader(self) -> DataLoader:
        """Create test dataloader.

        Returns:
            DataLoader: Test dataloader.

        """
        if self.test_dataset is None:
            raise RuntimeError("Call setup('test') before test_dataloader()")

        batch_sampler = build_scene_sampler(
            self.test_dataset,
            batch_size=self.batch_size,
            mode=self.scene_sampler_mode,
            scenes_per_batch=self.scenes_per_batch,
            chunk_max_scenes=self.chunk_max_scenes,
            drop_last=False,
            shuffle=False,
        )
        if batch_sampler is not None:
            return DataLoader(
                self.test_dataset,
                batch_sampler=batch_sampler,
                num_workers=self.num_workers,
                pin_memory=True,
                collate_fn=collate_trajectories,
            )

        return DataLoader(
            self.test_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            collate_fn=collate_trajectories,
        )


class BLCSMultiViewDataModule(pl.LightningDataModule):
    """Lightning DataModule for multi-view BLCS training.

    This module creates train/val/test dataloaders using BallTrajectoryDataset
    to provide ball trajectory observations from multiple cameras simultaneously.
    """

    def __init__(self, config: DictConfig | None = None) -> None:
        """Initialize the multi-view DataModule.

        Args:
            config: Configuration dictionary with data parameters.

        """
        super().__init__()
        self.config = config or {}

        data_cfg = self.config.get("data", {})
        self.batch_size = data_cfg.get("batch_size", 16)
        self.num_workers = data_cfg.get("num_workers", 4)
        self.pin_memory = bool(data_cfg.get("pin_memory", True))
        self.scene_dir = Path(data_cfg.get("scene_dir", "data/blcs"))
        self.num_views = data_cfg.get("num_views", 2)
        self.min_cameras = data_cfg.get("min_cameras", 2)
        self.scene_sampler_mode = resolve_scene_sampler_mode(data_cfg)
        self.scenes_per_batch = int(data_cfg.get("scenes_per_batch", 1))
        self.chunk_max_scenes = int(data_cfg.get("chunk_max_scenes", 64))

        self.train_dataset: BallTrajectoryDataset | None = None
        self.val_dataset: BallTrajectoryDataset | None = None
        self.test_dataset: BallTrajectoryDataset | None = None

    def setup(self, stage: str | None = None) -> None:
        """Set up datasets for the given stage.

        Args:
            stage: Either 'fit', 'validate', 'test', or None for all.

        """
        if stage == "fit" or stage is None:
            # Try to load from split files
            train_split = self.scene_dir / "train.txt"
            val_split = self.scene_dir / "val.txt"

            if train_split.exists():
                self.train_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    split_file=train_split,
                    config=self.config,
                    augment=True,
                    output_mode="multiview",
                    num_views=self.num_views,
                    min_cameras=self.min_cameras,
                )
            else:
                # Fall back to loading all scenes
                self.train_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    config=self.config,
                    augment=True,
                    output_mode="multiview",
                    num_views=self.num_views,
                    min_cameras=self.min_cameras,
                )

            if val_split.exists():
                self.val_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    split_file=val_split,
                    config=self.config,
                    augment=False,
                    output_mode="multiview",
                    num_views=self.num_views,
                    min_cameras=self.min_cameras,
                )
            else:
                self.val_dataset = self.train_dataset

        if stage == "test" or stage is None:
            test_split = self.scene_dir / "test.txt"
            if test_split.exists():
                self.test_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    split_file=test_split,
                    config=self.config,
                    augment=False,
                    output_mode="multiview",
                    num_views=self.num_views,
                    min_cameras=self.min_cameras,
                )
            else:
                self.test_dataset = BallTrajectoryDataset(
                    scene_dir=self.scene_dir,
                    config=self.config,
                    augment=False,
                    output_mode="multiview",
                    num_views=self.num_views,
                    min_cameras=self.min_cameras,
                )

    def train_dataloader(self) -> DataLoader:
        """Create training dataloader.

        Returns:
            DataLoader: Training dataloader.

        """
        if self.train_dataset is None:
            raise RuntimeError("Call setup('fit') before train_dataloader()")

        batch_sampler = build_scene_sampler(
            self.train_dataset,
            batch_size=self.batch_size,
            mode=self.scene_sampler_mode,
            scenes_per_batch=self.scenes_per_batch,
            chunk_max_scenes=self.chunk_max_scenes,
            drop_last=True,
            shuffle=True,
        )
        if batch_sampler is not None:
            return DataLoader(
                self.train_dataset,
                batch_sampler=batch_sampler,
                num_workers=self.num_workers,
                pin_memory=self.pin_memory,
                collate_fn=collate_multiview_trajectories,
            )

        return DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            drop_last=True,
            collate_fn=collate_multiview_trajectories,
        )

    def val_dataloader(self) -> DataLoader:
        """Create validation dataloader.

        Returns:
            DataLoader: Validation dataloader.

        """
        if self.val_dataset is None:
            raise RuntimeError("Call setup('fit') before val_dataloader()")

        batch_sampler = build_scene_sampler(
            self.val_dataset,
            batch_size=self.batch_size,
            mode=self.scene_sampler_mode,
            scenes_per_batch=self.scenes_per_batch,
            chunk_max_scenes=self.chunk_max_scenes,
            drop_last=False,
            shuffle=False,
        )
        if batch_sampler is not None:
            return DataLoader(
                self.val_dataset,
                batch_sampler=batch_sampler,
                num_workers=self.num_workers,
                pin_memory=self.pin_memory,
                collate_fn=collate_multiview_trajectories,
            )

        return DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            collate_fn=collate_multiview_trajectories,
        )

    def test_dataloader(self) -> DataLoader:
        """Create test dataloader.

        Returns:
            DataLoader: Test dataloader.

        """
        if self.test_dataset is None:
            raise RuntimeError("Call setup('test') before test_dataloader()")

        batch_sampler = build_scene_sampler(
            self.test_dataset,
            batch_size=self.batch_size,
            mode=self.scene_sampler_mode,
            scenes_per_batch=self.scenes_per_batch,
            chunk_max_scenes=self.chunk_max_scenes,
            drop_last=False,
            shuffle=False,
        )
        if batch_sampler is not None:
            return DataLoader(
                self.test_dataset,
                batch_sampler=batch_sampler,
                num_workers=self.num_workers,
                pin_memory=self.pin_memory,
                collate_fn=collate_multiview_trajectories,
            )

        return DataLoader(
            self.test_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            collate_fn=collate_multiview_trajectories,
        )


if __name__ == "__main__":
    import json
    from tempfile import TemporaryDirectory

    import numpy as np

    with TemporaryDirectory() as tmp_dir:
        base = Path(tmp_dir)
        scene_path = base / "scene_000.npz"
        np.savez(
            scene_path,
            meta=json.dumps({"num_frames": 2}),
            num_cameras=np.array(1),
            cam_0_ball_uv=np.zeros((2, 2), dtype=np.float32),
            cam_0_ball_visible=np.ones((2,), dtype=np.float32),
            cam_0_court_kp_uv=np.zeros((20, 2), dtype=np.float32),
            cam_0_court_kp_visible=np.ones((20,), dtype=np.float32),
            ball_pos_norm=np.zeros((2, 3), dtype=np.float32),
            ball_vel_world=np.zeros((2, 3), dtype=np.float32),
        )
        cfg = {"data": {"scene_dir": str(base), "batch_size": 1, "num_workers": 0}}
        dm = BLCSDataModule(cfg)
        dm.num_workers = 0
        dm.pin_memory = False
        dm.setup("fit")
        batch = next(iter(dm.train_dataloader()))
        assert batch["ball_uv"].shape[0] == 1
        print("blcs.data.datamodule smoke ok")
