#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i986-dpt-pretrain-s42-u60000-v1
# provider=codex session=01a0fb0c-97b5-7851-b805-25dae445a6a2 issue=986 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-dpt-pretrain-s42}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: e3f1356163e7b2009c580fc1727c1a413c5889a3 (branch HEAD)"
git checkout e3f1356163e7b2009c580fc1727c1a413c5889a3 2>/dev/null || echo "[repro] WARN: checkout e3f1356163e7b2009c580fc1727c1a413c5889a3 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 TORCHINDUCTOR_COMPILE_THREADS=2 PYTHONUNBUFFERED=1 .venv/bin/python -m src.tasks.ball_detection.scripts.pretrain_mdd_dpt --manifest /home/kamimura/projects/tennis-lab/outputs/ball_detection/precompute/mdd_coordinates_36/20261008-fps124-v1/mdd_only_windows.json --model-config /home/kamimura/projects/tennis-lab/.claude/worktrees/ball-dpt-pretrain-s42/src/tasks/ball_detection/configs/model/mdd_dpt_pretrain.yaml --output /home/kamimura/projects/tennis-lab/outputs/ball_detection/train/mdd-dpt-pretrain/s42-u60000-v1 --epochs 10 --windows-per-epoch 6000 --learning-rate .0002 --warmup-updates 500 --seed 42 --device cuda --precision bf16 --batch-size 1 --num-workers 8 --prefetch-factor 4 --cpu-threads 2 --pin-memory --jpeg-decoder nvjpeg --input-verification upfront --image-prefetch --compile-mode default --selection-scope common --log-every 50 --preview-clips 3
