#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-vitpose-precision-v1
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=half logical_slot=0
set -uo pipefail
export TENNIS_GPU_RESOURCE=half
export TENNIS_GPU_SLOT=0
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4348077d8f7a0b35ab58350232cf4ccb607990f1 (branch codex/slcs-real-rgb)"
git checkout 4348077d8f7a0b35ab58350232cf4ccb607990f1 2>/dev/null || echo "[repro] WARN: checkout 4348077d8f7a0b35ab58350232cf4ccb607990f1 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python -m scripts.analysis.benchmark_vitpose_precision --clip /home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_000 --observations /home/kamimura/projects/tennis-lab/outputs/tennis_scene/precompute/meiji_dino_vitpose/s42-001/video_000/clip_000 --checkpoint /home/kamimura/projects/tennis-lab/third_party/GVHMR/inputs/checkpoints/vitpose/vitpose-h-multi-coco.pth --output /home/kamimura/projects/tennis-lab/outputs/tennis_scene/evaluate/vitpose_precision/s42-001
