#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i714-court-dinov3-dpt-b00-v4-geometry-pos1
# provider=codex session=019ff617-dfb3-7182-8c2a-1d0705cf3ff0 issue=714
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-714-court-data-composition-v2}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 18bac72eac5954a95db79f55d26cea250ddbad9c (branch feat/issue-714-court-data-composition-v2)"
git checkout 18bac72eac5954a95db79f55d26cea250ddbad9c 2>/dev/null || echo "[repro] WARN: checkout 18bac72eac5954a95db79f55d26cea250ddbad9c failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=. PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.court_detection.scripts.train data/source=synthetic_court data/processing=kp model/encoder=dinov3 model/decoder=dpt training=lora loss.kp.positive_weight=1.0 data.batch_size=4 data.num_workers=4 data.augmentation.train_scales='[256]' data.augmentation.val_short_side=512 training.trainer.max_epochs=50 training.checkpoint.monitor=val/kp_mean_dist training.checkpoint.mode=min training.early_stopping.monitor=val/kp_mean_dist training.early_stopping.mode=min training.early_stopping.patience=10 training.qualitative_logging.enabled=false run.seed=714 run.output_dir=issue714/i714-court-dinov3-dpt-b00-v4-geometry-pos1 run.test_after_fit=true
