#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: plcs-multiview-all-outputs-beta01-gpu1
# provider=codex session=01a03ee0-c172-7d22-81d3-c07127757135 issue=
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-reprojection-loss}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 101120f100474781121ca0e83d65b5da9a2d7a20 (branch exp/plcs-reprojection-loss)"
git checkout 101120f100474781121ca0e83d65b5da9a2d7a20 2>/dev/null || echo "[repro] WARN: checkout 101120f100474781121ca0e83d65b5da9a2d7a20 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=1 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True TENNIS_RUN_ID=1787796355222865602_direct_plcs-multiview-all-outputs-beta01-gpu1 TENNIS_REPRO_DIR=/home/kamimura/projects/tennis-lab/.training_queue/repro/1787796355222865602_direct_plcs-multiview-all-outputs-beta01-gpu1 .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_canonical loss=all_outputs_beta01 data.scene_dir=plcs_canonical_pose_beta data.batch_size=4 'data.num_views_range=[2,2]' 'data.seq_len_range=[16,16]' data.num_workers=2 training.trainer.accumulate_grad_batches=1 training.trainer.precision=16-mixed training.trainer.max_epochs=50 training.compile.enabled=false training.qualitative_logging.enabled=false training.trainer.enable_progress_bar=false training.trainer.enable_model_summary=false run.output_dir=plcs/plcs_multiview_all_outputs_beta01_gpu1 paths.artifact_root=/home/kamimura/projects/tennis-lab/.training_queue/repro/1787796355222865602_direct_plcs-multiview-all-outputs-beta01-gpu1
