#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i936-x0-memory-r2-20260929
# provider=codex session=01a0ed26-b4eb-7c30-baea-c8a3cb41cf9e issue=936 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: c800d9f5888e4f63c0c4c4bba9a805171d5fbb9d (branch campaign930/i936-2-synthetic-diffusion)"
git checkout c800d9f5888e4f63c0c4c4bba9a805171d5fbb9d 2>/dev/null || echo "[repro] WARN: checkout c800d9f5888e4f63c0c4c4bba9a805171d5fbb9d failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --signal=TERM --kill-after=15s 840s env CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation/.venv/bin/python -u -m src.tasks.ball_refiner.scripts.memory_smoke_3d --config /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation/src/tasks/ball_refiner/refiner_3d/memory_smoke.yaml --fixture /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation/src/tasks/ball_refiner/refiner_3d/fixtures/meiji_video_002_clip_010.json --output /home/kamimura/projects/tennis-lab/outputs/ball_refiner/train/i936-memory-smoke/gpu-r2-20260929 --device cuda
