#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: shared_compile_blcs_compiled_b_3ep_v4
# provider=codex session=01a023be-2b89-7a33-9856-7b46d34326d5 issue=
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/shared-torch-compile}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 2f92bcb473e7ba653a6998db1049551bd7ac7938 (branch feat/shared-torch-compile)"
git checkout 2f92bcb473e7ba653a6998db1049551bd7ac7938 2>/dev/null || echo "[repro] WARN: checkout 2f92bcb473e7ba653a6998db1049551bd7ac7938 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
/usr/bin/time -f "BENCHMARK_WALL_SECONDS=%e BENCHMARK_MAX_RSS_KB=%M" env TORCHINDUCTOR_CACHE_DIR=/home/kamimura/projects/tennis-lab/.cache/torchinductor/shared_compile_abba_v4_compiled_b PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -c "import atexit,runpy,torch; atexit.register(lambda: print(\"BENCHMARK_PEAK_CUDA_BYTES=\"+str(torch.cuda.max_memory_allocated()))); runpy.run_module(\"src.tasks.blcs.scripts.train\",run_name=\"__main__\")" --config-name train_tracking paths.data_root=/home/kamimura/projects/tennis-lab/data paths.output_root=/home/kamimura/projects/tennis-lab/outputs paths.checkpoint_root=/home/kamimura/projects/tennis-lab/ckpt data.scene_dir=blcs/compile_benchmark_schema_v1 data.seq_len_range=[1024,1024] data.num_views_range=[3,3] data.batch_size=1 model=track_query_small model.dropout=0.0 model.cswa.backend=cuda training.trainer.precision=32-true training.trainer.max_epochs=3 training.trainer.log_every_n_steps=1 training.trainer.enable_model_summary=false training.warmup_steps=0 training.checkpoint.enabled=false training.early_stopping.enabled=false training.lr_monitor.enabled=false training.qualitative_logging.enabled=false run.output_dir=blcs/compile_training_abba_v4/compiled_b
