repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff (fix)
        entry: ./scripts/run_in_repo_venv.sh ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
        files: ^(src|tests|\.spin)/
      - id: mypy
        name: mypy
        entry: ./scripts/run_in_repo_venv.sh mypy --follow-imports=skip
        language: system
        types: [python]
        files: ^(src|tests|\.spin)/
        require_serial: true
