#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-evidence-mixed-e9-trainval-r17-20260930
# provider=codex session=01a0ef7d-1eb8-7973-b7c6-8b0604efd8ef issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-10-detector-selection}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 9f2256370cb52af71c6edf28d58ce7182923adb7 (branch campaign930/i935-10-detector-selection)"
git checkout 9f2256370cb52af71c6edf28d58ce7182923adb7 2>/dev/null || echo "[repro] WARN: checkout 9f2256370cb52af71c6edf28d58ce7182923adb7 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --signal=TERM --kill-after=15s 5385s env PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-10-detector-selection OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 OPENBLAS_NUM_THREADS=4 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-10-detector-selection/.venv/bin/python -u /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-10-detector-selection/knowledge/runs/run-i935-mixed-ft-val-recall-s42-r16-20260929/rebuild_cache.py --plan /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-10-detector-selection/knowledge/runs/run-i935-mixed-ft-val-recall-s42-r16-20260929/cache_plan.json
