#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-meiji-checkpoint-hash-probe-v2b
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: bbe6a703022c6b44a765b6f570e6fe7b85eceb7b (branch codex/slcs-real-rgb)"
git checkout bbe6a703022c6b44a765b6f570e6fe7b85eceb7b 2>/dev/null || echo "[repro] WARN: checkout bbe6a703022c6b44a765b6f570e6fe7b85eceb7b failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout 10m env PYTHONPATH=. CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python knowledge/runs/run-slcs-meiji-checkpoint-hash-probe-v2/probe.py --output-dir outputs/tennis_scene/analyze/meiji_hash_probe_v2/s42-002
