#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1050-convnext_v2-s42-u60000
# provider=codex session=01a0fb0c-97b5-7851-b805-25dae445a6a2 issue=1050 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-cnn-campaign-20261009}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4cb8b70c9cae3e7841944e94295615e584947402 (branch HEAD)"
git checkout 4cb8b70c9cae3e7841944e94295615e584947402 2>/dev/null || echo "[repro] WARN: checkout 4cb8b70c9cae3e7841944e94295615e584947402 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 TORCHINDUCTOR_COMPILE_THREADS=2 PYTHONUNBUFFERED=1 /home/kamimura/projects/tennis-lab/.claude/worktrees/ball-cnn-campaign-20261009/.venv/bin/python -m src.tasks.ball_detection.scripts.train_cnn_candidate --manifest /home/kamimura/projects/tennis-lab/outputs/ball_detection/precompute/mdd_coordinates_36/20261008-fps124-v1/mdd_only_windows.json --model-config /home/kamimura/projects/tennis-lab/.claude/worktrees/ball-cnn-campaign-20261009/src/tasks/ball_detection/configs/model/mdd_dpt_convnext_v2.yaml --output /home/kamimura/projects/tennis-lab/outputs/ball_detection/train/mdd-cnn-comparison/convnext_v2-s42-v1 --smoke-output /home/kamimura/projects/tennis-lab/outputs/ball_detection/analyze/mdd-cnn-smoke/20261009/convnext_v2
