#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-full-real-rgb-no-ball-smooth-e60-takeover-v2
# provider=codex session=01a0b71f-c516-75b2-ac58-0c92e8a4f098 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 48f75c7777cb7cf4d597589bed612750da975d49 (branch codex/slcs-real-rgb)"
git checkout 48f75c7777cb7cf4d597589bed612750da975d49 2>/dev/null || echo "[repro] WARN: checkout 48f75c7777cb7cf4d597589bed612750da975d49 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python -m src.tasks.slcs.scripts.train --config-name train_real_rgb loss.ball_position_smoothness_weight=0.0 run.output_dir=slcs/train/real_rgb_no_ball_smooth/s42-takeover-002
