#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1034-nht-b00-p90-s42-a0
# provider=codex session=01a1106e-187c-7163-be4e-9f1673767ad9 issue=1034 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 8e1a3acadf18c0b54eade155d45d9fb8090dbb94 (branch research/sfm-night-20261006)"
git checkout 8e1a3acadf18c0b54eade155d45d9fb8090dbb94 2>/dev/null || echo "[repro] WARN: checkout 8e1a3acadf18c0b54eade155d45d9fb8090dbb94 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.venv/bin/python -m experiments.sfm_comparison.run_command --campaign /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/outputs/aris/i1034-sfm-night-20261006 --run-id nht-b00-90-s42-a0 --stage sfm --seconds 1200 --metrics-source /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/outputs/aris/i1034-sfm-night-20261006/baseline/sfm/candidates/sift-incremental/metrics.json --required-path /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/outputs/aris/i1034-sfm-night-20261006/baseline/sfm/candidates/sift-incremental/metrics.json -- /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.cache/runtimes/nht-sfm/bin/nht-reconstruct --scene-id B00-i1034-p90 --workspace /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/outputs/aris/i1034-sfm-night-20261006/baseline --config /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/outputs/aris/i1034-sfm-night-20261006/configs/nht-sift.yaml --from-stage sfm --through-stage sfm
