#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-calibration-hdr-ft-e13-r5-20260928
# provider=codex session=01a0e7ce-fb4f-7891-bdd9-2fd526d5b391 issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-5-evaluation}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 7195911befde371c39f375981cb637bd117f5861 (branch campaign930/i935-5-evaluation)"
git checkout 7195911befde371c39f375981cb637bd117f5861 2>/dev/null || echo "[repro] WARN: checkout 7195911befde371c39f375981cb637bd117f5861 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-5-evaluation OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-5-evaluation/.venv/bin/python -u -m src.tasks.ball_refiner.scripts.evaluate_pilot paths.artifact_root=/home/kamimura/projects/tennis-lab/outputs paths.output_root=/home/kamimura/projects/tennis-lab/outputs evaluate.training_run=ball_refiner/train/detector_only/i935-ft-e13-s42-r4-20260928 evaluate.partition=calibration run.output_dir=ball_refiner/evaluate/detector_only/i935-ft-e13-calibration-r5-20260928
