#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i964-clip000-qualification-r14-20261001
# provider=codex session=01a0f34a-563b-75e3-be1f-3354c2608e8f issue=964 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-2-tracking}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: d189770794ab7f97c745a82d6d998067629e6b28 (branch campaign930/i964-2-tracking)"
git checkout d189770794ab7f97c745a82d6d998067629e6b28 2>/dev/null || echo "[repro] WARN: checkout d189770794ab7f97c745a82d6d998067629e6b28 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout -k 10s 5380s bash /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-2-tracking/tests/benchmarks/pipeline_qualification.sh /home/kamimura/projects/tennis-lab /home/kamimura/projects/tennis-lab/outputs/tennis_scene/evaluate/i964-qualification-r14-20261001
