#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-meiji-one-clip-repro-takeover-v2
# provider=codex session=01a0b71f-c516-75b2-ac58-0c92e8a4f098 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 57726f2c8f38fe50ab3870a7a030fad78ab14b4b (branch codex/slcs-real-rgb)"
git checkout 57726f2c8f38fe50ab3870a7a030fad78ab14b4b 2>/dev/null || echo "[repro] WARN: checkout 57726f2c8f38fe50ab3870a7a030fad78ab14b4b failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python knowledge/runs/run-slcs-meiji-one-clip-repro-v1/probe.py --output-dir /home/kamimura/projects/tennis-lab/outputs/tennis_scene/analyze/meiji_one_clip_repro/s42-takeover-001 --run-id takeover001
