#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: court_b02_regenerate
# provider=codex session=01a088da-0867-7e43-99b5-415e56dc292d issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab-worktrees/court-sfm-bounded}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: ecf64a7aa6e21ed11e619cb75360ef44377aea8b (branch codex/court-sfm-bounded)"
git checkout ecf64a7aa6e21ed11e619cb75360ef44377aea8b 2>/dev/null || echo "[repro] WARN: checkout ecf64a7aa6e21ed11e619cb75360ef44377aea8b failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=. .venv/bin/python outputs/court-b00-b03-generation/run_requested.py outputs/court-b00-b03-generation/B02-requested.yaml
