#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: plcs-track-reid-gpu-smoke-20260924
# provider=codex session=01a0d0f9-6057-7961-ad6b-adc46744d619 issue=915 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-track-reid}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 53db1868054e8330126d34a458edb1424646d61e (branch codex/plcs-track-reid)"
git checkout 53db1868054e8330126d34a458edb1424646d61e 2>/dev/null || echo "[repro] WARN: checkout 53db1868054e8330126d34a458edb1424646d61e failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=1 PYTHONPATH=. PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python tests/benchmarks/person_association.py --device cuda --data-root /home/kamimura/projects/tennis-lab/data --scene-dir plcs/tracked_person_reid_v1 --output /home/kamimura/projects/tennis-lab/outputs/plcs/diagnostics/tracked_reid_smoke_20260924
