defaults:
  - court_coordinate_normalization: v2
  - generation: single_object
  - paths: default
  - simulation: default
  - camera: default
  - motion_sources: default
  - run: generate_dataset
  - _self_

external_assets:
  smplh_model_path: smplx/smplh

run:
  output_dir: plcs_broadcast_norm_v2

hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},hydra/plcs/generate_dataset_norm_v2}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
