defaults:
  - court_keypoints: physical_v1
  - generation: single_object
  - paths: default
  - simulation: default
  - camera: default
  - motion_sources: accad
  - run: generate_dataset
  - _self_

external_assets:
  smplh_model_path: smplx/smplh
  coco17_regressor_path: src/submodules/vendor/gvhmr/body_model/data/smpl_coco17_J_regressor.pt

hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},hydra/plcs/generate_dataset}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
