#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1032-c-recon-consistency-s42-v1
# provider=claude session=72300f25-ca01-4859-9c8e-1ce0c340f9c3 issue=1032 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-1032-physics-refiner}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 5251d2f693dc7cabe5b766a5073b8585f6b98b2b (branch feat/issue-1032-p5-physics-heads)"
git checkout 5251d2f693dc7cabe5b766a5073b8585f6b98b2b 2>/dev/null || echo "[repro] WARN: checkout 5251d2f693dc7cabe5b766a5073b8585f6b98b2b failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 .venv/bin/python -m src.tasks.ball_refiner_3d.scripts.train paths.data_root=/home/kamimura/projects/tennis-lab/data paths.output_root=/home/kamimura/projects/tennis-lab/outputs run.output_dir=ball_refiner_3d/train/i1032-physics/c-recon-consistency-s42-v1 model.physics_heads=true loss.physics.field_weight=1.0 loss.physics.segment_weight=1.0 loss.physics.reconstruction_weight=1.0 loss.physics.consistency_weight=1.0 loss.physics.consistency_gradient=direct
