#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i590_courtkp14
# provider=claude session=e6b05f74-5cf0-4470-9219-ca1b8fb11eec issue=590
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 175045f8a9e7efce4585d658083defd895ad62f6 (branch feat/tennis-scene-submodules-gvhmr)"
git checkout 175045f8a9e7efce4585d658083defd895ad62f6 2>/dev/null || echo "[repro] WARN: checkout 175045f8a9e7efce4585d658083defd895ad62f6 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split model.num_layers=0 model.num_task_layers=6 data=chunked_multiview_sequence_bs8 data.num_court_kp=14 data.batch_size=8 training.trainer.accumulate_grad_batches=1 data.seq_len_range=[64,256] loss=canonical_rot loss.position_weight=8.0 loss.canonical_pose_weight=0.0 loss.joint_angle_weight=0.0 loss.torsion_angle_weight=0.0 loss.torso_twist_weight=0.0 loss.bone_length_weight=0.0 training.trainer.max_epochs=200 training.early_stopping.enabled=false run.gpus=1
