#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-full-real-rgb-gap48-e60-resume-v2
# provider=codex session=01a0b71f-c516-75b2-ac58-0c92e8a4f098 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 1758eda44debb618395fc7fe86e9ecb30f32a4fa (branch codex/slcs-real-rgb)"
git checkout 1758eda44debb618395fc7fe86e9ecb30f32a4fa 2>/dev/null || echo "[repro] WARN: checkout 1758eda44debb618395fc7fe86e9ecb30f32a4fa failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env PYTHONUNBUFFERED=1 PYTHONFAULTHANDLER=1 CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python -m src.tasks.slcs.scripts.train --config-name train_real_rgb_gap48 paths.checkpoint_root=/home/kamimura/projects/tennis-lab/outputs run.resume=slcs/train/real_rgb_gap48/s42-takeover-001/logs/version_0/checkpoints/last.ckpt run.test_after_fit=false run.output_dir=slcs/train/real_rgb_gap48/s42-takeover-001
