#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i545_s4_h4
# provider=claude session=8722d9dc-5894-4536-8e54-d03e3e34949a issue=545
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/wt/i545-prune}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4396ee5bcad62007b6b6ee154cd7e28d995af41b (branch feat/training-queue-auto-prune-ckpt)"
git checkout 4396ee5bcad62007b6b6ee154cd7e28d995af41b 2>/dev/null || echo "[repro] WARN: checkout 4396ee5bcad62007b6b6ee154cd7e28d995af41b failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split model.num_layers=4 model.num_task_layers=4 data=chunked_multiview_sequence_bs8 data.batch_size=8 data.seq_len_range=[64,256] training.trainer.accumulate_grad_batches=1 loss=canonical_rot training.trainer.max_epochs=200 training.early_stopping.enabled=false run.gpus=1
