#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i541_parameff_longtrain
# provider=claude session=d22b7d68-7d91-4a6f-862d-434085e5d2d9 issue=541
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 6399aa6f6848994957412eebabf4a4330c95cd15 (branch feat/issue-533-experiment-log-format)"
git checkout 6399aa6f6848994957412eebabf4a4330c95cd15 2>/dev/null || echo "[repro] WARN: checkout 6399aa6f6848994957412eebabf4a4330c95cd15 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split_eff loss=canonical_rot data=multiview_sequence training.trainer.max_epochs=400 run.gpus=1
