#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: plcs_accad_gvhmr_meiji_1000_v1_train
# provider=codex session=01a09b2a-4049-7231-8076-a15ca05d9c7e issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-gvhmr-motion-source}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: b8ccc6bac5beac082b97e94c8b42edd9da8d2f40 (branch feat/plcs-gvhmr-motion-source)"
git checkout b8ccc6bac5beac082b97e94c8b42edd9da8d2f40 2>/dev/null || echo "[repro] WARN: checkout b8ccc6bac5beac082b97e94c8b42edd9da8d2f40 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.plcs.scripts.train data.scene_dir=plcs/accad_gvhmr_meiji_1000_v1 paths.project_root=/home/kamimura/projects/tennis-lab run.output_dir=plcs/accad_gvhmr_meiji_1000_v1_train model=multiview_axial_base training.trainer.max_epochs=200 training.compile.enabled=false training.checkpoint.save_top_k=1 run.seed=42
