defaults:
  - data: ball_detection
  - training: ball_detection
  - logging: default
  - metrics: ball_detection
  - run: ball_detection
  - model: dinov3_heatmap
  - _self_

hydra:
  run:
    dir: .
  job:
    chdir: false
