defaults:
  - data: event_detection
  - training: event_detection
  - loss: event_detection
  - logging: default
  - metrics: event_detection
  - run: event_detection
  - model: event_detection_transformer
  - _self_

hydra:
  run:
    dir: outputs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
