#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i991-i1014-coordinates-report-20261005-v2
# provider=codex session=01a10697-63da-75b2-ae84-f2980da51c23 issue=1014 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/coordinate-ball-refiners-991-1014}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 0bdeb9514ae1e780f1d8e8e08a431b2aa9f5143c (branch codex/coordinate-ball-refiners-991-1014)"
git checkout 0bdeb9514ae1e780f1d8e8e08a431b2aa9f5143c 2>/dev/null || echo "[repro] WARN: checkout 0bdeb9514ae1e780f1d8e8e08a431b2aa9f5143c failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=. OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 .venv/bin/python tests/benchmarks/ball_refiner_coordinates_report.py --runs-root /home/kamimura/projects/tennis-lab/outputs/ball_refiner/train --output /home/kamimura/projects/tennis-lab/outputs/ball_refiner/evaluate/coordinates/20261005-v2 --tag 20261005-v2 --device cuda
