#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1014-3d-eventhead-regression-eventonly-s42-20261006-v1
# provider=codex session=01a10697-63da-75b2-ae84-f2980da51c23 issue=1014 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-refiner-3d-consolidation}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 09540efcf1cd46e1941eaf31f4062691eeee3c66 (branch codex/ball-refiner-3d-consolidation)"
git checkout 09540efcf1cd46e1941eaf31f4062691eeee3c66 2>/dev/null || echo "[repro] WARN: checkout 09540efcf1cd46e1941eaf31f4062691eeee3c66 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 .venv/bin/python -m src.tasks.ball_refiner_3d.scripts.train_coordinates run.output_dir=ball_refiner_3d/train/rope-regression-eventhead-eventonly/20261006-v1-s42
