"""Public strict configuration and runtime path contracts."""

from src.utils.configuration.contracts import (
    BoundaryAuthorityBinding,
    RuntimeBoundaryReference,
    TypedAdapterContract,
    discover_boundary_authorities,
    discover_configuration_contracts,
    discover_contract_declarations,
    inspect_typed_adapter,
)
from src.utils.configuration.errors import (
    ConfigurationError,
    ConfigurationTypeError,
    MissingConfigurationKeyError,
    PathContractError,
    SemanticConfigurationError,
    UnknownConfigurationKeyError,
)
from src.utils.configuration.inventory import (
    DEFAULT_AUDIT_INVENTORY,
    AuditInventory,
    AuditRule,
    BoundaryKind,
    RuntimeBoundary,
)
from src.utils.configuration.operations import (
    BUILD_CUDA_OPS,
    CUDA_OPS_BUILD_TARGET,
    DINO_OPS_BUILD_CONFIG,
    FORCE_TIME_LOCAL_REFERENCE,
    USE_TIME_LOCAL_CUDA,
    DinoOpsBuildConfig,
    OperationEnvironmentConfig,
    operation_environment,
)
from src.utils.configuration.paths import (
    BoundaryPathField,
    NonHydraPathBoundary,
    PathDirection,
    PathKind,
    PathResolver,
    PathRole,
    ResolvedBoundaryPath,
    ResolvedBoundaryPaths,
    RuntimePathRoots,
)
from src.utils.configuration.schema import (
    ConfigField,
    ConfigFieldContract,
    ConfigurationAbsencePolicy,
    ConfigurationDefaultPolicy,
    ConfigurationPrecedence,
    SemanticCheck,
    StrictConfigSchema,
    inspect_schema,
    mutually_exclusive,
)

__all__ = [
    "AuditInventory",
    "AuditRule",
    "BoundaryKind",
    "BoundaryAuthorityBinding",
    "BoundaryPathField",
    "BUILD_CUDA_OPS",
    "CUDA_OPS_BUILD_TARGET",
    "DEFAULT_AUDIT_INVENTORY",
    "ConfigField",
    "ConfigFieldContract",
    "ConfigurationAbsencePolicy",
    "DINO_OPS_BUILD_CONFIG",
    "DinoOpsBuildConfig",
    "ConfigurationDefaultPolicy",
    "ConfigurationError",
    "ConfigurationPrecedence",
    "ConfigurationTypeError",
    "FORCE_TIME_LOCAL_REFERENCE",
    "MissingConfigurationKeyError",
    "PathContractError",
    "PathDirection",
    "PathKind",
    "NonHydraPathBoundary",
    "OperationEnvironmentConfig",
    "PathResolver",
    "PathRole",
    "RuntimeBoundary",
    "RuntimeBoundaryReference",
    "ResolvedBoundaryPath",
    "ResolvedBoundaryPaths",
    "RuntimePathRoots",
    "SemanticCheck",
    "SemanticConfigurationError",
    "StrictConfigSchema",
    "TypedAdapterContract",
    "UnknownConfigurationKeyError",
    "USE_TIME_LOCAL_CUDA",
    "discover_configuration_contracts",
    "discover_boundary_authorities",
    "discover_contract_declarations",
    "inspect_schema",
    "inspect_typed_adapter",
    "mutually_exclusive",
    "operation_environment",
]
