#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: mono3d_blcs_bcast_v4_physics
# provider=claude session=dd9d56e0-5f2d-4d9d-a8c7-c80704a806b3 issue=593
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: be5e653b79b7a090f095f457c4986239637951c4 (branch feat/issue-593-physics-prior)"
git checkout be5e653b79b7a090f095f457c4986239637951c4 2>/dev/null || echo "[repro] WARN: checkout be5e653b79b7a090f095f457c4986239637951c4 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.blcs.scripts.train --config-name train_chunked data.scene_dir=data/blcs_broadcast data.chunk.chunks_dir=data/blcs_broadcast/chunks data.num_views_range=[1,1] data.camera_mode=random data.num_court_kp=14 data.num_workers=2 data.chunk.generation_workers=8 data.chunk.epochs_per_chunk=20 camera=broadcast training.position_axis_weights=[1.0,4.0,1.0] training.smoothness_loss_weight=1.0 training.gravity_loss_weight=0.5 training.trainer.max_epochs=200 training.trainer.check_val_every_n_epoch=5 training.qualitative_logging.enabled=false run.gpus=1
