#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: court-align-b00-s200-bilinear-t025-v2
# provider=codex session=01a05a02-ad55-76c0-9fcb-f250929e59a7 issue= resource=half logical_slot=1
set -uo pipefail
export TENNIS_GPU_RESOURCE=half
export TENNIS_GPU_SLOT=1
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/court-alignment-kp14}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: a3861691b1954779fd3dc2ab754cc99313018994 (branch feat/court-alignment-kp14-pipeline)"
git checkout a3861691b1954779fd3dc2ab754cc99313018994 2>/dev/null || echo "[repro] WARN: checkout a3861691b1954779fd3dc2ab754cc99313018994 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
HYDRA_FULL_ERROR=1 /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.court_alignment.scripts.evaluate_real_heatmap paths.data_root=/home/kamimura/projects/tennis-lab/.tmp/b00-alignment-eval paths.checkpoint_root=/home/kamimura/projects/tennis-lab/.claude/worktrees/court-alignment-kp14/outputs paths.output_root=/home/kamimura/projects/tennis-lab/.claude/worktrees/court-alignment-kp14/outputs real_evaluation.archive_path=synthetic_data_generation/scenes/B00/alignment/line-heatmaps/heatmaps.npz real_evaluation.manifest_path=synthetic_data_generation/scenes/B00/alignment/line-heatmaps/manifest.json real_evaluation.alignment_path=synthetic_data_generation/scenes/B00/alignment/alignment.json real_evaluation.device=cuda real_evaluation.checkpoint_path=court_alignment/ablation_sigma_200/logs/version_0/checkpoints/court-alignment-epoch\\=047.ckpt real_evaluation.preprocess.method=bilinear decoder.threshold=0.25 real_evaluation.preprocess.content_fraction=1.0 real_evaluation.output_dir=court_alignment/real_heatmap/b00_s200_bilinear_t025_v2
