#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i545_s5_h2_resume
# provider=codex session=019eed5b-bfed-7080-95ca-a09921dece32 issue=545
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/wt/i545-prune}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 674818c567169bd3bee4bab17dd417a7308fdcc6 (branch feat/training-queue-auto-prune-ckpt)"
git checkout 674818c567169bd3bee4bab17dd417a7308fdcc6 2>/dev/null || echo "[repro] WARN: checkout 674818c567169bd3bee4bab17dd417a7308fdcc6 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split model.num_layers=2 model.num_task_layers=5 data=chunked_multiview_sequence_bs8 data.batch_size=8 data.seq_len_range=[64,256] training.trainer.accumulate_grad_batches=1 loss=canonical_rot training.trainer.max_epochs=200 training.early_stopping.enabled=false run.gpus=1 run.resume=/home/kamimura/projects/wt/i545-prune/outputs/plcs/plcs_multiview_axial_split/logs/version_0/checkpoints/last.ckpt
