#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i931-default-meiji-clip000-20260927
# provider=claude session=abf284fe-984d-4b6c-afec-7375982b0bb0 issue=931 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i931-4-imports}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4fdc4d42dd32486344ae5438f9e0517a05f173ec (branch campaign930/i931-4-imports)"
git checkout 4fdc4d42dd32486344ae5438f9e0517a05f173ec 2>/dev/null || echo "[repro] WARN: checkout 4fdc4d42dd32486344ae5438f9e0517a05f173ec failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# #931: the original command built the DINO extension into the report directory under outputs/;
# the repro.sh builds it into a temporary directory with the same script instead.
DINO_EXTENSION="$(mktemp -d)/dino_extension"
bash tests/benchmarks/build_dino_extension.sh "${TENNIS_ASSET_ROOT:-/home/kamimura/projects/tennis-lab}" "$DINO_EXTENSION" || { echo "[repro] DINO extension build failed" >&2; exit 1; }
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=4 PYTHONPATH=.:$DINO_EXTENSION/lib .venv/bin/python tests/benchmarks/component_pipeline.py --repo /home/kamimura/projects/tennis-lab --clip /home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_000 --report /home/kamimura/projects/tennis-lab/outputs/tennis_scene/evaluate/i931-default-meiji-clip000-20260927 --device cuda
