"""Automatic court-to-scene alignment inputs and geometry."""

from src.synthetic_data_generation.alignment.acceptance_decision import (
    ALIGNMENT_ACCEPTANCE_DECISION_SCHEMA,
    USER_OVERRIDE_DECISION,
    AlignmentAcceptanceDecision,
    load_alignment_acceptance_decision,
    publish_alignment_acceptance_decision,
    verify_machine_evidence,
)
from src.synthetic_data_generation.alignment.court_line_acceptance import (
    ALIGNMENT_CALIBRATION_SCHEMA,
    ALIGNMENT_VALIDATION_SCHEMA,
    CourtLineEvaluationSettings,
    camera_heights_in_court,
    court_line_distances,
    evaluate_projected_court_lines,
    load_alignment_artifact,
    point_cloud_court_support,
    publish_alignment_artifact,
    transform_stability,
)
from src.synthetic_data_generation.alignment.court_template_fit import (
    COURT_GEOMETRY_SCHEMA,
    CourtFitCandidate,
    CourtTemplateFitSettings,
    court_line_segments,
    fit_court_instances,
    load_court_geometry_artifact,
    publish_court_geometry_artifact,
    sample_court_line_template,
    scene_from_court_matrix,
)
from src.synthetic_data_generation.alignment.fit_view_detection import (
    FIT_VIEW_COURT_DETECTIONS_SCHEMA,
    CourtKeypointPrediction,
    FitViewDetectionSettings,
    infer_fit_view_court_detections,
    load_fit_view_court_detections,
    publish_fit_view_court_detections,
)
from src.synthetic_data_generation.alignment.ground_line_map import (
    GROUND_LINE_MAP_SCHEMA,
    GroundLineAccumulator,
    GroundLineMapSettings,
    ProjectedLinePixels,
    expanded_plane_bounds,
    load_ground_line_map_artifact,
    project_line_pixels_to_ground,
    publish_ground_line_map_artifact,
)
from src.synthetic_data_generation.alignment.ground_plane import (
    GroundPlaneEstimate,
    GroundPlaneFitSettings,
    estimate_ground_plane,
)

__all__ = [
    "ALIGNMENT_ACCEPTANCE_DECISION_SCHEMA",
    "ALIGNMENT_CALIBRATION_SCHEMA",
    "ALIGNMENT_VALIDATION_SCHEMA",
    "COURT_GEOMETRY_SCHEMA",
    "FIT_VIEW_COURT_DETECTIONS_SCHEMA",
    "AlignmentAcceptanceDecision",
    "CourtFitCandidate",
    "CourtKeypointPrediction",
    "CourtLineEvaluationSettings",
    "CourtTemplateFitSettings",
    "FitViewDetectionSettings",
    "GROUND_LINE_MAP_SCHEMA",
    "GroundLineAccumulator",
    "GroundLineMapSettings",
    "GroundPlaneEstimate",
    "GroundPlaneFitSettings",
    "ProjectedLinePixels",
    "USER_OVERRIDE_DECISION",
    "camera_heights_in_court",
    "court_line_distances",
    "court_line_segments",
    "estimate_ground_plane",
    "evaluate_projected_court_lines",
    "expanded_plane_bounds",
    "fit_court_instances",
    "infer_fit_view_court_detections",
    "load_alignment_acceptance_decision",
    "load_fit_view_court_detections",
    "load_court_geometry_artifact",
    "load_alignment_artifact",
    "load_ground_line_map_artifact",
    "project_line_pixels_to_ground",
    "point_cloud_court_support",
    "publish_alignment_acceptance_decision",
    "publish_alignment_artifact",
    "publish_fit_view_court_detections",
    "publish_court_geometry_artifact",
    "publish_ground_line_map_artifact",
    "sample_court_line_template",
    "scene_from_court_matrix",
    "transform_stability",
    "verify_machine_evidence",
]
