defaults:
  - model: multitask_transformer
  - data: blcs_rally
  - training: default
  - metrics: default
  - run: train
  - _self_

hydra:
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
