#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: mono3d_plcs_ft_s15_safe
# provider=claude session=22fa49a8-b654-4af8-99ce-6f29e7453a00 issue=593
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: d36b7dc50522453fa13778e7d31756a733fa0403 (branch feat/issue-593-physics-prior)"
git checkout d36b7dc50522453fa13778e7d31756a733fa0403 2>/dev/null || echo "[repro] WARN: checkout d36b7dc50522453fa13778e7d31756a733fa0403 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split model.num_layers=0 model.num_task_layers=6 data=chunked_singleview_sequence data.scene_dir=data/plcs_broadcast data.chunk.chunks_dir=data/plcs_broadcast/chunks data.batch_size=6 data.seq_len_range=[64,192] data.num_court_kp=14 data.num_workers=2 data.chunk.generation_workers=3 data.chunk.epochs_per_chunk=30 loss=canonical_rot loss.position_weight=8.0 loss.position_smoothness_weight=1.5 loss.canonical_pose_weight=0.0 loss.joint_angle_weight=0.0 loss.torsion_angle_weight=0.0 loss.torso_twist_weight=0.0 loss.bone_length_weight=0.0 training.learning_rate=3e-5 training.trainer.max_epochs=50 training.trainer.check_val_every_n_epoch=5 training.qualitative_logging.enabled=false training.early_stopping.enabled=false camera=broadcast run.gpus=1 run.init_weights=ckpt/plcs/last.ckpt
