#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1034-vidmap-cuda-probe-a0
# provider=codex session=01a1106e-187c-7163-be4e-9f1673767ad9 issue=1034 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 2eeea0faecac81da5808f34e68dc792ac94c2b8c (branch research/sfm-night-20261006)"
git checkout 2eeea0faecac81da5808f34e68dc792ac94c2b8c 2>/dev/null || echo "[repro] WARN: checkout 2eeea0faecac81da5808f34e68dc792ac94c2b8c failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.venv/bin/python -m experiments.sfm_comparison.run_command --campaign /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006 --run-id vidmap-cuda-probe-a0 --stage sanity --seconds 180 --metrics-source /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006/environment/cuda-probe.json --required-path /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006/environment/cuda-probe.json -- /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.cache/runtimes/vidmap-native/bin/python -m experiments.sfm_comparison.probe_runtime --output /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006/environment/cuda-probe.json
