#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: mono3d_plcs_bcast
# provider=claude session=dd9d56e0-5f2d-4d9d-a8c7-c80704a806b3 issue=
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4a416b2a07f67518448e669ba5e985668373cdf4 (branch feat/mono3d-broadcast-pipeline)"
git checkout 4a416b2a07f67518448e669ba5e985668373cdf4 2>/dev/null || echo "[repro] WARN: checkout 4a416b2a07f67518448e669ba5e985668373cdf4 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split model.num_layers=0 model.num_task_layers=6 data=chunked_singleview_sequence data.scene_dir=data/plcs_broadcast data.chunk.chunks_dir=data/plcs_broadcast/chunks data.batch_size=8 data.seq_len_range=[64,256] data.num_court_kp=14 data.num_workers=2 loss=canonical_rot loss.position_weight=8.0 loss.canonical_pose_weight=0.0 loss.joint_angle_weight=0.0 loss.torsion_angle_weight=0.0 loss.torso_twist_weight=0.0 loss.bone_length_weight=0.0 training.trainer.accumulate_grad_batches=1 training.trainer.max_epochs=200 training.early_stopping.enabled=false camera=broadcast run.gpus=1
