#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i934-holdout-ft-e13-vs-mixed-e0-r7-20260928
# provider=codex session=01a0e707-b9f5-7221-b920-50119a3004e4 issue=934 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-4-mixed-ft}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 78ce7d9bd96104e424cd4983e7427a2b81912f9f (branch campaign930/i934-4-mixed-ft)"
git checkout 78ce7d9bd96104e424cd4983e7427a2b81912f9f 2>/dev/null || echo "[repro] WARN: checkout 78ce7d9bd96104e424cd4983e7427a2b81912f9f failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-4-mixed-ft OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-4-mixed-ft/.venv/bin/python /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-4-mixed-ft/tests/benchmarks/ball_detection_holdout.py --phase infer --device cuda --store /home/kamimura/projects/tennis-lab/data/ball_detection/ball-mix-v1 --poses /home/kamimura/projects/tennis-lab/outputs/player_association/evaluate/meiji_clips/i933-observe-v1-20260927/stores --baseline /home/kamimura/projects/tennis-lab/ckpt/ball_detection/run-i618-convnext-v2-ft-epoch13.ckpt --treatment /home/kamimura/projects/tennis-lab/outputs/ball_detection/train/i934_mixed_ft/s42-r6-20260928/logs/version_0/checkpoints/ball-detection-epoch=00.ckpt --report /home/kamimura/projects/tennis-lab/outputs/ball_detection/evaluate/i934-holdout-ft-e13-vs-mixed-e0-r7-20260928 --video video_001 --expected-frames 36006 --expected-clips 63 --batch-size 4 --stride 4 --score-threshold 0.5 --distance-px 20 --near-wrist-px 100 --wrist-confidence 0.5
