#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: issue880_b00_last_v2
# provider=codex session=01a09588-636e-7560-b584-5451ff831df9 issue=880 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-880-semantic-alignment}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 6679ae4307b1d7ddd1c81d753a0effe7e02ffacd (branch feat/issue-880-semantic-alignment)"
git checkout 6679ae4307b1d7ddd1c81d753a0effe7e02ffacd 2>/dev/null || echo "[repro] WARN: checkout 6679ae4307b1d7ddd1c81d753a0effe7e02ffacd failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-880-semantic-alignment /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.synthetic_data_generation.scripts.compare_semantic_alignment profile=b00 roots.project_root=/home/kamimura/projects/tennis-lab comparison.checkpoint=court_detection/mixed-source/semantic-line-frozen-b00-b03-b8-e20-s42/logs/version_0/checkpoints/last.ckpt comparison.output=issue880/B00-last-v1
