#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i936-combined512-physics10-r16-s936-20261001
# provider=codex session=01a0f3ed-4151-7303-886f-52e91fdac10e issue=936 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 50098f0e6923b11ce0f856ef473e0d8bc4d4c8a0 (branch campaign930/i936-2-synthetic-diffusion)"
git checkout 50098f0e6923b11ce0f856ef473e0d8bc4d4c8a0 2>/dev/null || echo "[repro] WARN: checkout 50098f0e6923b11ce0f856ef473e0d8bc4d4c8a0 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --signal=TERM --kill-after=15s 5340s env CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation/.venv/bin/python -u -m src.tasks.ball_refiner.scripts.experiment_dev_3d --plan /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation/knowledge/runs/run-i936-combined512-physics10-r16-s936/plan.json --device cuda
