#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: court_mixed_pose_lora_b8_e20_s42
# provider=codex session=01a06e82-4115-7af1-b52d-c011c61cfa56 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 379b5a66dd5ce756a29c5dd3f398b448b9526694 (branch main)"
git checkout 379b5a66dd5ce756a29c5dd3f398b448b9526694 2>/dev/null || echo "[repro] WARN: checkout 379b5a66dd5ce756a29c5dd3f398b448b9526694 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.court_detection.scripts.train_mixed training=lora data.batch_size=8 mixed.train_batch_counts.synthetic_court=4 mixed.train_batch_counts.tennis_court_detector=4 run.test_after_fit=true run.output_dir=court_detection/mixed-source/dense-pose-lora-b8-e20-s42
