#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: blcs-axial-base-t128-v3-6-reprojection-e200-s42-20261006
# provider=codex session=01a10f9e-7f68-7623-9325-0a5534377076 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/blcs-axial-base-s42-20261006}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 1178e66a8873d57083366bfc4b9536eee494878a (branch HEAD)"
git checkout 1178e66a8873d57083366bfc4b9536eee494878a 2>/dev/null || echo "[repro] WARN: checkout 1178e66a8873d57083366bfc4b9536eee494878a failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env MPLBACKEND=Agg OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 OPENBLAS_NUM_THREADS=4 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -u -m src.tasks.blcs.scripts.train model=multiview_axial_base data=multiview_sequence training=default loss=reprojection paths.data_root=/home/kamimura/projects/tennis-lab/data paths.output_root=/home/kamimura/projects/tennis-lab/outputs paths.artifact_root=/home/kamimura/projects/tennis-lab/outputs paths.checkpoint_root=/home/kamimura/projects/tennis-lab/ckpt model.predict_velocity=false model.num_court_tokens=14 data.num_court_kp=14 'data.seq_len_range=[128,128]' 'data.num_views_range=[3,6]' data.camera_mode=random data.batch_size=2 data.num_workers=4 data.augmentation.enabled=true loss.position_weight=1.0 loss.reprojection_weight=0.1 loss.smoothness_weight=0.0 loss.gravity_weight=0.0 training.learning_rate=1e-4 training.weight_decay=0.01 training.warmup_steps=200 training.min_lr=1e-6 training.compile.enabled=false training.gan.enabled=false training.trainer.precision=bf16-mixed training.trainer.max_epochs=200 training.trainer.accumulate_grad_batches=8 training.trainer.check_val_every_n_epoch=5 training.trainer.enable_progress_bar=false training.trainer.log_every_n_steps=10 training.checkpoint.monitor=val/position_error_m training.checkpoint.mode=min training.checkpoint.save_top_k=1 training.checkpoint.save_last=true training.qualitative_logging.every_n_epochs=10 run.seed=42 run.resume=null run.init_weights=null run.test_after_fit=false run.output_dir=blcs/train/axial_base_t128_v3-6_reprojection_e200/s42-20261006-001
