#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i986-query-bf16-s42-u60000-nvjpeg-v2
# provider=codex session=01a0fb0c-97b5-7851-b805-25dae445a6a2 issue=986 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-nvjpeg-train-s42-u60000-v2}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: e75f81a4e3831af6f0ca175f71c0ccb90fd2b021 (branch HEAD)"
git checkout e75f81a4e3831af6f0ca175f71c0ccb90fd2b021 2>/dev/null || echo "[repro] WARN: checkout e75f81a4e3831af6f0ca175f71c0ccb90fd2b021 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 TORCHINDUCTOR_COMPILE_THREADS=2 TORCH_LOGS=graph_breaks,recompiles PYTHONUNBUFFERED=1 .venv/bin/python -m src.tasks.ball_detection.scripts.train_mdd_pose --manifest /home/kamimura/projects/tennis-lab/outputs/ball_detection/precompute/mdd_coordinates_36/20261008-fps124-v1/mdd_only_windows.json --model-config /home/kamimura/projects/tennis-lab/outputs/ball_detection/precompute/mdd_coordinates_36/20261008-fps124-v1/models/conv2d-query_only.yaml --output /home/kamimura/projects/tennis-lab/outputs/ball_detection/train/conv2d-query-only-bf16/s42-u60000-nvjpeg-v2 --device cuda --precision bf16 --compile-mode default --batch-size 1 --num-workers 8 --pin-memory --prefetch-factor 4 --cpu-threads 2 --jpeg-decoder nvjpeg --input-verification upfront --image-prefetch --epochs 10 --windows-per-epoch 6000 --learning-rate 0.0001 --seed 42 --mdd-a 0.2 --mdd-b 0.15 --selection-scope common --log-every 50
