#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-full-real-rgb-velocity-val-v1
# provider=codex session=01a0b71f-c516-75b2-ac58-0c92e8a4f098 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: c5b32165c27bba0319ff2328c19c73455ea67eda (branch codex/slcs-real-rgb)"
git checkout c5b32165c27bba0319ff2328c19c73455ea67eda 2>/dev/null || echo "[repro] WARN: checkout c5b32165c27bba0319ff2328c19c73455ea67eda failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env PYTHONUNBUFFERED=1 PYTHONFAULTHANDLER=1 CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python -m scripts.analysis.evaluate_slcs_run --output-root /home/kamimura/projects/tennis-lab/outputs --training-run slcs/train/real_rgb_velocity/s42-001 --output slcs/evaluate/real_rgb_velocity/s42-001 --domain-prefix video_=meiji --default-domain broadcast --device cuda --batch-size 4 --ball-train-mean --gap-no-rgb
