#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i964-detectors-val-meiji-r1-20260929
# provider=codex session=01a0eb46-5947-7a73-a409-92ae9b952dfd issue=964 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-1-player-detection}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 312f11ec8c7242bef3f3fbeae14ccc0f69d70129 (branch campaign930/i964-1-player-detection)"
git checkout 312f11ec8c7242bef3f3fbeae14ccc0f69d70129 2>/dev/null || echo "[repro] WARN: checkout 312f11ec8c7242bef3f3fbeae14ccc0f69d70129 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
bash /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-1-player-detection/tests/benchmarks/player_detection_comparison.sh /home/kamimura/projects/tennis-lab /home/kamimura/projects/tennis-lab/outputs/player_detection/evaluate/pipeline_switch/i964-detectors-r1-20260929
