#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i551_dinov3_rope_tracknet_t3_train
# provider=codex session=019f0329-2f83-7e22-83f8-10d706257993 issue=551
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: ed6eef1b4fbfa5431d1ce40f3a010e90115b09fb (branch main)"
git checkout ed6eef1b4fbfa5431d1ce40f3a010e90115b09fb 2>/dev/null || echo "[repro] WARN: checkout ed6eef1b4fbfa5431d1ce40f3a010e90115b09fb failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.ball_detection.scripts.train model=dinov3_rope data=rgb_sequence model.num_frames=3 run.output_dir=outputs/ball_detection/dinov3_rope_tracknet_t3 && .venv/bin/python -c "from pathlib import Path; import sys; root=Path(\"outputs/ball_detection/dinov3_rope_tracknet_t3\"); ckpts=sorted(root.glob(\"logs/version_*/checkpoints/last.ckpt\"), key=lambda p: p.stat().st_mtime); ckpts or sys.exit(f\"No last.ckpt found under {root}\"); ckpt=ckpts[-1]; target=root/\"latest\"/\"checkpoints\"/\"last.ckpt\"; target.parent.mkdir(parents=True, exist_ok=True); target.unlink() if target.exists() or target.is_symlink() else None; target.symlink_to(ckpt.resolve()); print(f\"latest checkpoint -> {ckpt}\")"
