#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-pipeline-ft-e13-r7-20260928
# provider=codex session=01a0e806-1b81-7340-8062-cdc418a1fa27 issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-7-pipeline}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 5f839cc417e960236d62e9f1d43f1bce29ee30e1 (branch campaign930/i935-7-pipeline)"
git checkout 5f839cc417e960236d62e9f1d43f1bce29ee30e1 2>/dev/null || echo "[repro] WARN: checkout 5f839cc417e960236d62e9f1d43f1bce29ee30e1 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --foreground --signal=TERM --kill-after=15s 900 bash -c 'set -euo pipefail
export OMP_NUM_THREADS=2 MKL_NUM_THREADS=2
mkdir -p '\''/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/detector_only_pipeline'\''
mkdir '\''/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/detector_only_pipeline/i935-ft-e13-pipeline-r7-20260928'\''
'\''/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-7-pipeline/.venv/bin/python'\'' '\''-m'\'' '\''src.tasks.ball_refiner.scripts.run_pipeline'\'' '\''--video'\'' '\''/home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_010/media/cam0.mp4'\'' '\''--camera-id'\'' '\''cam0'\'' '\''--bundle'\'' '\''/home/kamimura/projects/tennis-lab/ckpt/ball_refiner/i935-detector-only-ft-e13-r7-20260928'\'' '\''--detector-checkpoint'\'' '\''/home/kamimura/projects/tennis-lab/ckpt/ball_detection/run-i618-convnext-v2-ft-epoch13.ckpt'\'' '\''--store'\'' '\''/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/detector_only_pipeline/i935-ft-e13-pipeline-r7-20260928/store'\'' '\''--device'\'' '\''cuda'\'' '\''--detector-batch-size'\'' '\''4'\'' '\''--refiner-batch-size'\'' '\''32'\'' --source execute > '\''/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/detector_only_pipeline/i935-ft-e13-pipeline-r7-20260928/execute.json'\''
'\''/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-7-pipeline/.venv/bin/python'\'' '\''-m'\'' '\''src.tasks.ball_refiner.scripts.run_pipeline'\'' '\''--video'\'' '\''/home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_010/media/cam0.mp4'\'' '\''--camera-id'\'' '\''cam0'\'' '\''--bundle'\'' '\''/home/kamimura/projects/tennis-lab/ckpt/ball_refiner/i935-detector-only-ft-e13-r7-20260928'\'' '\''--detector-checkpoint'\'' '\''/home/kamimura/projects/tennis-lab/ckpt/ball_detection/run-i618-convnext-v2-ft-epoch13.ckpt'\'' '\''--store'\'' '\''/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/detector_only_pipeline/i935-ft-e13-pipeline-r7-20260928/store'\'' '\''--device'\'' '\''cuda'\'' '\''--detector-batch-size'\'' '\''4'\'' '\''--refiner-batch-size'\'' '\''32'\'' --source load > '\''/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/detector_only_pipeline/i935-ft-e13-pipeline-r7-20260928/load.json'\''
'\''/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-7-pipeline/.venv/bin/python'\'' - <<'\''VERIFY'\''

import json
from dataclasses import fields
from pathlib import Path
import numpy as np
from src.tennis_scene.pipeline.storage.clip_store import ClipStore
from src.tennis_scene.pipeline.storage.codec import ArtifactCodec
from src.tennis_scene.pipeline.components.ball_refiner import BallRefiner2DOutput
from src.tennis_scene.pipeline.artifacts import json_value
from src.utils.checksum import dual_sha256
root=Path("/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/detector_only_pipeline/i935-ft-e13-pipeline-r7-20260928")
a=json.loads((root/'\''execute.json'\'').read_text().splitlines()[-1])
b=json.loads((root/'\''load.json'\'').read_text().splitlines()[-1])
assert a['\''status'\'']==b['\''status'\'']=='\''complete'\''
assert set(a['\''components'\''].values())=={'\''executed'\''}
assert set(b['\''components'\''].values())=={'\''loaded'\''}
assert a['\''references'\'']==b['\''references'\''] and a['\''source'\'']==b['\''source'\'']
store=ClipStore(root/'\''store'\'',a['\''source'\''],memory_entries=0)
ref=store.active('\''ball_refiner_2d/cam0'\'')
assert ref is not None and ref.schema=='\''ball_distribution_2d'\'' and ref.version==1
v=store.load(ref,ArtifactCodec(BallRefiner2DOutput))
assert v.camera_id=='\''cam0'\'' and v.source_size_wh==(1920,1080)
assert v.prediction.distribution.means.shape==(1,270,4,2)
assert v.time_base=='\''1/2997003'\'' and v.calibration=='\''uncalibrated'\''
np.testing.assert_array_equal(v.pts,np.arange(270,dtype=np.int64)*50000)
np.testing.assert_array_equal(v.frame_indices,np.arange(270,dtype=np.int64))
assert a['\''source'\'']['\''videos'\''][0]['\''sha256'\'']=='\''0ac292acd91aa8f0fda4082c0ec3c85c3240b958b89f65fc5c3cafb170f8f26b'\''
archive=root/'\''refiner_prediction.npz'\''
with archive.open('\''xb'\'') as stream:
    np.savez_compressed(stream,**{f.name:getattr(v.prediction.distribution,f.name)[0].numpy() for f in fields(v.prediction.distribution)},
        frame_indices=v.frame_indices,pts=v.pts,timestamps_seconds=v.timestamps_seconds,
        refiner_window_start=v.prediction.window_start,refiner_time_index=v.prediction.time_index,
        detector_window_start=v.detector_window_start,detector_time_index=v.detector_time_index,
        source_size_wh=np.asarray(v.source_size_wh,dtype=np.int64))
report={'\''status'\'':'\''complete'\'','\''artifact'\'':json_value(ref),'\''source'\'':a['\''source'\''],
        '\''frame_count'\'':270,'\''components'\'':4,'\''calibration'\'':v.calibration,
        '\''refiner_window_length'\'':v.prediction.window_length,'\''detector_window_length'\'':v.detector_window_length,
        '\''time_base'\'':v.time_base,'\''fresh_process_loaded_same_artifacts'\'':True,
        '\''all_array_checksums_valid'\'':True,'\''predictions_sha256'\'':dual_sha256(archive),
        '\''bundle_manifest_sha256'\'':dual_sha256(Path("/home/kamimura/projects/tennis-lab/ckpt/ball_refiner/i935-detector-only-ft-e13-r7-20260928/manifest.json")),
        '\''execute_seconds'\'':a['\''seconds'\''],'\''load_seconds'\'':b['\''seconds'\'']}
with (root/'\''verification.json'\'').open('\''x'\'') as stream:
    json.dump(report,stream,indent=2)
print(json.dumps(report),flush=True)

VERIFY'
