task: seg
image_source: court/images
checkpoint: court_detection/seg/logs/version_0/checkpoints/court-detection-epoch=19.ckpt
save: court_detection/seg.gif
fps: 6
max_frames: 24
info: false

gif:
  loop: 0
