defaults:
  - model: tracknetv3
  - data: labeled_tracknetv3
  - training: default
  - loss: default
  - run: train
  - _self_

hydra:
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false

training:
  xy_weight: 0.0
  vis_weight: 0.0
  heatmap_weight: 1.0
  heatmap_loss_type: tracknet_wbce
