#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: court-align-kp14-pilot-sigma-1-r1
# provider=codex session=01a05a02-ad55-76c0-9fcb-f250929e59a7 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/court-alignment-kp14}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 456a6b19e6ffbf73b9645b76f860dde14ae37906 (branch feat/court-alignment-kp14-pipeline)"
git checkout 456a6b19e6ffbf73b9645b76f860dde14ae37906 2>/dev/null || echo "[repro] WARN: checkout 456a6b19e6ffbf73b9645b76f860dde14ae37906 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.court_alignment.scripts.train data.train_samples=128 data.val_samples=32 data.test_samples=32 data.batch_size=4 data.num_workers=4 training.steps_per_epoch=32 training.trainer.max_epochs=20 training.trainer.log_every_n_steps=8 run.output_dir=court_alignment/pilot_sigma_1_r1
