#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i545_nocanon_rs_s0_h12
# provider=codex session=019ef7e7-03a8-7e53-9c92-21cdcb326a79 issue=560
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: ed6eef1b4fbfa5431d1ce40f3a010e90115b09fb (branch main)"
git checkout ed6eef1b4fbfa5431d1ce40f3a010e90115b09fb 2>/dev/null || echo "[repro] WARN: checkout ed6eef1b4fbfa5431d1ce40f3a010e90115b09fb failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_base model.num_layers=12 model.predict_canonical_pose=false data=chunked_multiview_sequence_bs8 data.batch_size=8 training.trainer.accumulate_grad_batches=1 data.seq_len_range=[64,256] loss=no_canonical loss.rotation_weight=0.5 +loss.angle_weight=1.0 training.trainer.max_epochs=200 training.early_stopping.enabled=false run.gpus=1
