#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-known-memory-cpu-audit-v1
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 892b02c481e368d3357c1d77a446ea368126f4a0 (branch codex/slcs-real-rgb)"
git checkout 892b02c481e368d3357c1d77a446ea368126f4a0 2>/dev/null || echo "[repro] WARN: checkout 892b02c481e368d3357c1d77a446ea368126f4a0 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --kill-after=5s 300s env PYTHONPATH=. OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 .venv/bin/python -B knowledge/runs/run-slcs-known-memory-cpu-audit-v1/probe.py --output-dir outputs/tennis_scene/analyze/known_memory_cpu_audit/s42-001
