#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: appearance-b00-clay-flare-v001-7000
# provider=codex session=01a0bd70-e78d-7732-ba19-1a4595e91a32 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/b00-clay-variant}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 2d78cc47c8e1fca872a87339d2d1511f34df8a3a (branch codex/b00-clay-variant)"
# #931: the run used 893d0ca4 plus untracked source files (src/synthetic_data_generation/appearance/, scripts/run_appearance_variant.py), which the bundle did not capture.
# They were first committed in 2d78cc47; the repro checks out that commit (the patch may not apply).
git checkout 2d78cc47c8e1fca872a87339d2d1511f34df8a3a 2>/dev/null || echo "[repro] WARN: checkout 2d78cc47c8e1fca872a87339d2d1511f34df8a3a failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
/home/kamimura/projects/tennis-lab/.claude/worktrees/b00-clay-variant/.venv/bin/python -m src.synthetic_data_generation.scripts.run_appearance_variant action=execute_training variant.output_root=/home/kamimura/projects/tennis-lab/data/synthetic_data_generation/scene_variants/B00/clay-flare-v001
