"""3DGS-native BLCS asset selection, placement, and label contracts."""

from src.synthetic_data_generation.blcs.asset_ingestion import (
    BALL_ASSET_CONVERSION_REPORT_SCHEMA,
    BALL_ASSET_INGESTION_SCHEMA,
    BALL_ASSET_PUBLICATION_SCHEMA,
    FROZEN_TARGET_NHT_FIT,
    IDENTITY_SHARED_NHT,
    INDEPENDENT_NHT_SOURCE,
    SHARED_NHT_SOURCE,
    VANILLA_3DGS_SOURCE,
    BallAssetIngestionSpec,
    publish_ball_asset_registry_from_sources,
)
from src.synthetic_data_generation.blcs.assets import (
    BALL_ASSET_REGISTRY_SCHEMA,
    BallAssetEntry,
    BallAssetRegistry,
    BallAssetSelection,
    load_ball_asset_registry,
    select_ball_asset,
    verify_local_ball_asset_registry,
    verify_local_gaussian_asset,
    write_ball_asset_registry,
)
from src.synthetic_data_generation.blcs.calibration import (
    BALL_CALIBRATION_BUNDLE_SCHEMA,
    BALL_CALIBRATION_CAPTURE_SCHEMA,
    BALL_CALIBRATION_IMPORT_SCHEMA,
    BallCalibrationBundle,
    BallCalibrationCapture,
    BallCalibrationCaptureView,
    BallCalibrationImport,
    import_ball_calibration_capture,
    load_ball_calibration_bundle,
    load_ball_calibration_capture,
    load_ball_calibration_import,
    write_ball_calibration_bundle,
)
from src.synthetic_data_generation.blcs.planner import (
    BLCS_GAUSSIAN_PLAN_SCHEMA,
    BLCSGaussianScenePlan,
    build_blcs_gaussian_plan_from_scene,
    load_blcs_gaussian_plan,
    verify_blcs_gaussian_plan_output,
    write_blcs_gaussian_plan,
)
from src.synthetic_data_generation.blcs.prototype import (
    PrototypeBallGeometry,
    build_prototype_ball_geometry,
)

__all__ = [
    "BALL_ASSET_REGISTRY_SCHEMA",
    "BALL_ASSET_CONVERSION_REPORT_SCHEMA",
    "BALL_ASSET_INGESTION_SCHEMA",
    "BALL_ASSET_PUBLICATION_SCHEMA",
    "BALL_CALIBRATION_BUNDLE_SCHEMA",
    "BALL_CALIBRATION_CAPTURE_SCHEMA",
    "BALL_CALIBRATION_IMPORT_SCHEMA",
    "BLCS_GAUSSIAN_PLAN_SCHEMA",
    "BLCSGaussianScenePlan",
    "BallAssetEntry",
    "BallAssetRegistry",
    "BallAssetSelection",
    "BallAssetIngestionSpec",
    "BallCalibrationBundle",
    "BallCalibrationCapture",
    "BallCalibrationCaptureView",
    "BallCalibrationImport",
    "PrototypeBallGeometry",
    "FROZEN_TARGET_NHT_FIT",
    "IDENTITY_SHARED_NHT",
    "INDEPENDENT_NHT_SOURCE",
    "SHARED_NHT_SOURCE",
    "VANILLA_3DGS_SOURCE",
    "build_blcs_gaussian_plan_from_scene",
    "build_prototype_ball_geometry",
    "import_ball_calibration_capture",
    "load_ball_asset_registry",
    "load_ball_calibration_bundle",
    "load_ball_calibration_capture",
    "load_ball_calibration_import",
    "load_blcs_gaussian_plan",
    "publish_ball_asset_registry_from_sources",
    "select_ball_asset",
    "verify_blcs_gaussian_plan_output",
    "verify_local_ball_asset_registry",
    "verify_local_gaussian_asset",
    "write_ball_asset_registry",
    "write_ball_calibration_bundle",
    "write_blcs_gaussian_plan",
]
