#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: tennis-scene-cleanup-visible-court-tracking-20260922T2207Z
# provider=codex session=01a0c8c3-d190-7c51-b671-ded223340a2f issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/tennis-scene-responsibility-cleanup}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: fa8798a4c19f7efc6b123f4819130d57fe14b565 (branch codex/tennis-scene-responsibility-cleanup)"
git checkout fa8798a4c19f7efc6b123f4819130d57fe14b565 2>/dev/null || echo "[repro] WARN: checkout fa8798a4c19f7efc6b123f4819130d57fe14b565 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# #931: the original command read these files from outputs/; they are saved in this bundle.
# #931: the original PYTHONPATH used a DINO extension built outside the repository; it is rebuilt from
# this checkout by the bundle's build_dino_extension.sh (copy of tests/benchmarks/build_dino_extension.sh).
DINO_EXTENSION="$(mktemp -d)/dino_extension"
bash "$SCRIPT_DIR/build_dino_extension.sh" "${TENNIS_ASSET_ROOT:-/home/kamimura/projects/tennis-lab}" "$DINO_EXTENSION" || { echo "[repro] DINO extension build failed" >&2; exit 1; }
# --- original training command ---
env PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/tennis-scene-responsibility-cleanup:$DINO_EXTENSION/lib OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 /home/kamimura/projects/tennis-lab/.claude/worktrees/tennis-scene-responsibility-cleanup/.venv/bin/python "$SCRIPT_DIR/tracker_court_filter_visible_probe.py"
