#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-rgb-pilot-gpu-smoke-v2
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4348077d8f7a0b35ab58350232cf4ccb607990f1 (branch codex/slcs-real-rgb)"
git checkout 4348077d8f7a0b35ab58350232cf4ccb607990f1 2>/dev/null || echo "[repro] WARN: checkout 4348077d8f7a0b35ab58350232cf4ccb607990f1 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONFAULTHANDLER=1 CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=3 MKL_NUM_THREADS=3 .venv/bin/python -m src.tasks.slcs.scripts.train --config-name train_real_rgb_pilot training.trainer.max_epochs=1 training.warmup_steps=0 run.output_dir=slcs/train/real_rgb_pilot_gpu_smoke/s42-002
