#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: blcs-residual-v2-gpu-smoke-r2
# provider=codex session=01a0bf91-5494-74c0-8793-3424866618ed issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-triangulation-residual}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4671f9bad0873a23054a3311009b9ecf4a6bbc88 (branch codex/plcs-triangulation-residual)"
git checkout 4671f9bad0873a23054a3311009b9ecf4a6bbc88 2>/dev/null || echo "[repro] WARN: checkout 4671f9bad0873a23054a3311009b9ecf4a6bbc88 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=2 .venv/bin/python -c 'import runpy,torch; runpy.run_module("src.tasks.blcs.scripts.train_triangulation_residual",run_name="__main__"); print("CUDA_PEAK",torch.cuda.max_memory_allocated(),torch.cuda.max_memory_reserved(),flush=True)' --config-name train_triangulation_residual_v2 paths.data_root=/home/kamimura/projects/tennis-lab/data paths.output_root=/home/kamimura/projects/tennis-lab/outputs run.output_dir=blcs/triangulation_residual_v2_gpu_smoke_20260921 run.seed=42 data.train_limit=64 data.val_limit=32 data.test_limit=32 data.num_workers=2 data.min_views=6 data.max_views=6 v2.evaluation_views=6 training.trainer.max_epochs=1 training.trainer.enable_progress_bar=false training.warmup_epochs=0
