defaults:
  - paths: default
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_
scene: ???
court: ???
output: ${tennis_output:tennis_scene,evaluate,refinement,${tennis_run_id:}}
recipe: build_slcs_dataset
overrides: []
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
