defaults:
  - paths: default
  - _self_
source_directory: ???
clip_names: null
export:
  fps: null
  width: null
  height: null
  crf: 17
  overwrite: false
hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},clip_studio/hydra,${now:%Y-%m-%d_%H-%M-%S}}
  output_subdir: null
  job:
    chdir: false
