defaults:
- paths: default
- _self_
dataset_directory: ???
clip_ids: null
overwrite: false
continue_on_error: true
pipeline_overrides: []
hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},${tennis_output:tennis_scene,generate,generate_dataset,${tennis_run_id:}},hydra}
  output_subdir: null
  job:
    chdir: false
