#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: mono3d_blcs_gan_ft_v3
# provider=claude session=59c50b41-eb5d-40e1-aecf-09958a0bf02e issue=593
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 692b4f6c94bb4bd7036101112a50de61e90983ab (branch main)"
git checkout 692b4f6c94bb4bd7036101112a50de61e90983ab 2>/dev/null || echo "[repro] WARN: checkout 692b4f6c94bb4bd7036101112a50de61e90983ab failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.blcs.scripts.train --config-name train_chunked_gan data.scene_dir=/home/kamimura/projects/tennis-lab/data/blcs_broadcast data.chunk.chunks_dir=/home/kamimura/projects/tennis-lab/data/blcs_broadcast/chunks data.num_views_range=[1,1] data.camera_mode=random data.num_court_kp=14 data.num_workers=2 data.chunk.generation_workers=8 data.chunk.epochs_per_chunk=20 camera=broadcast training.position_axis_weights=[1.0,4.0,1.0] training.trainer.check_val_every_n_epoch=5 training.qualitative_logging.enabled=false training.gan.target_weight=0.05 training.gan.warmup_epochs=10 training.learning_rate=3e-5 training.trainer.max_epochs=60 training.gan.transition.start_epoch=10 run.init_weights=/home/kamimura/projects/tennis-lab/outputs/blcs/blcs_multiview_axial/logs/version_2/checkpoints/last.ckpt run.output_dir=/home/kamimura/projects/tennis-lab/outputs/blcs/blcs_multiview_axial run.gpus=1
