#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i545_nocanon_s6_h0
# provider=codex session=019ef7e7-03a8-7e53-9c92-21cdcb326a79 issue=560
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: a7bd9a7b4e3bb88a51fe536840a9b44b18d941ec (branch main)"
git checkout a7bd9a7b4e3bb88a51fe536840a9b44b18d941ec 2>/dev/null || echo "[repro] WARN: checkout a7bd9a7b4e3bb88a51fe536840a9b44b18d941ec failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split model.num_layers=0 model.num_task_layers=6 model.predict_canonical_pose=false data=chunked_multiview_sequence_bs8 data.batch_size=8 training.trainer.accumulate_grad_batches=1 data.seq_len_range=[64,256] loss=no_canonical training.trainer.max_epochs=200 training.early_stopping.enabled=false run.gpus=1
