defaults:
  - _self_

input_dir: data/tennis/raw/videos
output_dir: data/tennis/extracted/clips
summary_path: ${output_dir}/summary.json

clips:
  video_1:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  video_2:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  video_3:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  video_4:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  video_5:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  video_6:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  video_7:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  video_8:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []

extraction:
  codec: mp4v
  clear_existing_video_dir: true

hydra:
  run:
    dir: outputs/ball_detection/clip_extract/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
