manifest_path: src/tasks/ball_detection/configs/evaluation/ball_detector_comparison.yaml

hydra:
  run:
    dir: ${tennis_lab_path:project}
  output_subdir: null
  job:
    chdir: false
defaults:
  - paths: default
  - _self_
