defaults:
  - paths: default
  - model: stunet
  - data: rgb_sequence
  - loss: default
  - metrics: default
  - training: default
  - run: train
  - _self_

hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},${run.output_dir},hydra}
  output_subdir: null
  job:
    chdir: false
