defaults:
  - model: stunet
  - data: rgb_sequence
  - metrics: default
  - visualization: default
  - run: visualize
  - _self_

hydra:
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false