#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i934-mixed-ft-s42-r6-20260928
# provider=codex session=01a0e5be-53c1-76e2-a5a0-889df629cd9f issue=934 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-4-mixed-ft}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 8142fc349c268ee567525efc603c11bf705cd5a4 (branch campaign930/i934-4-mixed-ft)"
git checkout 8142fc349c268ee567525efc603c11bf705cd5a4 2>/dev/null || echo "[repro] WARN: checkout 8142fc349c268ee567525efc603c11bf705cd5a4 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-4-mixed-ft/.venv/bin/python -m src.tasks.ball_detection.scripts.train --config-name train_meiji_mixed paths.project_root=/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-4-mixed-ft paths.data_root=/home/kamimura/projects/tennis-lab/data paths.checkpoint_root=/home/kamimura/projects/tennis-lab/ckpt paths.output_root=/home/kamimura/projects/tennis-lab/outputs paths.artifact_root=/home/kamimura/projects/tennis-lab/outputs paths.cache_root=/home/kamimura/projects/tennis-lab/.cache paths.external_asset_root=/home/kamimura/projects/tennis-lab/third_party run.output_dir=ball_detection/train/i934_mixed_ft/s42-r6-20260928
