#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i647_blcs_line_moderate_v2_100ep
# provider=codex session=019f6013-0a29-7183-87ae-e4c221387139 issue=647
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-647-court-line-token}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: f26addb77c3b6c3657f10caa8917328f22ab0274 (branch feat/issue-647-court-line-token)"
git checkout f26addb77c3b6c3657f10caa8917328f22ab0274 2>/dev/null || echo "[repro] WARN: checkout f26addb77c3b6c3657f10caa8917328f22ab0274 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=. PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.blcs.scripts.train model=multiview_axial_line_small data=chunked_multiview_sequence_line_bs4 data.scene_dir=data/blcs_broadcast data.chunk.chunks_dir=data/blcs_broadcast/chunks camera=broadcast data.batch_size=8 data.num_workers=4 data.num_views_range=[1,1] data.seq_len_range=[64,256] data.chunk.generation_workers=8 data.chunk.epochs_per_chunk=20 training.position_axis_weights=[1.0,4.0,1.0] training.reprojection_loss_weight=0.1 training.trainer.max_epochs=100 training.trainer.check_val_every_n_epoch=5 training.qualitative_logging.enabled=false training.early_stopping.enabled=false run.output_dir=outputs/blcs/issue647_line_moderate_v2_100ep run.gpus=1 +data.court_line.augmentation.partial_erasure_prob=0.5 +data.court_line.augmentation.max_partial_erasures=3 +data.court_line.augmentation.occlusion_prob=0.35 +data.court_line.augmentation.max_occlusions=2 +data.court_line.augmentation.false_positive_prob=0.2 +data.court_line.augmentation.max_false_positive_lines=1 +data.court_line.augmentation.blur_prob=0.2 +data.court_line.augmentation.morphology_prob=0.25 +data.court_line.augmentation.far_dropout_prob=0.15 +data.court_line.augmentation.near_only_prob=0.05
