#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i634_slcs_overfit_split_no_dino
# provider=codex session=019f55e6-8819-7e63-8481-72f9effc4079 issue=634
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/i634-dino-compress-split-trunks}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 56445ad063a9a87e6453f4d095c084f8efb0b532 (branch feat/issue-634-dino-compress-split-trunks)"
git checkout 56445ad063a9a87e6453f4d095c084f8efb0b532 2>/dev/null || echo "[repro] WARN: checkout 56445ad063a9a87e6453f4d095c084f8efb0b532 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.slcs.scripts.train model=small data.dataset_root=/home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/tennis_clip/dataset data.split_file=/home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/tennis_clip/dataset/splits.json data.overfit=true data.batch_size=1 data.num_workers=2 training.trainer.max_epochs=100 training.trainer.check_val_every_n_epoch=10 training.trainer.log_every_n_steps=13 training.early_stopping.enabled=false training.learning_rate=3e-4 training.warmup_steps=20 training.checkpoint.save_top_k=1 data.require_dino=false model.num_shared_layers=0 model.num_position_layers=2 model.num_rotation_layers=2 run.output_dir=outputs/slcs/i634_overfit_split_no_dino
