#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i991-rope-gan-gpu-preflight-20261006
# provider=codex session=01a10697-63da-75b2-ae84-f2980da51c23 issue=991 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/coordinate-refiner-rope-gan}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 9588b33833c54423c361d150fbac442f9631497f (branch codex/coordinate-refiner-rope-gan)"
git checkout 9588b33833c54423c361d150fbac442f9631497f 2>/dev/null || echo "[repro] WARN: checkout 9588b33833c54423c361d150fbac442f9631497f failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 .venv/bin/python -m src.tasks.ball_refiner.scripts.train_coordinates training.steps=4 training.evaluate_every=4 training.log_every=1 training.gan.transition.start_step=1 training.gan.warmup_steps=2 run.output_dir=ball_refiner/train/rope-2d-gan-gpu-preflight/20261006-s42
