#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-real-rgb-build-meiji
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 767ac67c43c35f65dd294ddf69a0b6a25d519656 (branch codex/slcs-real-rgb)"
git checkout 767ac67c43c35f65dd294ddf69a0b6a25d519656 2>/dev/null || echo "[repro] WARN: checkout 767ac67c43c35f65dd294ddf69a0b6a25d519656 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env TENNIS_RGB_GPU=0 bash /home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb/scripts/datasets/build_real_rgb.sh --execute meiji 
