#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i539_deep16_chunked
# provider=claude session=8722d9dc-5894-4536-8e54-d03e3e34949a issue=539
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/wt/i525-asym}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: d407e54cdb903d7082aa4011b2a6f8cb0426c7cc (branch exp/i525-asym)"
git checkout d407e54cdb903d7082aa4011b2a6f8cb0426c7cc 2>/dev/null || echo "[repro] WARN: checkout d407e54cdb903d7082aa4011b2a6f8cb0426c7cc failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split_asym_deep16 data.batch_size=4 training.trainer.accumulate_grad_batches=2 data=chunked_multiview_sequence_bs8 data.seq_len_range=[64,256] loss=canonical_rot training.trainer.max_epochs=200 run.gpus=1
