#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i964-recalibration-features-r12-20260930
# provider=codex session=01a0f223-3c51-7b42-8c49-648f9aad0838 issue=964 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-2-tracking}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 91733d9cb25c81c6ea5757a06519a89c6013f087 (branch campaign930/i964-2-tracking)"
git checkout 91733d9cb25c81c6ea5757a06519a89c6013f087 2>/dev/null || echo "[repro] WARN: checkout 91733d9cb25c81c6ea5757a06519a89c6013f087 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout -k 10s 7190s bash /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-2-tracking/tests/benchmarks/association_recalibration_features.sh /home/kamimura/projects/tennis-lab /home/kamimura/projects/tennis-lab/outputs/player_association/evaluate/recalibration/i964-r12-20260930/features
