defaults:
  - data: ball_detection
  - training: ball_detection
  - loss: ball_detection
  - logging: default
  - metrics: ball_detection
  - run: ball_detection
  - model: hrcnet
  - _self_

hydra:
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
