D_model: 256
dim_feedforward: 1024
nheads: 8
decoder_layers: 6
dropout: 0.1

intra_layers: 3
inter_layers: 3
temporal_layers: 3

num_joints: 20
num_court_points: 20
num_queries: 50
max_cameras: 8
max_frames: 32
