defaults:
  - physics: default
  - shot: default
  - camera: default
  - sampling: default
  - generator: default
  - run: generate_dataset
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
  job_logging: null
  hydra_logging: null

