defaults:
  - model: default
  - data: default
  - training: default
  - metrics: default
  - run: train
  - _self_

hydra:
  run:
    dir: outputs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: false

