#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i525_parameff_200ep
# provider=claude session=d22b7d68-7d91-4a6f-862d-434085e5d2d9 issue=536
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/wt/i525-parameff}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: caa677e3995f4bafadf5f354813b1944c83bef1c (branch exp/i525-parameff)"
git checkout caa677e3995f4bafadf5f354813b1944c83bef1c 2>/dev/null || echo "[repro] WARN: checkout caa677e3995f4bafadf5f354813b1944c83bef1c failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python -m src.tasks.plcs.scripts.train model=multiview_axial_split_eff loss=canonical_rot data=multiview_sequence training.trainer.max_epochs=200 run.gpus=1
