#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: scene-component-meiji-fullclip-r2-20260925
# provider=codex session=01a0d0f9-6057-7961-ad6b-adc46744d619 issue=915 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/clip-component-store}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: b0620d701fd38ffd1d5c6cdbeeb8c0f37744cbc4 (branch codex/clip-component-store)"
git checkout b0620d701fd38ffd1d5c6cdbeeb8c0f37744cbc4 2>/dev/null || echo "[repro] WARN: checkout b0620d701fd38ffd1d5c6cdbeeb8c0f37744cbc4 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=4 PYTHONPATH=.:/home/kamimura/projects/tennis-lab/outputs/tennis_scene/analyze/responsibility_cleanup/20260922T170847Z/dino_extension/lib .venv/bin/python tests/benchmarks/component_pipeline.py --repo /home/kamimura/projects/tennis-lab --clip /home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_000 --report /home/kamimura/projects/tennis-lab/outputs/tennis_scene/evaluate/clip_components_meiji_20260925 --device cuda
