name: dino_pseudo3d
input_mode: rgb
in_channels: 3
num_classes: 1
num_frames: 8
input_layout: bcthw
backbone_checkpoint_path: /workspace/checkpoints/DINO/backbone_body_state.pth
backbone_name: resnet50
backbone_dilation: false
return_interm_indices: [0, 1, 2, 3]
backbone_strict: true
freeze_backbone: true
decoder_expand_ratio: 4.0
