defaults:
  - paths: default
  - data: default
  - _self_

evaluate:
  checkpoint: REQUIRED.ckpt
  split: test
  device: cpu
  batch_size: 4
  checkpoint_strict: true
  checkpoint_weights_only: false
  output_dir: slcs/evaluate/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},${evaluate.output_dir}}
  output_subdir: null
  job:
    chdir: false
