defaults:
  - data: default
  - _self_

splits:
  val_ratio: 0.15
  test_ratio: 0.15
  seed: 0
  overwrite: false

hydra:
  run:
    dir: outputs/slcs/make_splits/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
