defaults:
- paths: default
- data: default
- precompute: default
- _self_
hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},${tennis_output:slcs,precompute,precompute_dino_tokens,${tennis_run_id:}},hydra}
  output_subdir: null
  job:
    chdir: false
