#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: staged_phase3
# provider=claude session=7fdebd68-e82c-43c1-b8f9-ded3802a3522 issue=579
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-579-staged-training}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 916575525cdaa7dcbf395d76246c0e4e800a870a (branch feat/issue-579-staged-training)"
git checkout 916575525cdaa7dcbf395d76246c0e4e800a870a 2>/dev/null || echo "[repro] WARN: checkout 916575525cdaa7dcbf395d76246c0e4e800a870a failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.ball_detection.scripts.train_staged --config-name staged_phase3
