#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: mcp-runtime-capabilities-half
# provider=chatgpt-wsl-mcp session=train-f985b53a72b6dce4 issue= resource=half logical_slot=0
set -uo pipefail
export TENNIS_GPU_RESOURCE=half
export TENNIS_GPU_SLOT=0
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/.local/state/tennis-lab-chatgpt-mcp/revisions/rev-04a3f1422bb6c312}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 615fb03e21a86e7cb517758b7b96cecd4cdffb0e (branch HEAD)"
git checkout 615fb03e21a86e7cb517758b7b96cecd4cdffb0e 2>/dev/null || echo "[repro] WARN: checkout 615fb03e21a86e7cb517758b7b96cecd4cdffb0e failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env TENNIS_MCP_REPO_ROOT=/home/kamimura/projects/tennis-lab TENNIS_MCP_STATE_DIR=/home/kamimura/.local/state/tennis-lab-chatgpt-mcp TENNIS_MCP_CONTROL_DIR=/home/kamimura/.local/share/tennis-lab-chatgpt-mcp TENNIS_MCP_ORIGIN_URL=https://github.com/Motoki0705/tennis-lab.git TENNIS_MCP_DOCKER_IMAGE=tennis-lab-mcp:runtime-v1 TENNIS_MCP_UV_PYTHON_ROOT=/home/kamimura/.local/share/uv/python /home/kamimura/.local/share/tennis-lab-chatgpt-mcp/venv/bin/python -I -c 'import sys; from pathlib import Path; sys.path.insert(0, '"'"'/home/kamimura/.local/share/tennis-lab-chatgpt-mcp/current'"'"'); from src.automation.chatgpt_mcp.sandbox_exec import run_from_spec; raise SystemExit(run_from_spec(Path(sys.argv[1])))' /home/kamimura/.local/state/tennis-lab-chatgpt-mcp/training-specs/train-f985b53a72b6dce4.json
