#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: issue878_b00_rendered_line_projection
# provider=codex session=01a094f3-f431-7871-b55d-5c34ca6f48dc issue=878 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-878-rendered-line-input}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: c4bb0e63b43ae4492f190bfac485a4dae087af5d (branch feat/issue-878-rendered-line-input)"
git checkout c4bb0e63b43ae4492f190bfac485a4dae087af5d 2>/dev/null || echo "[repro] WARN: checkout c4bb0e63b43ae4492f190bfac485a4dae087af5d failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
TENNIS_RUN_B00_RENDERED_ALIGNMENT_GPU_TEST=1 TENNIS_B00_FIXTURE_REPOSITORY=/home/kamimura/projects/tennis-lab PYTHONPATH=. .venv/bin/pytest -q -n 0 -s tests/integration/synthetic_data_generation/test_alignment_rendered_input_gpu.py
