defaults:
  - physics: default
  - rally: default
  - camera: default
  - sampling: default
  - targeted_velocity: default
  - generator: default
  - run: generate_dataset
  - _self_

hydra:
  run:
    dir: outputs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
