defaults:
  - court_keypoints: physical_v1
  - paths: default
  - visualization: multiview
  - _self_

hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},${tennis_output:blcs,visualize,${visualization.mode},${tennis_run_id:}},hydra}
  output_subdir: null
  job:
    chdir: false
