#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i801_attempt2_blcs_selector_zero_paired_v6_final
# provider=codex session=01a03207-0be4-72c1-ba60-a051d0d8d9b6 issue=801
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-801-reference-rope}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 40c21fbad59e040f52c040ae354637c5f3c8975a (branch feat/issue-801-reference-camera-rope)"
git checkout 40c21fbad59e040f52c040ae354637c5f3c8975a 2>/dev/null || echo "[repro] WARN: checkout 40c21fbad59e040f52c040ae354637c5f3c8975a failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.blcs.scripts.evaluate_reference_counterfactual evaluation.checkpoint_path=/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-801-reference-rope/outputs/blcs/norm-v2/issue-801/t128-v4/ablation-d-selector-zero-eb32-seeded-retry4/logs/version_0/checkpoints/last.ckpt paths.data_root=/home/kamimura/projects/tennis-lab/data data.scene_dir=blcs/multi_object_camera_view_norm-v2 data.batch_size=1 data.num_workers=16 model=track_query_ablation_d_v2_selector_zero evaluation.trainer.accelerator=gpu evaluation.trainer.precision=bf16-mixed
