#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: ball-mix-v2-player-pose-gpu-smoke-20261002
# provider=codex session=01a0f53f-bff2-7202-b7ee-5fa777ae6627 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-mix-v2-player-pose}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: bd48b063d73778710f849e56178e07806343ec1e (branch codex/ball-mix-v2-player-pose)"
git checkout bd48b063d73778710f849e56178e07806343ec1e 2>/dev/null || echo "[repro] WARN: checkout bd48b063d73778710f849e56178e07806343ec1e failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/context/i935-context-fullframe-pilot-r10-20260928/dino_extension/lib:/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-mix-v2-player-pose OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2 MKL_NUM_THREADS=2 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True CUDA_LAUNCH_BLOCKING=1 /home/kamimura/projects/tennis-lab/.venv/bin/python -u /home/kamimura/projects/tennis-lab/.claude/worktrees/ball-mix-v2-player-pose/.runtime/gpu_smoke.py
