#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: issue-643-multiperson-baseline
# provider=codex session=019f6023-b08a-7af3-aa59-182d7cf43958 issue=643
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-643-648-multi-object-tracking}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 6ef9adbd7c055a31fdb936da5f475345a3f5d098 (branch feat/issue-643-648-multi-object-tracking)"
git checkout 6ef9adbd7c055a31fdb936da5f475345a3f5d098 2>/dev/null || echo "[repro] WARN: checkout 6ef9adbd7c055a31fdb936da5f475345a3f5d098 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
.venv/bin/python -m src.tasks.player_tracking.scripts.train run.output_dir=outputs/player_tracking/issue-643-baseline
