defaults:
  - model: uv_transformer
  - data: blcs_rally_uv
  - training: default
  - metrics: default
  - run: train
  - _self_

hydra:
  run:
    dir: outputs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: false

