#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1031-player-ckpt-qualitative-20261008a
# provider=codex session=01a113c9-1114-71a2-9261-80815f662d33 issue=1031 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-1031-qualitative-schedule}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: c751331f589a40432920a4f9fc2bbf34eb3c96db (branch fix/issue-1031-qualitative-schedule)"
git checkout c751331f589a40432920a4f9fc2bbf34eb3c96db 2>/dev/null || echo "[repro] WARN: checkout c751331f589a40432920a4f9fc2bbf34eb3c96db failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m scripts.verify_qualitative_checkpoints --task player_detection --asset-root /home/kamimura/projects/tennis-lab --checkpoint /home/kamimura/projects/tennis-lab/ckpt/player_detection/chat-player-v1-e8-best-epoch03.ckpt --output-dir /home/kamimura/projects/tennis-lab/outputs/player_detection/evaluate/issue-1031-qualitative/20261008a --sample-indices 0 347 --player-max-frames 60 --player-display-width 640
