#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-vitpose-redownload-smoke-v1
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 3bebe44d52f4a2cc2a77f2bc2dba1eea31be306e (branch codex/slcs-real-rgb)"
git checkout 3bebe44d52f4a2cc2a77f2bc2dba1eea31be306e 2>/dev/null || echo "[repro] WARN: checkout 3bebe44d52f4a2cc2a77f2bc2dba1eea31be306e failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 PYTHONPATH=. .venv/bin/python knowledge/runs/run-slcs-vitpose-redownload-smoke-v1/driver.py --video /home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_000/media/cam0.mp4 --observations /home/kamimura/projects/tennis-lab/outputs/tennis_scene/precompute/meiji_dino_vitpose/s42-004/video_000/clip_000/cam0_people.npz --checkpoint /home/kamimura/projects/tennis-lab/third_party/GVHMR/inputs/checkpoints/vitpose/vitpose-h-multi-coco.pth --installation /home/kamimura/projects/tennis-lab/outputs/tennis_scene/analyze/vitpose_redownload/s42-001/installation.json --output /home/kamimura/projects/tennis-lab/outputs/tennis_scene/analyze/vitpose_redownload_smoke/s42-001
