#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1032-a-coords-s42-v1
# provider=claude session=72300f25-ca01-4859-9c8e-1ce0c340f9c3 issue=1032 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-1032-physics-refiner}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 6d0cc11313b2c67c0fcbed79265f8aebafeb13b7 (branch feat/issue-1032-p5-physics-heads)"
git checkout 6d0cc11313b2c67c0fcbed79265f8aebafeb13b7 2>/dev/null || echo "[repro] WARN: checkout 6d0cc11313b2c67c0fcbed79265f8aebafeb13b7 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 .venv/bin/python -m src.tasks.ball_refiner_3d.scripts.train paths.data_root=/home/kamimura/projects/tennis-lab/data paths.output_root=/home/kamimura/projects/tennis-lab/outputs run.output_dir=ball_refiner_3d/train/i1032-physics/a-coords-s42-v1
