#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: issue880_b02_wide_v1
# provider=codex session=01a09588-636e-7560-b584-5451ff831df9 issue=880 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-880-semantic-alignment}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: cfc211b87ad3a1027082f5a9f9092956f09eee11 (branch feat/issue-880-semantic-alignment)"
git checkout cfc211b87ad3a1027082f5a9f9092956f09eee11 2>/dev/null || echo "[repro] WARN: checkout cfc211b87ad3a1027082f5a9f9092956f09eee11 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-880-semantic-alignment /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.synthetic_data_generation.scripts.compare_semantic_alignment profile=b02 roots.project_root=/home/kamimura/projects/tennis-lab comparison.checkpoint=court_detection/mixed-source/semantic-line-frozen-b00-b03-b8-e20-s42/logs/version_0/checkpoints/last.ckpt comparison.output=issue880/b02-wide-v1 comparison.translation_radius_metres=8 comparison.maximum_iterations=2000
