#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i991-coordinate-gpu-smoke-20261005
# provider=codex session=01a10697-63da-75b2-ae84-f2980da51c23 issue=991 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/coordinate-ball-refiners-991-1014}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: ea96f1ffaa378f5b36d5347f29dabbd3edaee038 (branch codex/coordinate-ball-refiners-991-1014)"
git checkout ea96f1ffaa378f5b36d5347f29dabbd3edaee038 2>/dev/null || echo "[repro] WARN: checkout ea96f1ffaa378f5b36d5347f29dabbd3edaee038 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 .venv/bin/python -m src.tasks.ball_refiner.scripts.train_coordinates paths.data_root=/tmp/ball-refiner-coordinate-smoke run.output_dir=ball_refiner/train/coordinates-smoke/gpu-20261005 training.steps=100 training.batch_size=32 training.evaluate_every=100 training.log_every=25 training.gan_warmup_steps=25
