output_dir: ball_detection/eval/${model.name}
seed: 42
gpus: 1
checkpoint_path: ball_detection/stunet/logs/version_2/checkpoints/ball-detection-epoch=18.ckpt
strict: true
weights_only: false
allow_device_fallback: false
