#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i801_dref_pose_beta005_inact1_match025_s42_r1
# provider=codex session=01a04915-27a4-7b62-9f6b-34275561fded issue=801
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-tracking-pose-beta005}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 9ffae3d34d34fe93b41a4f7e64e60238b3254cd4 (branch experiments/plcs-tracking-pose-beta005)"
git checkout 9ffae3d34d34fe93b41a4f7e64e60238b3254cd4 2>/dev/null || echo "[repro] WARN: checkout 9ffae3d34d34fe93b41a4f7e64e60238b3254cd4 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.plcs.scripts.train --config-name train_tracking_pose model=track_query_ablation_d_v2_selector court_keypoints=camera_view_v2 model.cswa.backend=cuda paths.data_root=/home/kamimura/projects/tennis-lab/data data.scene_dir=plcs/multi_object_camera_view_v2 'data.seq_len_range=[128,128]' 'data.num_views_range=[6,6]' data.batch_size=8 data.num_workers=16 data.evaluation_reference_camera_id=camera_2 loss.presence_inactive_weight=1.0 loss.match_presence_inactive_weight=0.25 training.compile.enabled=false training.trainer.precision=bf16-mixed training.trainer.accumulate_grad_batches=4 training.trainer.max_epochs=40 training.warmup_steps=400 training.trainer.check_val_every_n_epoch=5 training.trainer.enable_progress_bar=false training.trainer.enable_model_summary=false training.early_stopping.enabled=false training.qualitative_logging.enabled=false run.seed=42 run.fast_dev_run=false run.test_after_fit=true run.output_dir=plcs/i801_dref_pose_beta005_inact1_match025_s42_r1
