#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i535_asym_deep16_rerun
# provider=claude session=8722d9dc-5894-4536-8e54-d03e3e34949a issue=535
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/wt/i525-asym}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 6d24b4dccad36a73bd56a526602757e16bac0275 (branch exp/i525-asym)"
git checkout 6d24b4dccad36a73bd56a526602757e16bac0275 2>/dev/null || echo "[repro] WARN: checkout 6d24b4dccad36a73bd56a526602757e16bac0275 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split_asym_deep16 loss=canonical_rot data=multiview_sequence data.batch_size=4 training.trainer.max_epochs=200 run.gpus=1
