#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: pr937-player-inference-real-frame-20260928
# provider=codex session=01a0e2cc-b573-7011-939d-947448f2d4e0 issue=937 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/pr937-player-inference}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 665d10d1e25085e991678910dd216e791b29817c (branch codex/pr937-player-inference)"
git checkout 665d10d1e25085e991678910dd216e791b29817c 2>/dev/null || echo "[repro] WARN: checkout 665d10d1e25085e991678910dd216e791b29817c failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PLAYER_DETECTION_GPU_TEST=1 PLAYER_DETECTION_ARTIFACT_ROOT=/home/kamimura/projects/tennis-lab .venv/bin/python -m pytest -n 0 tests/integration/tasks/player_detection/test_exported_inference.py -q
