#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i621_court_kp512_resume_r4
# provider=claude session= issue=621
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 41b318b39f757e09897964a32f28148a777b87f5 (branch feat/issue-618-ball-subpixel-retrain)"
git checkout 41b318b39f757e09897964a32f28148a777b87f5 2>/dev/null || echo "[repro] WARN: checkout 41b318b39f757e09897964a32f28148a777b87f5 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.court_detection.scripts.train data=court_kp loss=kp model.num_classes=14 data.augmentation.train_scales=[512] data.augmentation.val_short_side=512 data.num_workers=2 training.trainer.max_epochs=50 training.checkpoint.monitor=val/mean_dist training.checkpoint.mode=min training.early_stopping.monitor=val/mean_dist training.early_stopping.mode=min run.resume=outputs/court_detection/kp/logs/version_0/checkpoints/last.ckpt
