#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-context-shard-00201-chat-r12-20260928
# provider=codex session=01a0e875-821a-7933-ab59-3a7e497a165c issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-9-context-shards}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: db28d14d3a965fb0b6d7971cf364419ef980c137 (branch campaign930/i935-9-context-shards)"
git checkout db28d14d3a965fb0b6d7971cf364419ef980c137 2>/dev/null || echo "[repro] WARN: checkout db28d14d3a965fb0b6d7971cf364419ef980c137 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
'timeout' '--signal=TERM' '--kill-after=15s' '18m' 'bash' '/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-9-context-shards/tests/benchmarks/ball_refiner_context_shard.sh' '/home/kamimura/projects/tennis-lab' '/home/kamimura/projects/tennis-lab/data/ball_refiner/detector-ft-e13-trainval-r3-20260928' '/home/kamimura/projects/tennis-lab/data/ball_refiner/context-fullframe-shards-r12-20260928/plan/plan.json' '/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/context/i935-context-shards-r12-20260928/scene-context.yaml' '/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/context/i935-context-shards-r12-20260928/dino_extension' '201' '/home/kamimura/projects/tennis-lab/data/ball_refiner/context-fullframe-shards-r12-20260928/shard-00201-a1' '/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/context/i935-context-shards-r12-20260928/shard-00201-a1'
