#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-anchored-seed44-r24-20260930
# provider=codex session=01a0f1dc-49b9-7c82-bcfb-fe29dda6b9e1 issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-11-pilot-retrain}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 521eea03985a96a715a26cdbdbdac90995aebfb6 (branch campaign930/i935-14-pipeline-candidate)"
git checkout 521eea03985a96a715a26cdbdbdac90995aebfb6 2>/dev/null || echo "[repro] WARN: checkout 521eea03985a96a715a26cdbdbdac90995aebfb6 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --signal=TERM --kill-after=15s 2385s env PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-11-pilot-retrain OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2 TORCHINDUCTOR_COMPILE_THREADS=2 MAX_JOBS=2 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True TORCHINDUCTOR_CACHE_DIR=/home/kamimura/projects/tennis-lab/outputs/ball_refiner/analyze/precision/i935-seed44-r24-20260930-compiler /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-11-pilot-retrain/.venv/bin/python -u /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-11-pilot-retrain/knowledge/runs/run-i935-precision-variants-s42-r21-20260930/run_variants.py --plan /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-11-pilot-retrain/knowledge/runs/run-i935-seed44-retry-r24-20260930/plan.json
