#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-full-real-rgb-one-sided-context-e60-v1
# provider=codex session=01a0b71f-c516-75b2-ac58-0c92e8a4f098 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: f8f83a6c457c153640dcba04ed86722cbdb794f9 (branch codex/slcs-real-rgb)"
git checkout f8f83a6c457c153640dcba04ed86722cbdb794f9 2>/dev/null || echo "[repro] WARN: checkout f8f83a6c457c153640dcba04ed86722cbdb794f9 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env PYTHONUNBUFFERED=1 PYTHONFAULTHANDLER=1 CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python -m src.tasks.slcs.scripts.train --config-name train_real_rgb_one_sided_context paths.checkpoint_root=/home/kamimura/projects/tennis-lab/outputs paths.data_root=/home/kamimura/projects/tennis-lab/data paths.output_root=/home/kamimura/projects/tennis-lab/outputs run.output_dir=slcs/train/real_rgb_one_sided_context/s42-001
