#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i719-blcs-kp7-reference-benchmark
# provider=codex session=019ff682-9749-74d2-ad8c-7a39e815dcd5 issue=719
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-719-courtkp7-reference}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 6daaebce341c02acbc1fd3948093afad9508bcb7 (branch feat/issue-719-courtkp7-reference)"
git checkout 6daaebce341c02acbc1fd3948093afad9508bcb7 2>/dev/null || echo "[repro] WARN: checkout 6daaebce341c02acbc1fd3948093afad9508bcb7 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=. PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.blcs.scripts.train --config-name train_tracking model=track_query_kp7_reference data.scene_dir=issue719/blcs data.seq_len_range='[64,64]' data.num_views_range='[3,5]' data.batch_size=8 data.num_workers=4 training.trainer.max_epochs=3 training.trainer.check_val_every_n_epoch=1 training.warmup_steps=0 training.early_stopping.enabled=false training.qualitative_logging.enabled=false run.seed=719 run.output_dir=issue719/i719-blcs-kp7-reference-benchmark run.test_after_fit=true
