#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1034-vidmap-b00-p90-default-a0
# provider=codex session=01a1106e-187c-7163-be4e-9f1673767ad9 issue=1034 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: b113500e37bd391125a39a6a1862a4e73fabf11a (branch research/sfm-night-20261006)"
git checkout b113500e37bd391125a39a6a1862a4e73fabf11a 2>/dev/null || echo "[repro] WARN: checkout b113500e37bd391125a39a6a1862a4e73fabf11a failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.venv/bin/python -m experiments.sfm_comparison.run_command --campaign /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006 --run-id vidmap-b00-p90-default-a0 --stage sfm --seconds 5400 --required-path /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006/vidmap-p90-default-a0/evaluation/metrics.json --metrics-source /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006/vidmap-p90-default-a0/evaluation/metrics.json -- env HF_HOME=/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.cache/vidmap-model-cache/huggingface TORCH_HOME=/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.cache/vidmap-model-cache/torch HF_HUB_DISABLE_XET=1 TORCHINDUCTOR_CACHE_DIR=/home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.cache/vidmap-compile TORCHINDUCTOR_COMPILE_THREADS=2 OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=4 MKL_NUM_THREADS=4 /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.cache/runtimes/vidmap-native/bin/python -m experiments.sfm_comparison.run_vidmap --images /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006/baseline-a1/frames/images --manifest /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006/inputs/manifest-a1.json --output /home/kamimura/projects/tennis-lab/outputs/aris/i1034-sfm-night-20261006/vidmap-p90-default-a0 --evaluator-root /home/kamimura/projects/tennis-lab/.claude/worktrees/sfm-night-20261006/.cache/nht
