#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: dino-input-abl512-repeat_rgb
# provider=codex session=01a06b47-7972-7521-a83c-be95cccf7d91 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/dino-detr-court-alignment}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 6631f8224a1869bf1ef5d08c8bfbae41cc0cb3a4 (branch feat/dino-detr-court-alignment)"
git checkout 6631f8224a1869bf1ef5d08c8bfbae41cc0cb3a4 2>/dev/null || echo "[repro] WARN: checkout 6631f8224a1869bf1ef5d08c8bfbae41cc0cb3a4 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/dino-detr-court-alignment /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.court_alignment.scripts.train --config-name train_dino paths.project_root=/home/kamimura/projects/tennis-lab paths.external_asset_root=/home/kamimura/projects/tennis-lab/third_party paths.output_root=/home/kamimura/projects/tennis-lab/.claude/worktrees/dino-detr-court-alignment/outputs model.repository=/home/kamimura/projects/tennis-lab/third_party/DINO model.checkpoint_path=/home/kamimura/projects/tennis-lab/ckpt/dino/checkpoint0029_4scale_swin.pth model.device=cuda:0 data.train_samples=512 data.val_samples=128 data.test_samples=128 data.batch_size=1 data.num_workers=2 training.steps_per_epoch=512 training.warmup_steps=32 training.trainer.max_epochs=1 training.trainer.precision=32-true training.trainer.log_every_n_steps=25 training.checkpoint.save_top_k=1 training.checkpoint.save_last=false run.fast_dev_run=false run.test_after_fit=true model.input_mode=repeat_rgb run.output_dir=court_alignment/dino_input_ablation_512_repeat_rgb
