#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i576_camtoken_s0_h12
# provider=claude session=83686dbd-1af9-4c61-814d-63204dfb6684 issue=576
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-576-camera-token-split}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 8ed46945dae97f9307b38562cbbfd79172388929 (branch exp/issue-576-camera-token-split)"
git checkout 8ed46945dae97f9307b38562cbbfd79172388929 2>/dev/null || echo "[repro] WARN: checkout 8ed46945dae97f9307b38562cbbfd79172388929 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_camtoken data.batch_size=8 training.trainer.accumulate_grad_batches=1 data=chunked_multiview_sequence_bs8 data.seq_len_range=[64,256] loss=canonical_rot training.trainer.max_epochs=200 training.early_stopping.enabled=false training.trainer.check_val_every_n_epoch=10 run.gpus=1
