"""Canonical public API for shared task model I/O lifecycle contracts."""

from src.tasks.base.model_io.contracts import (
    BoundModelIO,
    ModelAdapterMismatchError,
    ModelArgument,
    ModelCall,
    ModelInputContractError,
    ModelIOAdapter,
    ModelIOContractError,
    ModelOutputContractError,
    bind_model_io,
)
from src.tasks.base.model_io.court_keypoint_contract import (
    ModelArtifactCourtKeypointContract,
    extract_model_artifact_court_keypoint_contract,
    resolve_model_artifact_court_keypoint_contract,
    validate_model_artifact_court_keypoint_contract,
    write_model_artifact_court_keypoint_contract,
)
from src.tasks.base.model_io.tensors import TensorSpec, require_tensor
from src.tasks.base.model_io.track_query_reference import (
    REFERENCE_SELECTOR_NOT_APPLICABLE,
    TRACK_QUERY_CHECKPOINT_ARCHITECTURE_ID,
    TRACK_QUERY_CHECKPOINT_ARCHITECTURE_METADATA_KEY,
    TRACK_QUERY_CHECKPOINT_ARCHITECTURE_SCHEMA_VERSION,
    TRACK_QUERY_REFERENCE_METADATA_KEY,
    TRACK_QUERY_REFERENCE_METADATA_SCHEMA_VERSION,
    InvalidTrackQueryReferenceMetadataError,
    MissingTrackQueryReferenceMetadataError,
    ModelArtifactTrackQueryReferenceContract,
    TrackQueryReferenceContract,
    TrackQueryReferenceContractError,
    TrackQueryReferenceContractMetadata,
    TrackQueryReferenceContractMismatchError,
    extract_track_query_reference_contract_metadata,
    resolve_track_query_reference_contract,
    validate_checkpoint_track_query_reference_contract,
    validate_track_query_reference_contract,
    write_checkpoint_track_query_reference_contract,
    write_track_query_reference_contract,
)

__all__ = [
    "BoundModelIO",
    "ModelAdapterMismatchError",
    "ModelArgument",
    "ModelCall",
    "ModelIOAdapter",
    "ModelIOContractError",
    "ModelInputContractError",
    "ModelOutputContractError",
    "ModelArtifactCourtKeypointContract",
    "ModelArtifactTrackQueryReferenceContract",
    "MissingTrackQueryReferenceMetadataError",
    "InvalidTrackQueryReferenceMetadataError",
    "REFERENCE_SELECTOR_NOT_APPLICABLE",
    "TRACK_QUERY_CHECKPOINT_ARCHITECTURE_ID",
    "TRACK_QUERY_CHECKPOINT_ARCHITECTURE_METADATA_KEY",
    "TRACK_QUERY_CHECKPOINT_ARCHITECTURE_SCHEMA_VERSION",
    "TRACK_QUERY_REFERENCE_METADATA_KEY",
    "TRACK_QUERY_REFERENCE_METADATA_SCHEMA_VERSION",
    "TensorSpec",
    "TrackQueryReferenceContract",
    "TrackQueryReferenceContractError",
    "TrackQueryReferenceContractMetadata",
    "TrackQueryReferenceContractMismatchError",
    "bind_model_io",
    "extract_model_artifact_court_keypoint_contract",
    "extract_track_query_reference_contract_metadata",
    "require_tensor",
    "resolve_model_artifact_court_keypoint_contract",
    "resolve_track_query_reference_contract",
    "validate_checkpoint_track_query_reference_contract",
    "validate_track_query_reference_contract",
    "validate_model_artifact_court_keypoint_contract",
    "write_model_artifact_court_keypoint_contract",
    "write_checkpoint_track_query_reference_contract",
    "write_track_query_reference_contract",
]
