#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: blcs-triangulation-residual-physics-v1
# provider=codex session=01a0bf91-5494-74c0-8793-3424866618ed issue= resource=half logical_slot=1
set -uo pipefail
export TENNIS_GPU_RESOURCE=half
export TENNIS_GPU_SLOT=1
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-triangulation-residual}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 893d0ca4129e9e69f8e8c850d89c6200cf2df2e3 (branch codex/plcs-triangulation-residual)"
git checkout 893d0ca4129e9e69f8e8c850d89c6200cf2df2e3 2>/dev/null || echo "[repro] WARN: checkout 893d0ca4129e9e69f8e8c850d89c6200cf2df2e3 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
'env' 'CUDA_VISIBLE_DEVICES=0' 'OMP_NUM_THREADS=2' 'OPENBLAS_NUM_THREADS=1' 'MKL_NUM_THREADS=2' '/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-triangulation-residual/.venv/bin/python' '-u' '-m' 'src.tasks.blcs.scripts.train_triangulation_residual' 'paths.data_root=/home/kamimura/projects/tennis-lab/data' 'paths.output_root=/home/kamimura/projects/tennis-lab/outputs' 'paths.artifact_root=/home/kamimura/projects/tennis-lab/outputs' 'paths.checkpoint_root=/home/kamimura/projects/tennis-lab/outputs' 'paths.cache_root=/home/kamimura/projects/tennis-lab/.cache' 'paths.external_asset_root=/home/kamimura/projects/tennis-lab/data' 'run.output_dir=blcs/triangulation_residual_v1_20260921' 'training.trainer.enable_progress_bar=false' && 'env' 'CUDA_VISIBLE_DEVICES=0' 'OMP_NUM_THREADS=2' 'OPENBLAS_NUM_THREADS=1' 'MKL_NUM_THREADS=2' '/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-triangulation-residual/.venv/bin/python' '-u' '-m' 'src.tasks.base.triangulation_residual.inference' '--task' 'blcs' '--run-dir' '/home/kamimura/projects/tennis-lab/outputs/blcs/triangulation_residual_v1_20260921' '--clip' '/home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_000' '--output' '/mnt/c/Users/kamim/.codex/visualizations/2026/09/20/01a0bf91-5494-74c0-8793-3424866618ed/geometric-residual/blcs' '--device' 'cuda'
