#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-meiji-checkpoint-hash-probe-v3
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 89daad4e7cf501ff4c63f5016d9aa25ae159ac52 (branch codex/slcs-real-rgb)"
git checkout 89daad4e7cf501ff4c63f5016d9aa25ae159ac52 2>/dev/null || echo "[repro] WARN: checkout 89daad4e7cf501ff4c63f5016d9aa25ae159ac52 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --kill-after=5s 590s env PYTHONPATH=. CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python -B knowledge/runs/run-slcs-meiji-checkpoint-hash-probe-v3/probe.py --output-dir outputs/tennis_scene/analyze/meiji_hash_probe_v3/s42-001
