task: tennis_pose
experiment_name: tennis_mvpose_dev

includes:
  dataset: datasets/tennis_pose_sim.yaml
  model: models/tennis_mvpose.yaml
  training: training/tennis_mvpose.yaml
  logging: logging/tennis_mvpose.yaml
