task: tennis_multi_cam_3d_pose
experiment_name: tennis_mvpose_dev_v2

includes:
  dataset: datasets/tennis_multi_cam_3d_pose_sim.yaml
  model: models/tennis_mvpose_v2.yaml
  training: training/tennis_mvpose_v2.yaml
  logging: logging/tennis_mvpose.yaml
