#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i545_s4_h4_posw4
# provider=codex session=019ef7e7-03a8-7e53-9c92-21cdcb326a79 issue=545
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 8ce84fc04df94fba6a0489133a67914859ed5dbf (branch main)"
git checkout 8ce84fc04df94fba6a0489133a67914859ed5dbf 2>/dev/null || echo "[repro] WARN: checkout 8ce84fc04df94fba6a0489133a67914859ed5dbf failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split model.num_layers=4 model.num_task_layers=4 data=chunked_multiview_sequence_bs8 data.batch_size=8 training.trainer.accumulate_grad_batches=1 data.seq_len_range=[64,256] loss=canonical_rot loss.position_weight=4.0 training.trainer.max_epochs=200 training.early_stopping.enabled=false run.gpus=1
