#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: b01_court_shapes_full
# provider=codex session=01a088da-0867-7e43-99b5-415e56dc292d issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab-worktrees/court-sfm-bounded}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 96b98a17ee067d9956cafcfb65448d527910349b (branch codex/court-sfm-bounded)"
git checkout 96b98a17ee067d9956cafcfb65448d527910349b 2>/dev/null || echo "[repro] WARN: checkout 96b98a17ee067d9956cafcfb65448d527910349b failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# #931: NOT REPRODUCIBLE. outputs/b01-court-shapes/full_render_check.py was neither committed nor saved in
# this bundle, and outputs/ has since been deleted. The original command (see run.json) was:
#   CUDA_VISIBLE_DEVICES=0 PYTHONPATH=. .venv/bin/python outputs/b01-court-shapes/full_render_check.py
echo "[repro] full_render_check.py of this run was not preserved; see run.json" >&2
exit 1
