#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i576_camtoken_posw8
# provider=claude session=163b1591-40c5-4551-8b36-29e97a8931bc issue=576
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-576-camera-token-split}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 27c9c73053baedffd2e2152520cf35443d170c57 (branch exp/issue-576-camera-token-split)"
git checkout 27c9c73053baedffd2e2152520cf35443d170c57 2>/dev/null || echo "[repro] WARN: checkout 27c9c73053baedffd2e2152520cf35443d170c57 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_camtoken data.batch_size=8 training.trainer.accumulate_grad_batches=1 data=chunked_multiview_sequence_bs8 data.seq_len_range=[64,256] loss=canonical_rot training.trainer.max_epochs=200 training.early_stopping.enabled=false training.trainer.check_val_every_n_epoch=10 run.gpus=1 loss.position_weight=8.0
