#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i936-repro3-512-physics10-r17-s936-20261001
# provider=codex session=01a0f48a-352c-7fe0-8609-b27d0b56436b issue=936 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4a882fcaf9a5e0e74121fb697d9ca1e20bfa0b3e (branch campaign930/i936-2-synthetic-diffusion)"
git checkout 4a882fcaf9a5e0e74121fb697d9ca1e20bfa0b3e 2>/dev/null || echo "[repro] WARN: checkout 4a882fcaf9a5e0e74121fb697d9ca1e20bfa0b3e failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --signal=TERM --kill-after=15s 5340s env CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 NUMEXPR_NUM_THREADS=1 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation/.venv/bin/python -u -m src.tasks.ball_refiner.scripts.experiment_dev_3d --plan /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i936-probabilistic-triangulation/knowledge/runs/run-i936-repro3-512-physics10-r17-s936/plan.json --device cuda
