#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: mono3d_blcs_ftB_s06g03
# provider=claude session=dd9d56e0-5f2d-4d9d-a8c7-c80704a806b3 issue=593
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: d36b7dc50522453fa13778e7d31756a733fa0403 (branch feat/issue-593-physics-prior)"
git checkout d36b7dc50522453fa13778e7d31756a733fa0403 2>/dev/null || echo "[repro] WARN: checkout d36b7dc50522453fa13778e7d31756a733fa0403 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.blcs.scripts.train --config-name train_chunked data.scene_dir=data/blcs_broadcast data.chunk.chunks_dir=data/blcs_broadcast/chunks data.num_views_range=[1,1] data.camera_mode=random data.num_court_kp=14 data.num_workers=2 data.chunk.generation_workers=8 data.chunk.epochs_per_chunk=20 camera=broadcast training.position_axis_weights=[1.0,4.0,1.0] training.learning_rate=3e-5 training.trainer.max_epochs=60 training.trainer.check_val_every_n_epoch=5 training.qualitative_logging.enabled=false training.early_stopping.enabled=false run.gpus=1 training.smoothness_loss_weight=0.6 training.gravity_loss_weight=0.30 run.init_weights=outputs/blcs/blcs_multiview_axial/logs/version_2/checkpoints/last.ckpt
