defaults:
  - model: traj3d_transformer
  - data: chunked_blcs_rally_3d
  - training: default
  - metrics: default
  - run: train
  - _self_

hydra:
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false