defaults:
  - paths: default
  - _self_

hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},${tennis_output:court_detection,generate,generate_masks,${tennis_run_id:}},hydra}
  output_subdir: null
  job:
    chdir: false

generate_masks:
  root: court
  image_id: null
  write_color_mask: false
  color_dir_name: masks_color
