defaults:
  - paths: default
  - _self_

hydra:
  run:
    dir: ${tennis_lab_path:output,${paths.output_root},court_detection/generate_line_masks,${now:%Y-%m-%d_%H-%M-%S}}
  output_subdir: null
  job:
    chdir: false

generate_line_masks:
  root: court
  image_id: null
  mask_dir_name: line_masks
  preview_dir: court_detection/line_mask_preview
  preview_count_per_split: 8
