#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-meiji-court-crop-probe-v1
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 41020d13080c5c1765c218924bbbb4d2aee2ef84 (branch codex/slcs-real-rgb)"
git checkout 41020d13080c5c1765c218924bbbb4d2aee2ef84 2>/dev/null || echo "[repro] WARN: checkout 41020d13080c5c1765c218924bbbb4d2aee2ef84 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 bash knowledge/runs/run-slcs-meiji-court-crop-probe-v1/repro.sh --output /home/kamimura/projects/tennis-lab/outputs/tennis_scene/evaluate/meiji_court_crop_probe/s42-001
