#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-meiji-checkpoint-hash-cpu-v1
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: d4e6e65244b3eabc530c57e5899f117168785a62 (branch codex/slcs-real-rgb)"
git checkout d4e6e65244b3eabc530c57e5899f117168785a62 2>/dev/null || echo "[repro] WARN: checkout d4e6e65244b3eabc530c57e5899f117168785a62 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --kill-after=5s 590s env OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 .venv/bin/python -B knowledge/runs/run-slcs-meiji-checkpoint-hash-cpu-v1/probe.py --output-dir outputs/tennis_scene/analyze/meiji_hash_cpu_v1/s42-001
