#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i986-pread-sustained-v2
# provider=codex session=01a0fb0c-97b5-7851-b805-25dae445a6a2 issue=986 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-query-only-training}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 2da3351a28cf6c685767338f0f768d3c357c402e (branch codex/ball-query-only-training)"
git checkout 2da3351a28cf6c685767338f0f768d3c357c402e 2>/dev/null || echo "[repro] WARN: checkout 2da3351a28cf6c685767338f0f768d3c357c402e failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env PYTHONPATH=. OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 TORCHINDUCTOR_COMPILE_THREADS=2 TORCH_LOGS=graph_breaks,recompiles PYTHONUNBUFFERED=1 timeout 2400 .venv/bin/python tests/benchmarks/ball_mdd_query_gpu.py --manifest /home/kamimura/projects/tennis-lab/outputs/ball_detection/precompute/mdd_coordinates_36/20261008-fps124-v1/mdd_only_windows.json --model-config "$SCRIPT_DIR/model.yaml" --output /home/kamimura/projects/tennis-lab/outputs/ball_detection/analyze/native-rgb-reader/20261009-pread-sustained-v2/report.json --mode pipeline --workers 2 --prefetch-factor 2 --pin-memory --precision bf16 --compile-mode default --jpeg-decoder nvjpeg --image-prefetch --preverify --drop-file-cache --batch-size 1 --warmup 12 --steps 1008
