#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-detector-only-ft-e13-s42-r4-20260928
# provider=codex session=01a0e7b2-7de1-75c2-a2fe-c844567c4de0 issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-4-training}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: afc2c0fd76d3891162162ce558d5ea969b579bab (branch campaign930/i935-4-training)"
git checkout afc2c0fd76d3891162162ce558d5ea969b579bab 2>/dev/null || echo "[repro] WARN: checkout afc2c0fd76d3891162162ce558d5ea969b579bab failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-4-training OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-4-training/.venv/bin/python -u -m src.tasks.ball_refiner.scripts.train paths.data_root=/home/kamimura/projects/tennis-lab/data paths.cache_root=/home/kamimura/projects/tennis-lab/data paths.checkpoint_root=/home/kamimura/projects/tennis-lab/ckpt paths.output_root=/home/kamimura/projects/tennis-lab/outputs run.output_dir=ball_refiner/train/detector_only/i935-ft-e13-s42-r4-20260928
