#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i991-rope-2d-gan-only-eventonly-s42-20261006-v4
# provider=codex session=01a10697-63da-75b2-ae84-f2980da51c23 issue=991 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/coordinate-refiner-gan-only}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: b415d791c7275ba871bb2c2cdc541090cfacec12 (branch codex/coordinate-refiner-gan-only)"
git checkout b415d791c7275ba871bb2c2cdc541090cfacec12 2>/dev/null || echo "[repro] WARN: checkout b415d791c7275ba871bb2c2cdc541090cfacec12 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 .venv/bin/python -m src.tasks.ball_refiner.scripts.train_coordinates training=coordinate_gan_only model.dimensions=2 run.output_dir=ball_refiner/train/rope-2d-gan-only-eventonly/20261006-v4-s42
