#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: mono3d_blcs_ftC_axis_s04g03
# provider=claude session=22fa49a8-b654-4af8-99ce-6f29e7453a00 issue=593
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/i593-axis-smoothness}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 93c5baceba9f1aa90e6f8dc303e86a01cafb76a4 (branch worktree-i593-axis-smoothness)"
git checkout 93c5baceba9f1aa90e6f8dc303e86a01cafb76a4 2>/dev/null || echo "[repro] WARN: checkout 93c5baceba9f1aa90e6f8dc303e86a01cafb76a4 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.blcs.scripts.train --config-name train_chunked data.scene_dir=/home/kamimura/projects/tennis-lab/data/blcs_broadcast data.chunk.chunks_dir=/home/kamimura/projects/tennis-lab/data/blcs_broadcast/chunks data.num_views_range=[1,1] data.camera_mode=random data.num_court_kp=14 data.num_workers=2 data.chunk.generation_workers=8 data.chunk.epochs_per_chunk=20 camera=broadcast training.position_axis_weights=[1.0,4.0,1.0] training.learning_rate=3e-5 training.trainer.max_epochs=60 training.trainer.check_val_every_n_epoch=5 training.qualitative_logging.enabled=false training.early_stopping.enabled=false training.smoothness_loss_weight=0.4 training.gravity_loss_weight=0.3 training.smoothness_axis_weights=[1,1,0] run.output_dir=/home/kamimura/projects/tennis-lab/outputs/blcs/blcs_multiview_axial run.init_weights=/home/kamimura/projects/tennis-lab/outputs/blcs/blcs_multiview_axial/logs/version_2/checkpoints/last.ckpt run.gpus=1
