#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i786-plcs-v2-resume-b24-r2
# provider=codex session=01a028df-6133-79c2-9266-f9b6a343765f issue=786
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-786-normalization-v2}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: b356bbeb6bedeb43d4dd07c0b574f4eddc8c4f8c (branch feat/issue-786-normalization-v2)"
git checkout b356bbeb6bedeb43d4dd07c0b574f4eddc8c4f8c 2>/dev/null || echo "[repro] WARN: checkout b356bbeb6bedeb43d4dd07c0b574f4eddc8c4f8c failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.plcs.scripts.train --config-name train_norm_v2 paths.data_root=/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-786-normalization-v2/data paths.external_asset_root=/home/kamimura/projects/tennis-lab/data run.output_dir=plcs/i786/norm-v2/multiview_axial_base run.gpus=1 data.batch_size=24 training.steps_per_epoch=200 run.resume=plcs/i786/norm-v2/multiview_axial_base/logs/version_0/checkpoints/last.ckpt
