#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i934-evidence-meiji-clip000-r4-20260928
# provider=codex session=01a0e57b-9d42-7a60-a1e4-8ab2461e46ea issue=934 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-3-evidence-contract}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 87de832cb049d5da36cd3df7a1549fa240199db8 (branch campaign930/i934-3-evidence-contract)"
git checkout 87de832cb049d5da36cd3df7a1549fa240199db8 2>/dev/null || echo "[repro] WARN: checkout 87de832cb049d5da36cd3df7a1549fa240199db8 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-3-evidence-contract /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-3-evidence-contract/.venv/bin/python /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i934-3-evidence-contract/tests/benchmarks/ball_detection_evidence.py --repo /home/kamimura/projects/tennis-lab --clip /home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_001/clips/clip_000 --report /home/kamimura/projects/tennis-lab/outputs/ball_detection/evaluate/i934-evidence-meiji-clip000-r4-20260928 --device cuda
