#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i620_convnext_webmix_ft_r2
# provider= session= issue=
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab-ball-webmix}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 72230f2db31f9f6a99cfe6d2bdc24824d3f4d57e (branch feat/issue-620-web-mix-datamodule)"
git checkout 72230f2db31f9f6a99cfe6d2bdc24824d3f4d57e 2>/dev/null || echo "[repro] WARN: checkout 72230f2db31f9f6a99cfe6d2bdc24824d3f4d57e failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True ./.venv/bin/python -m src.tasks.ball_detection.scripts.train_staged model=conv_next_unet data.t_max=8 data.t_distribution=fixed data.val_num_frames=8 data.heatmap_size='[72,128]' data.num_workers=2 data.sources.tracknet.enabled=true data.sources.tracknet.sample_stride=4 data.sources.web.enabled=true 'data.sources.web.splits=[train]' 'data.sources.web.sources=[ball_yolo,kaggle_backview]' data.sources.web.sampling.mode=temporal data.sources.web.sampling.temporal.frame_step=1 data.sources.web.sampling.temporal.sample_stride=2 data.sources.web.sampling.temporal.max_frame_gap=1 training.learning_rate=5e-5 training.trainer.max_epochs=16 training.checkpoint.monitor=val/f1 training.checkpoint.mode=max training.early_stopping.enabled=true training.early_stopping.monitor=val/f1 training.early_stopping.mode=max training.early_stopping.patience=6 training.early_stopping.min_delta=0.0005 'run.init_weights="/home/kamimura/projects/tennis-lab/outputs/ball_detection/convnext_v2_scratch/logs/version_0/checkpoints/ball-detection-epoch=25.ckpt"' run.output_dir=/home/kamimura/projects/tennis-lab/outputs/ball_detection/convnext_mdd_webmix_ft
