#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-meiji-rgb-features-v2
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=half logical_slot=0
set -uo pipefail
export TENNIS_GPU_RESOURCE=half
export TENNIS_GPU_SLOT=0
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4348077d8f7a0b35ab58350232cf4ccb607990f1 (branch codex/slcs-real-rgb)"
git checkout 4348077d8f7a0b35ab58350232cf4ccb607990f1 2>/dev/null || echo "[repro] WARN: checkout 4348077d8f7a0b35ab58350232cf4ccb607990f1 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=3 MKL_NUM_THREADS=3 .venv/bin/python -m src.tennis_scene.scripts.build_slcs_dataset stage=features output_dir=tennis_scene/precompute/meiji_rgb_features/s42-gpu-002 paths.external_asset_root=/home/kamimura/projects/tennis-lab/third_party
