#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: player-pose-v2-pilot-00034-20261002
# provider=codex session=01a0f53f-bff2-7202-b7ee-5fa777ae6627 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-mix-v2-player-pose}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 47bd048c54183a186b37e7d49102467c2ac10587 (branch codex/ball-mix-v2-player-pose)"
git checkout 47bd048c54183a186b37e7d49102467c2ac10587 2>/dev/null || echo "[repro] WARN: checkout 47bd048c54183a186b37e7d49102467c2ac10587 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=/home/kamimura/projects/tennis-lab/outputs/ball_refiner/generate/context/i935-context-fullframe-pilot-r10-20260928/dino_extension/lib:/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-mix-v2-player-pose OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2 MKL_NUM_THREADS=2 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.claude/worktrees/ball-mix-v2-player-pose/.venv/bin/python -u -m src.tennis_scene.chat_annotation.player_pose generate-clip --campaign /home/kamimura/projects/tennis-lab/outputs/chat_annotation/player_pose/ball-mix-v2-20261002 --index 34
