#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: court-align-aug-r2-weak-warm-v2
# provider=codex session=01a05a02-ad55-76c0-9fcb-f250929e59a7 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/court-alignment-kp14}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 5de3a7d45e037a799d4dad0ae1ef3ac3cb24897e (branch feat/court-alignment-kp14-pipeline)"
git checkout 5de3a7d45e037a799d4dad0ae1ef3ac3cb24897e 2>/dev/null || echo "[repro] WARN: checkout 5de3a7d45e037a799d4dad0ae1ef3ac3cb24897e failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True HYDRA_FULL_ERROR=1 /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.court_alignment.scripts.train data=b00_weak_structure_v2 paths.checkpoint_root=/home/kamimura/projects/tennis-lab/.claude/worktrees/court-alignment-kp14/outputs data.train_samples=2048 data.val_samples=256 data.test_samples=256 data.batch_size=16 training.steps_per_epoch=128 training.trainer.max_epochs=30 training.learning_rate=3.0e-4 training.warmup_steps=128 run.seed=42 run.init_weights=court_alignment/ablation_sigma_200/logs/version_0/checkpoints/court-alignment-epoch\\=047.ckpt run.output_dir=court_alignment/augmentation_round2/b00_weak_warm30_lr3e4_s42
