#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i964-coco-fullframe-r5-20260929
# provider=codex session=01a0ed37-597b-7d63-92ea-34732ac91701 issue=964 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-2-tracking}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: cdedbc183d35cb3e2c89814bf5fe70dcddc2ec31 (branch campaign930/i964-2-tracking)"
git checkout cdedbc183d35cb3e2c89814bf5fe70dcddc2ec31 2>/dev/null || echo "[repro] WARN: checkout cdedbc183d35cb3e2c89814bf5fe70dcddc2ec31 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --signal=TERM --kill-after=15s 5385s bash /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i964-2-tracking/tests/benchmarks/person_coco_fullframe.sh /home/kamimura/projects/tennis-lab /home/kamimura/projects/tennis-lab/outputs/player_detection/evaluate/pipeline_switch/i964-detectors-r1-20260929/meiji/comparison.json /home/kamimura/projects/tennis-lab/outputs/player_detection/evaluate/coco_fullframe/i964-r5-20260929
