#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i935-context-fullframe-pilot-r9-20260928
# provider=codex session=01a0e82d-a490-71b3-b824-86a92b90919a issue=935 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: f65c91f5c8a1a0e60025237ef424fc90afd7bcfa (branch campaign930/i935-8-context-cache)"
git checkout f65c91f5c8a1a0e60025237ef424fc90afd7bcfa 2>/dev/null || echo "[repro] WARN: checkout f65c91f5c8a1a0e60025237ef424fc90afd7bcfa failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
timeout --signal=TERM --kill-after=15s 18m bash -c 'cp /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache/outputs/campaign_930/i935/run9/scene-context.yaml /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache/outputs/campaign_930/i935/run9/preflight-final.json /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache/outputs/campaign_930/i935/run9/jpeg-preflight.json /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache/outputs/campaign_930/i935/run9/pilot-selection.json "$TENNIS_REPRO_DIR/" && env PYTHONPATH=/home/kamimura/projects/tennis-lab/build/lib.linux-x86_64-cpython-311 OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2 /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache/.venv/bin/python -m src.tasks.ball_refiner.scripts.generate_context --store /home/kamimura/projects/tennis-lab/data/ball_detection/ball-mix-v1 --evidence /home/kamimura/projects/tennis-lab/data/ball_refiner/detector-ft-e13-trainval-r3-20260928 --output /home/kamimura/projects/tennis-lab/data/ball_refiner/context-fullframe-pilot-r9-20260928 --max-tracks 64 --clip-id tracknet/game5/Clip14 --clip-id meiji/video_002/clip_011/cam0 --clip-id chat_annotation/-6UwVW0DeO4__f056b9d6649bee3a__f000000496-000000821 --scene-config "$TENNIS_REPRO_DIR/scene-context.yaml" && env OMP_NUM_THREADS=2 /home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i935-8-context-cache/.venv/bin/python -c '"'"'import json, os
from pathlib import Path
from src.tasks.ball_detection.data.store import BallFrameStore
from src.tasks.ball_refiner.data.evidence_cache import EvidenceCache
from src.tasks.ball_refiner.data.context_cache import ContextCache
from src.utils.checksum import dual_sha256
root = Path('"'"'"'"'"'"'"'"'/home/kamimura/projects/tennis-lab'"'"'"'"'"'"'"'"')
repro = Path(os.environ['"'"'"'"'"'"'"'"'TENNIS_REPRO_DIR'"'"'"'"'"'"'"'"'])
store = BallFrameStore(root / '"'"'"'"'"'"'"'"'data/ball_detection/ball-mix-v1'"'"'"'"'"'"'"'"')
evidence = EvidenceCache(root / '"'"'"'"'"'"'"'"'data/ball_refiner/detector-ft-e13-trainval-r3-20260928'"'"'"'"'"'"'"'"', store)
directory = root / '"'"'"'"'"'"'"'"'data/ball_refiner/context-fullframe-pilot-r9-20260928'"'"'"'"'"'"'"'"'
cache = ContextCache(directory, evidence)
selected = tuple(json.loads((repro / '"'"'"'"'"'"'"'"'pilot-selection.json'"'"'"'"'"'"'"'"').read_text()))
cache.require_clips(selected)
assert set(cache.clip_ids) == set(selected)
rows = []
for clip_id in cache.clip_ids:
    generated = cache.load(clip_id)
    clip = store.clip_by_id(clip_id)
    pose, court = generated.arrays.model_context(clip, pose_threshold=.15, provenance={}).require_complete()
    rows.append({'"'"'"'"'"'"'"'"'clip_id'"'"'"'"'"'"'"'"': clip_id, '"'"'"'"'"'"'"'"'frames'"'"'"'"'"'"'"'"': clip.frame_count, '"'"'"'"'"'"'"'"'tracks'"'"'"'"'"'"'"'"': len(generated.arrays.track_ids),
                 '"'"'"'"'"'"'"'"'pose_valid_frames'"'"'"'"'"'"'"'"': int(pose.valid.any(axis=(1, 2)).sum()), '"'"'"'"'"'"'"'"'pose_valid_slots'"'"'"'"'"'"'"'"': int(pose.valid.sum()),
                 '"'"'"'"'"'"'"'"'court_valid_points'"'"'"'"'"'"'"'"': int(court.valid.sum()), '"'"'"'"'"'"'"'"'execution'"'"'"'"'"'"'"'"': generated.execution})
result = {'"'"'"'"'"'"'"'"'status'"'"'"'"'"'"'"'"': '"'"'"'"'"'"'"'"'verified_load_in_separate_process'"'"'"'"'"'"'"'"', '"'"'"'"'"'"'"'"'context_manifest_sha256'"'"'"'"'"'"'"'"': dual_sha256(directory / '"'"'"'"'"'"'"'"'manifest.json'"'"'"'"'"'"'"'"'),
          '"'"'"'"'"'"'"'"'pose_threshold'"'"'"'"'"'"'"'"': .15, '"'"'"'"'"'"'"'"'clips'"'"'"'"'"'"'"'"': rows}
(repro / '"'"'"'"'"'"'"'"'context-verification.json'"'"'"'"'"'"'"'"').write_text(json.dumps(result, ensure_ascii=False, indent=2) + '"'"'"'"'"'"'"'"'
'"'"'"'"'"'"'"'"')
print(json.dumps(result, ensure_ascii=False))
'"'"''
