#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: issue-753-track-query-baseline-matched-v4
# provider=codex session=01a02003-4b40-79c3-abbf-24c54b29c0dc issue=753
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 296310e8e6749079bbbe60ac68329b8adb31b22a (branch feat/blcs-track-query-cswa)"
git checkout 296310e8e6749079bbbe60ac68329b8adb31b22a 2>/dev/null || echo "[repro] WARN: checkout 296310e8e6749079bbbe60ac68329b8adb31b22a failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
.venv/bin/python -m experiments.blcs.issue_753.scripts.train
