"""Canonical typed model-I/O API for Court detection."""

from src.tasks.court_detection.model_io.adapters import (
    CourtDINOv3ExecutionBoundary,
    CourtModelExecutionBoundary,
    CourtModelIOAdapter,
    CourtPoseModelIOAdapter,
)
from src.tasks.court_detection.model_io.contracts import (
    CourtConsistencyResult,
    CourtDecodedOutput,
    CourtDecodedPrediction,
    CourtKeypointPrediction,
    CourtLinePrediction,
    CourtLogits,
    CourtModelCall,
    CourtModelIOError,
    CourtModelOutput,
    CourtModelSpec,
    CourtPoseLossKind,
    CourtPosePrediction,
    CourtPoseTargetBatch,
    CourtPoseTrainingResult,
    CourtRawOutput,
    CourtRawPoseOutput,
    CourtSegmentationPrediction,
    CourtTrainingCall,
    CourtTrainingResult,
)

__all__ = [
    "CourtDINOv3ExecutionBoundary",
    "CourtDecodedPrediction",
    "CourtDecodedOutput",
    "CourtConsistencyResult",
    "CourtKeypointPrediction",
    "CourtLinePrediction",
    "CourtLogits",
    "CourtModelCall",
    "CourtModelExecutionBoundary",
    "CourtModelIOAdapter",
    "CourtModelIOError",
    "CourtModelSpec",
    "CourtModelOutput",
    "CourtPoseModelIOAdapter",
    "CourtPoseTrainingResult",
    "CourtPosePrediction",
    "CourtPoseLossKind",
    "CourtPoseTargetBatch",
    "CourtRawPoseOutput",
    "CourtRawOutput",
    "CourtSegmentationPrediction",
    "CourtTrainingCall",
    "CourtTrainingResult",
]
