"""Canonical typed model-I/O API for Court detection."""

from src.tasks.court_detection.model_io.adapters import (
    CourtDINOv3ExecutionBoundary,
    CourtModelExecutionBoundary,
    CourtModelIOAdapter,
    CourtQueryDINOv3ExecutionBoundary,
    CourtQueryModelExecutionBoundary,
    CourtQueryModelIOAdapter,
)
from src.tasks.court_detection.model_io.contracts import (
    CourtDecodedPrediction,
    CourtKeypointPrediction,
    CourtLinePrediction,
    CourtLogits,
    CourtModelCall,
    CourtModelIOError,
    CourtModelSpec,
    CourtQueryDecodedOutput,
    CourtQueryModelCall,
    CourtQueryModelSpec,
    CourtQueryPrediction,
    CourtQueryRawOutput,
    CourtQueryTrainingCall,
    CourtQueryTrainingResult,
    CourtSegmentationPrediction,
    CourtTrainingCall,
    CourtTrainingResult,
)

__all__ = [
    "CourtDINOv3ExecutionBoundary",
    "CourtDecodedPrediction",
    "CourtKeypointPrediction",
    "CourtLinePrediction",
    "CourtLogits",
    "CourtModelCall",
    "CourtModelExecutionBoundary",
    "CourtModelIOAdapter",
    "CourtModelIOError",
    "CourtModelSpec",
    "CourtQueryDINOv3ExecutionBoundary",
    "CourtQueryDecodedOutput",
    "CourtQueryModelCall",
    "CourtQueryModelExecutionBoundary",
    "CourtQueryModelIOAdapter",
    "CourtQueryModelSpec",
    "CourtQueryRawOutput",
    "CourtQueryPrediction",
    "CourtQueryTrainingCall",
    "CourtQueryTrainingResult",
    "CourtSegmentationPrediction",
    "CourtTrainingCall",
    "CourtTrainingResult",
]
