#!/usr/bin/env bash
set -euo pipefail

# Run B01-B03 through NHT reconstruction and court alignment on one Colab GPU.
#
# The script mounts Google Drive, installs the locked repository and NHT
# runtimes, verifies every Drive input by SHA-256, stages inputs onto the Colab
# VM, and pipelines the three scenes. Each reconstruction trains on GPU while
# the preceding scene shares that GPU for line inference and performs geometric
# alignment on CPU. Canonical pipeline publication stays
# on the VM because Google Drive FUSE does not provide the filesystem semantics
# required by atomic stage replacement. Each completed reconstruction and
# alignment is copied to a unique Drive result directory before the next scene.
#
# Usage from a Colab checkout:
#   !bash scripts/colab/train/20260829T150257Z/run_b01_b03_alignment.sh
#
# Validate the command and asset contract without mounting Drive or using GPU:
#   !bash scripts/colab/train/20260829T150257Z/run_b01_b03_alignment.sh --dry-run
#
# Environment overrides:
#   REPO_ROOT       repository root inferred from this script by default
#   DRIVE_ROOT      /content/drive/MyDrive/tennis_lab by default
#   RESULT_RUN_ROOT unique Drive output directory generated by default

usage() {
    echo "Usage: bash scripts/colab/train/20260829T150257Z/run_b01_b03_alignment.sh [--dry-run]" >&2
}

DRY_RUN=0
case "${1-}" in
    "")
        ;;
    --dry-run)
        DRY_RUN=1
        shift
        ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        usage
        exit 2
        ;;
esac
if [[ "$#" -ne 0 ]]; then
    usage
    exit 2
fi

REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)}"
DRIVE_MOUNT_POINT="${DRIVE_MOUNT_POINT:-/content/drive}"
DRIVE_ROOT="${DRIVE_ROOT:-${DRIVE_MOUNT_POINT}/MyDrive/tennis_lab}"
DRIVE_DATA_ROOT="${DRIVE_ROOT}/data"
DRIVE_CHECKPOINT_ROOT="${DRIVE_ROOT}/ckpt"
REVISION="$(git -C "${REPO_ROOT}" rev-parse --short=12 HEAD 2>/dev/null || true)"
if [[ -z "${REVISION}" ]]; then
    REVISION="unknown-revision"
fi
RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)-${REVISION}"
RESULT_RUN_ROOT="${RESULT_RUN_ROOT:-${DRIVE_ROOT}/outputs/synthetic_data_generation/alignment-runs/${RUN_ID}}"

DINOV3_NAME="dinov3_vitb16_pretrain_lvd1689m-73cec8be.pth"
LINE_CHECKPOINT_NAME="court-detection-epoch19.ckpt"
DINOV3_SHA256="73cec8be7427c8655ceced13ce62f6e20a1fa90d1b4d4a550df17a1144081a7c"
LINE_CHECKPOINT_SHA256="81914bc58ba08824061b4509f54fcb2637a99b5c505cd5c28780cd4c1e88bfd4"
SCENES=(B01 B02 B03)
declare -A VIDEO_SHA256=(
    [B01]="c9608e911f86274a862a289927ff9d0cc587543f836ffbdcad127f8ce61b5d56"
    [B02]="035a3e79637583d0794e598808fcdd46aac9d3f8e374599f453718a3d6c8615a"
    [B03]="80ec1676b420b05f22fc9c4ed5db9257e1c35b9e9bb9596dd1be3f479c7287ac"
)
declare -A EXPECTED_COURT_COUNT=(
    [B01]="3"
)

log() {
    echo "[run_b01_b03_alignment] $*"
}

fail() {
    echo "[run_b01_b03_alignment] $*" >&2
    exit 1
}

require_repository() {
    [[ -f "${REPO_ROOT}/pyproject.toml" ]] \
        || fail "REPO_ROOT is not a tennis-lab checkout: ${REPO_ROOT}"
    [[ -f "${REPO_ROOT}/src/synthetic_data_generation/configs/run_scene_pipeline.yaml" ]] \
        || fail "canonical scene-pipeline config is missing from ${REPO_ROOT}"
}

print_dry_run() {
    log "dry-run repository=${REPO_ROOT}"
    log "dry-run drive_root=${DRIVE_ROOT}"
    log "dry-run result_run_root=${RESULT_RUN_ROOT}"
    log "dry-run setup=mount-drive,verify-gpu,init-dinov3,verify-inputs,system-deps,uv-sync,setup-nht"
    log "dry-run asset=${DRIVE_DATA_ROOT}/${DINOV3_NAME} sha256=${DINOV3_SHA256}"
    log "dry-run asset=${DRIVE_CHECKPOINT_ROOT}/court_detection/line/${LINE_CHECKPOINT_NAME} sha256=${LINE_CHECKPOINT_SHA256}"
    local scene profile
    for scene in "${SCENES[@]}"; do
        profile="${scene,,}"
        log "dry-run asset=${DRIVE_DATA_ROOT}/synthetic_data_generation/raw/${scene}.mp4 sha256=${VIDEO_SHA256[${scene}]}"
        log "dry-run scene=${scene} gpu-command=.venv/bin/python -m src.synthetic_data_generation.scripts.run_scene_pipeline profile=${profile} request.from_stage=ingest request.through_stage=reconstruction"
        log "dry-run scene=${scene} shared-gpu-command=TENNIS_LAB_ALIGNMENT_INFERENCE_MIRROR_ROOT=<run>/${scene}/court-line-inference TENNIS_LAB_ALIGNMENT_HOLDOUT_CAMERA_PREFIX_COUNT=72 .venv/bin/python -m src.synthetic_data_generation.scripts.run_scene_pipeline profile=${profile} request.from_stage=alignment request.through_stage=alignment"
        log "dry-run scene=${scene} save-after=reconstruction,alignment"
        log "dry-run scene=${scene} verify=alignment,line-heatmaps,no-datasets,no-report"
    done
}

mount_drive() {
    if [[ -d "${DRIVE_ROOT}" ]]; then
        log "Google Drive is already mounted: ${DRIVE_ROOT}"
        return
    fi
    command -v python3 >/dev/null 2>&1 \
        || fail "python3 is required to mount Google Drive"
    log "mounting Google Drive at ${DRIVE_MOUNT_POINT}..."
    if ! python3 - "${DRIVE_MOUNT_POINT}" <<'PY'
import sys

from google.colab import drive

drive.mount(sys.argv[1], force_remount=False)
PY
    then
        fail "Google Drive mount failed; run this script inside a Colab runtime"
    fi
    [[ -d "${DRIVE_ROOT}" ]] \
        || fail "Drive mounted without the expected tennis_lab directory: ${DRIVE_ROOT}"
}

verify_gpu() {
    command -v nvidia-smi >/dev/null 2>&1 \
        || fail "nvidia-smi is unavailable; select a Colab GPU runtime"
    nvidia-smi -L
}

install_system_dependencies() {
    local apt_command=(apt-get)
    if [[ "${EUID}" -ne 0 ]]; then
        command -v sudo >/dev/null 2>&1 \
            || fail "root or sudo is required to install Colab system dependencies"
        apt_command=(sudo apt-get)
    fi
    log "installing system dependencies..."
    "${apt_command[@]}" update
    DEBIAN_FRONTEND=noninteractive "${apt_command[@]}" install -y \
        build-essential \
        cmake \
        ffmpeg \
        ninja-build
}

install_python_and_nht() {
    if ! command -v uv >/dev/null 2>&1; then
        log "installing uv..."
        python3 -m pip install uv
    fi
    log "synchronizing the locked tennis-lab environment..."
    (
        cd "${REPO_ROOT}"
        uv sync --locked
    )
    local uv_tool_bin
    uv_tool_bin="$(uv tool dir --bin)"
    [[ -n "${uv_tool_bin}" ]] || fail "uv did not resolve its tool bin directory"
    export PATH="${uv_tool_bin}:${PATH}"
    local trainer_python="${REPO_ROOT}/third_party/nht/.trainer-venv/bin/python"
    if command -v nht-reconstruct >/dev/null 2>&1 \
        && command -v nht-render >/dev/null 2>&1 \
        && [[ -x "${trainer_python}" ]] \
        && "$(command -v nht-reconstruct | xargs dirname)/../share/uv/tools/nht/bin/python" -c 'import hloc' >/dev/null 2>&1 \
        && "${trainer_python}" -c 'from gsplat.nht.deferred_shader import DeferredShaderModule' >/dev/null 2>&1; then
        log "reusing the verified NHT public CLI and trainer runtime"
    else
        log "installing the pinned NHT public CLI and trainer runtime..."
        (
            cd "${REPO_ROOT}"
            .venv/bin/python -m spin setup-nht --with-sfm-learned
        )
    fi
    (
        cd "${REPO_ROOT}"
        .venv/bin/python - <<'PY'
import torch

if not torch.cuda.is_available():
    raise RuntimeError("The locked tennis-lab environment cannot access a CUDA GPU.")
print(f"CUDA ready: {torch.cuda.get_device_name(0)}")
PY
    )
}

initialize_dinov3() {
    log "initializing the pinned DINOv3 submodule..."
    git -C "${REPO_ROOT}" submodule update \
        --init \
        --recursive \
        --checkout \
        third_party/dinov3
    [[ -d "${REPO_ROOT}/third_party/dinov3/dinov3" ]] \
        || fail "DINOv3 submodule did not publish its Python package"
}

sha256_of() {
    sha256sum "$1" | awk '{print $1}'
}

stage_verified_file() {
    local source="$1"
    local destination="$2"
    local expected="$3"
    [[ -f "${source}" ]] || fail "required Drive input is missing: ${source}"

    local source_hash
    source_hash="$(sha256_of "${source}")"
    [[ "${source_hash}" == "${expected}" ]] \
        || fail "Drive input SHA-256 mismatch: ${source} (expected ${expected}, got ${source_hash})"

    if [[ -f "${destination}" && "$(sha256_of "${destination}")" == "${expected}" ]]; then
        log "verified staged input: ${destination}"
        return
    fi

    mkdir -p "$(dirname "${destination}")"
    local staging="${destination}.staging.$$"
    rm -f "${staging}"
    cp "${source}" "${staging}"
    local staged_hash
    staged_hash="$(sha256_of "${staging}")"
    if [[ "${staged_hash}" != "${expected}" ]]; then
        rm -f "${staging}"
        fail "staged input SHA-256 mismatch: ${destination}"
    fi
    mv -f "${staging}" "${destination}"
    log "staged verified input: ${destination}"
}

stage_inputs() {
    stage_verified_file \
        "${DRIVE_DATA_ROOT}/${DINOV3_NAME}" \
        "${REPO_ROOT}/third_party/dinov3/checkpoints/${DINOV3_NAME}" \
        "${DINOV3_SHA256}"
    stage_verified_file \
        "${DRIVE_CHECKPOINT_ROOT}/court_detection/line/${LINE_CHECKPOINT_NAME}" \
        "${REPO_ROOT}/ckpt/court_detection/line/${LINE_CHECKPOINT_NAME}" \
        "${LINE_CHECKPOINT_SHA256}"

    local scene
    for scene in "${SCENES[@]}"; do
        stage_verified_file \
            "${DRIVE_DATA_ROOT}/synthetic_data_generation/raw/${scene}.mp4" \
            "${REPO_ROOT}/data/synthetic_data_generation/raw/${scene}.mp4" \
            "${VIDEO_SHA256[${scene}]}"
    done
}

validate_scene_output() {
    local scene="$1"
    local scene_root="${REPO_ROOT}/data/synthetic_data_generation/scenes/${scene}"
    (
        cd "${REPO_ROOT}"
        .venv/bin/python - "${scene_root}" "${scene}" "${EXPECTED_COURT_COUNT[${scene}]-}" <<'PY'
import json
import sys
from pathlib import Path

from src.synthetic_data_generation.alignment.heatmaps import validate_line_heatmaps

scene_root = Path(sys.argv[1])
scene_id = sys.argv[2]
expected_court_count = int(sys.argv[3]) if sys.argv[3] else None
run_manifest = json.loads((scene_root / "run.json").read_text(encoding="utf-8"))
if run_manifest["scene_id"] != scene_id:
    raise RuntimeError("run.json scene_id disagrees with the requested scene")
for stage in ("ingest", "reconstruction", "alignment"):
    status = run_manifest["stages"][stage]["status"]
    if status != "completed":
        raise RuntimeError(f"{scene_id} stage {stage} is {status}, not completed")
for stage in ("court_dataset", "blcs_dataset", "plcs_dataset", "report"):
    status = run_manifest["stages"][stage]["status"]
    if status in {"running", "completed"}:
        raise RuntimeError(f"unexpected terminal-stage status for {stage}: {status}")
for forbidden in (scene_root / "datasets", scene_root / "report"):
    if forbidden.exists() or forbidden.is_symlink():
        raise RuntimeError(f"alignment-only run published forbidden output: {forbidden}")

alignment = scene_root / "alignment"
for required in ("alignment.json", "court-geometry.json", "ground-line-map.npz"):
    if not (alignment / required).is_file():
        raise RuntimeError(f"alignment output is missing: {required}")
alignment_result = json.loads((alignment / "alignment.json").read_text())
accepted_court_count = len(alignment_result["layout"]["courts"])
if (
    expected_court_count is not None
    and accepted_court_count != expected_court_count
):
    raise RuntimeError(
        f"{scene_id} accepted {accepted_court_count} courts; "
        f"expected {expected_court_count}"
    )
heatmaps = validate_line_heatmaps(alignment / "line-heatmaps")
print(
    f"validated {scene_id}: {len(heatmaps.views)} raw heatmaps, "
    f"{len(heatmaps.views)} weighted heatmaps, one weighted projection, "
    f"{accepted_court_count} accepted courts"
)
PY
    )
}

persist_reconstruction_output() {
    local scene="$1"
    local scene_root="${REPO_ROOT}/data/synthetic_data_generation/scenes/${scene}"
    local destination="${RESULT_RUN_ROOT}/${scene}"
    local staging="${destination}.reconstruction-uploading"
    [[ ! -e "${destination}" && ! -L "${destination}" ]] \
        || fail "Drive result destination already exists: ${destination}"
    [[ ! -e "${staging}" && ! -L "${staging}" ]] \
        || fail "Drive reconstruction staging destination already exists: ${staging}"
    mkdir -p "${staging}/source"
    cp "${scene_root}/run.json" "${staging}/run.json"
    cp "${scene_root}/resolved-config.yaml" "${staging}/resolved-config.yaml"
    cp "${scene_root}/source/metadata.json" "${staging}/source/metadata.json"
    cp -RL "${scene_root}/reconstruction" "${staging}/reconstruction"
    mv "${staging}" "${destination}"
    log "saved ${scene} completed reconstruction to ${destination}"
}

persist_alignment_output() {
    local scene="$1"
    local scene_root="${REPO_ROOT}/data/synthetic_data_generation/scenes/${scene}"
    local destination="${RESULT_RUN_ROOT}/${scene}"
    local staging="${destination}/alignment.uploading"
    local archive="${destination}/alignment-attempts/$(date -u +%Y%m%dT%H%M%SZ)-superseded-output"
    [[ -d "${destination}/reconstruction" ]] \
        || fail "Drive reconstruction checkpoint is missing: ${destination}"
    [[ ! -e "${staging}" && ! -L "${staging}" ]] \
        || fail "Drive alignment staging destination already exists: ${staging}"
    cp -RL "${scene_root}/alignment" "${staging}"
    if [[ -e "${destination}/alignment" || -L "${destination}/alignment" ]]; then
        [[ ! -e "${archive}" && ! -L "${archive}" ]] \
            || fail "Drive alignment archive destination already exists: ${archive}"
        mkdir -p "$(dirname "${archive}")"
        mv "${destination}/alignment" "${archive}"
        log "archived prior ${scene} alignment to ${archive}"
    fi
    mv "${staging}" "${destination}/alignment"
    cp "${scene_root}/run.json" "${destination}/run.json"
    cp "${scene_root}/resolved-config.yaml" "${destination}/resolved-config.yaml"
    log "saved ${scene} reconstruction and alignment to ${destination}"
}

run_reconstruction() {
    local scene="$1"
    local profile="${scene,,}"
    local scene_manifest="${REPO_ROOT}/data/synthetic_data_generation/scenes/${scene}/run.json"
    if [[ -f "${scene_manifest}" ]] && .venv/bin/python - "${scene_manifest}" <<'PY'
import json
import sys

manifest = json.load(open(sys.argv[1], encoding="utf-8"))
raise SystemExit(0 if manifest["stages"]["reconstruction"]["status"] == "completed" else 1)
PY
    then
        log "reusing completed ${scene} GPU reconstruction"
        return
    fi
    log "starting ${scene} GPU work: ingest -> reconstruction"
    (
        cd "${REPO_ROOT}"
        MPLBACKEND="${MPLBACKEND:-Agg}" \
        PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}" \
        .venv/bin/python -m src.synthetic_data_generation.scripts.run_scene_pipeline \
            "profile=${profile}" \
            request.from_stage=ingest \
            request.through_stage=reconstruction
    )
}

run_alignment() {
    local scene="$1"
    local profile="${scene,,}"
    local scene_root="${REPO_ROOT}/data/synthetic_data_generation/scenes/${scene}"
    local destination="${RESULT_RUN_ROOT}/${scene}"
    local attempt_id
    local attempt_log
    local drive_attempt_log
    local status
    attempt_id="$(date -u +%Y%m%dT%H%M%SZ)-$$"
    attempt_log="${scene_root}/alignment-attempts/${attempt_id}.log"
    drive_attempt_log="${destination}/alignment-attempts/${attempt_id}.log"
    mkdir -p "$(dirname "${attempt_log}")" "$(dirname "${drive_attempt_log}")"
    log "starting ${scene} shared-GPU line inference and CPU geometric alignment"
    set +e
    (
        cd "${REPO_ROOT}"
        MPLBACKEND="${MPLBACKEND:-Agg}" \
        PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}" \
        TENNIS_LAB_ALIGNMENT_INFERENCE_MIRROR_ROOT="${destination}/court-line-inference" \
        TENNIS_LAB_ALIGNMENT_HOLDOUT_CAMERA_PREFIX_COUNT=72 \
        .venv/bin/python -m src.synthetic_data_generation.scripts.run_scene_pipeline \
            "profile=${profile}" \
            request.from_stage=alignment \
            request.through_stage=alignment
    ) 2>&1 | tee "${attempt_log}"
    status="${PIPESTATUS[0]}"
    set -e
    cp "${attempt_log}" "${drive_attempt_log}.uploading"
    mv "${drive_attempt_log}.uploading" "${drive_attempt_log}"
    if [[ "${status}" -ne 0 ]]; then
        log "${scene} alignment attempt failed; diagnostics saved to ${drive_attempt_log}"
        return "${status}"
    fi
    validate_scene_output "${scene}"
    persist_alignment_output "${scene}"
}

require_repository
if [[ "${DRY_RUN}" -eq 1 ]]; then
    print_dry_run
    exit 0
fi

mount_drive
verify_gpu
initialize_dinov3
stage_inputs
install_system_dependencies
install_python_and_nht
mkdir -p "${RESULT_RUN_ROOT}"

log "Drive result root: ${RESULT_RUN_ROOT}"
alignment_pid=""
alignment_scene=""
for scene in "${SCENES[@]}"; do
    run_reconstruction "${scene}"
    persist_reconstruction_output "${scene}"
    if [[ -n "${alignment_pid}" ]]; then
        log "waiting for ${alignment_scene} shared-GPU/CPU alignment after ${scene} GPU reconstruction"
        wait "${alignment_pid}"
        log "completed ${alignment_scene} CPU alignment"
    fi
    run_alignment "${scene}" &
    alignment_pid="$!"
    alignment_scene="${scene}"
    log "overlap enabled: ${scene} shared-GPU/CPU alignment pid=${alignment_pid}; next GPU reconstruction may start"
done
[[ -n "${alignment_pid}" ]] || fail "no alignment process was started"
wait "${alignment_pid}"
log "completed ${alignment_scene} CPU alignment"
log "all B01-B03 alignment runs completed: ${RESULT_RUN_ROOT}"
