#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-meiji-checkpoint-hash-probe-v1
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 88dca25f954178bb3668768c8418332bd0a98749 (branch codex/slcs-real-rgb)"
git checkout 88dca25f954178bb3668768c8418332bd0a98749 2>/dev/null || echo "[repro] WARN: checkout 88dca25f954178bb3668768c8418332bd0a98749 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=. CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 MKL_NUM_THREADS=4 .venv/bin/python knowledge/runs/run-slcs-meiji-checkpoint-hash-probe-v1/probe.py
