#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i801_attempt2_plcs_d_reference_t128_v6_eb32_e100_final
# provider=codex session=01a03207-0be4-72c1-ba60-a051d0d8d9b6 issue=801
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-801-reference-rope}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 71426cb84519d4fa716ac9b221d90b00d26b4e63 (branch feat/issue-801-reference-camera-rope)"
git checkout 71426cb84519d4fa716ac9b221d90b00d26b4e63 2>/dev/null || echo "[repro] WARN: checkout 71426cb84519d4fa716ac9b221d90b00d26b4e63 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.plcs.scripts.train --config-name train_tracking court_coordinate_normalization=v2 court_keypoints=camera_view_v2 model.cswa.backend=cuda paths.data_root=/home/kamimura/projects/tennis-lab/data data.scene_dir=plcs/multi_object_camera_view_norm-v2 data.seq_len_range=[128,128] data.num_views_range=[6,6] data.batch_size=8 data.num_workers=16 data.evaluation_reference_camera_id=camera_2 training.compile.enabled=false training.trainer.precision=bf16-mixed training.trainer.accumulate_grad_batches=4 training.trainer.max_epochs=100 training.trainer.check_val_every_n_epoch=5 training.trainer.enable_progress_bar=false training.trainer.enable_model_summary=false training.early_stopping.enabled=false training.qualitative_logging.enabled=false run.seed=42 run.fast_dev_run=false run.test_after_fit=true model=track_query_ablation_d_v2_selector run.output_dir=plcs/norm-v2/issue-801/t128-v6/ablation-d-reference-selector-eb32-final
