#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: plcs-web-inference
# provider=codex session=01a09e9c-5c30-7bf3-8e7b-9d2f9d6d3bd8 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/dataset-scene-review}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 782fc137d85c054d0f5ef775fe5edbf8cf52f00f (branch codex/dataset-scene-review)"
git checkout 782fc137d85c054d0f5ef775fe5edbf8cf52f00f 2>/dev/null || echo "[repro] WARN: checkout 782fc137d85c054d0f5ef775fe5edbf8cf52f00f failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
/home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.base.visualization.inference_queue /home/kamimura/projects/tennis-lab/.training_queue/ui_requests/plcs-73lm5pmb/request.json
