#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1031-court-ckpt-qualitative-20261008b
# provider=codex session=01a113c9-1114-71a2-9261-80815f662d33 issue=1031 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-1031-qualitative-schedule}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 1dcf9407897cefc38842fe02e57e6895c008e6f6 (branch fix/issue-1031-qualitative-schedule)"
git checkout 1dcf9407897cefc38842fe02e57e6895c008e6f6 2>/dev/null || echo "[repro] WARN: checkout 1dcf9407897cefc38842fe02e57e6895c008e6f6 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env MPLBACKEND=Agg OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m scripts.verify_qualitative_checkpoints --task court_detection --asset-root /home/kamimura/projects/tennis-lab --checkpoint /home/kamimura/projects/tennis-lab/ckpt/court_detection/multiscale_depth3/b863df1f01f0.ckpt --output-dir /home/kamimura/projects/tennis-lab/outputs/court_detection/evaluate/issue-1031-qualitative/20261008b --sample-indices 0 935
