#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: plcs_foot_residual_hard_ft20
# provider=codex session=01a09b38-6993-7e23-9122-9482895fe0b4 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-foot-residual}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: b8ccc6bac5beac082b97e94c8b42edd9da8d2f40 (branch experiments/plcs-foot-residual)"
git checkout b8ccc6bac5beac082b97e94c8b42edd9da8d2f40 2>/dev/null || echo "[repro] WARN: checkout b8ccc6bac5beac082b97e94c8b42edd9da8d2f40 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
OMP_NUM_THREADS=4 PYTHONPATH=. .venv/bin/python -m src.tasks.plcs.scripts.train --config-path /home/kamimura/projects/tennis-lab/.claude/worktrees/plcs-foot-residual/outputs/plcs/foot_residual --config-name train
