name: court_fpn
in_channels: 3
num_classes: 7
encoder_name: default
# DINO encoder examples:
# encoder_name: resnet
# encoder_name: resnet50
# encoder_name: swin
# encoder_name: swin_L_384_22k
encoder_checkpoint_path: null
encoder_dilation: false
return_interm_indices: [0, 1, 2, 3]
encoder_pretrain_img_size: null
encoder_use_checkpoint: false
encoder_strict: true
freeze_encoder: false
decoder_channels: [64, 128, 256, 512]