#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: slcs-meiji-v8-feature-reuse-v1
# provider=codex session=01a0b314-89b5-7902-b0a1-3141a9323ea9 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/slcs-real-rgb}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 10a8a73edf38348eb6322b901d05329b6b2c7f5d (branch codex/slcs-real-rgb)"
git checkout 10a8a73edf38348eb6322b901d05329b6b2c7f5d 2>/dev/null || echo "[repro] WARN: checkout 10a8a73edf38348eb6322b901d05329b6b2c7f5d failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
if [ ! -f /home/kamimura/projects/tennis-lab/.training_queue/done/1789739458621952459_956621_slcs-meiji-v8-observe-v1.job ]; then echo 'Required observation job did not complete' >&2; exit 1; fi; env CUDA_VISIBLE_DEVICES= OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 .venv/bin/python -B knowledge/runs/run-slcs-meiji-v8-feature-reuse-v1/reuse_features.py --output-dir outputs/tennis_scene/analyze/meiji_v8_feature_reuse/s42-001
