#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i719-plcs-kp14
# provider=codex session=019ff6e5-b975-7671-bdd4-f03843734cf5 issue=719
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-719-courtkp7-reference}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 64c2da16e029acd2202c3b592e31eb9952c916d7 (branch feat/issue-719-courtkp7-reference)"
git checkout 64c2da16e029acd2202c3b592e31eb9952c916d7 2>/dev/null || echo "[repro] WARN: checkout 64c2da16e029acd2202c3b592e31eb9952c916d7 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=. PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train --config-name train_tracking model=track_query_kp14 data.scene_dir=issue719/plcs data.seq_len_range='[64,64]' data.num_views_range='[3,5]' data.batch_size=8 data.num_workers=4 training.trainer.max_epochs=3 training.trainer.check_val_every_n_epoch=1 training.warmup_steps=0 training.early_stopping.enabled=false training.qualitative_logging.enabled=false run.seed=719 run.output_dir=issue719/i719-plcs-kp14 run.test_after_fit=true
