#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i786-blcs-norm-v2-b64-w16
# provider=codex session=01a028df-6133-79c2-9266-f9b6a343765f issue=786
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-786-normalization-v2}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 7aff92cb59eb6c4abfa844fcf19a9452ee7e8000 (branch feat/issue-786-normalization-v2)"
git checkout 7aff92cb59eb6c4abfa844fcf19a9452ee7e8000 2>/dev/null || echo "[repro] WARN: checkout 7aff92cb59eb6c4abfa844fcf19a9452ee7e8000 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.blcs.scripts.train --config-name train_normalization_v2 paths.data_root=/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-786-normalization-v2/data run.output_dir=blcs/i786/norm-v2/multiview_axial_base run.gpus=1 data.batch_size=64 data.num_workers=16
