defaults:
  - train
  - _self_

evaluation:
  checkpoint_path: null

training:
  checkpoint:
    enabled: false
  early_stopping:
    enabled: false
  lr_monitor:
    enabled: false
  qualitative_logging:
    enabled: false

run:
  output_dir: court_alignment/evaluate_sigma_${data.sigma_px}
  gpus: 0
  test_after_fit: true
