#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: plcs-residual-v2-asinh-legacy-s42
# provider=codex session=01a0bf91-5494-74c0-8793-3424866618ed issue= resource=half logical_slot=0
set -uo pipefail
export TENNIS_GPU_RESOURCE=half
export TENNIS_GPU_SLOT=0
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/residual-v2-conditioning}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 771649c98814914f4a9164cf4ca6df44aabc9041 (branch codex/residual-v2-conditioning)"
git checkout 771649c98814914f4a9164cf4ca6df44aabc9041 2>/dev/null || echo "[repro] WARN: checkout 771649c98814914f4a9164cf4ca6df44aabc9041 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 PYTHONFAULTHANDLER=1 OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=2 .venv/bin/python -m src.tasks.plcs.scripts.train_triangulation_residual --config-name train_triangulation_residual_v2 paths.data_root=/home/kamimura/projects/tennis-lab/data paths.output_root=/home/kamimura/projects/tennis-lab/outputs run.output_dir=plcs/triangulation_residual_v2_asinh_legacy_s42_20260921 run.seed=42 v2.loss_mode=legacy features.residual_encoding=asinh features.residual_scale=0.01 training.trainer.enable_progress_bar=false && CUDA_VISIBLE_DEVICES=0 PYTHONFAULTHANDLER=1 OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=2 .venv/bin/python -m src.tasks.base.scripts.infer_triangulation_residual --task plcs --run-dir /home/kamimura/projects/tennis-lab/outputs/plcs/triangulation_residual_v2_asinh_legacy_s42_20260921 --clip /home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_000 --output '/mnt/c/Users/kamim/.codex/visualizations/2026/09/20/01a0bf91-5494-74c0-8793-3424866618ed/geometric-residual-v2/plcs/asinh' --device cuda
