"""Fixed-width manifold-constrained hyper-connections.

The component reads a fixed set of residual streams into one stream and writes a
residual-free sublayer update back to the set.  Coefficients are generated by
shared stream and pair functions, so reordering streams only reorders the
corresponding coefficient axes.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from numbers import Real

import torch
import torch.nn.functional as F
from torch import Tensor, nn


@dataclass(frozen=True, slots=True)
class MHCConfig:
    """Configuration for :class:`ManifoldConstrainedHyperConnection`.

    Args:
        dim: Feature dimension of every residual stream.
        num_streams: Fixed residual-stream width.
        coefficient_dim: Hidden width of the shared coefficient generator.
        sinkhorn_iters: Number of alternating row/column normalizations.
        eps: Positive numerical epsilon used by RMS normalization and division.
        residual_identity_bias: Non-negative diagonal residual-logit bias for
            the Sinkhorn-projected residual target.
        update_scale_init: Initial value of the learned update scale.
    """

    dim: int
    num_streams: int
    coefficient_dim: int
    sinkhorn_iters: int
    eps: float
    residual_identity_bias: float
    update_scale_init: float = 0.0

    def __post_init__(self) -> None:
        for name in ("dim", "num_streams", "coefficient_dim", "sinkhorn_iters"):
            value = getattr(self, name)
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                raise ValueError(f"{name} must be a positive integer, got {value!r}")

        _validate_finite_real("eps", self.eps, positive=True)
        _validate_finite_real(
            "residual_identity_bias",
            self.residual_identity_bias,
            non_negative=True,
        )
        _validate_finite_real("update_scale_init", self.update_scale_init)


@dataclass(slots=True)
class MHCState:
    """Tensor-only state passed from :meth:`pre` to :meth:`post`.

    Attributes:
        residual_mix: Doubly-stochastic residual map with shape ``[..., P, P]``.
        post_weights: Per-stream write weights with shape ``[..., P, 1]``.
        valid_mask: Boolean stream-validity mask with shape ``[..., P]``.
    """

    residual_mix: Tensor
    post_weights: Tensor
    valid_mask: Tensor


def _validate_finite_real(
    name: str,
    value: object,
    *,
    positive: bool = False,
    non_negative: bool = False,
) -> None:
    if isinstance(value, bool) or not isinstance(value, Real):
        raise ValueError(f"{name} must be a finite real number, got {value!r}")
    numeric_value = float(value)
    if not math.isfinite(numeric_value):
        raise ValueError(f"{name} must be finite, got {value!r}")
    if positive and numeric_value <= 0.0:
        raise ValueError(f"{name} must be positive, got {value!r}")
    if non_negative and numeric_value < 0.0:
        raise ValueError(f"{name} must be non-negative, got {value!r}")


class ManifoldConstrainedHyperConnection(nn.Module):
    """Read from and write to a fixed-width set of residual streams.

    ``pre`` accepts streams of shape ``[..., P, D]`` and a same-leading-shape
    boolean mask ``[..., P]``.  It returns one projected stream ``[..., 1, D]``
    plus an :class:`MHCState`.  After a caller computes a *residual-free* update
    with shape ``[..., 1, D]``, ``post`` combines it with the original residual
    streams and returns ``[..., P, D]``.

    Coefficient generation and masked log-Sinkhorn run in at least float32.
    Float64 is retained for double-precision numerical checks.  Returned maps
    and values use the stream input dtype.
    """

    _SUPPORTED_DTYPES = {
        torch.float16,
        torch.bfloat16,
        torch.float32,
        torch.float64,
    }

    def __init__(self, config: MHCConfig) -> None:
        super().__init__()
        if not isinstance(config, MHCConfig):
            raise TypeError(f"config must be MHCConfig, got {type(config).__name__}")

        self.config = config
        self.dim = config.dim
        self.num_streams = config.num_streams
        self.coefficient_dim = config.coefficient_dim
        self.sinkhorn_iters = config.sinkhorn_iters
        self.eps = float(config.eps)
        self.residual_identity_bias = float(config.residual_identity_bias)

        self.stream_in = nn.Linear(self.dim, self.coefficient_dim)
        self.stream_out = nn.Linear(self.coefficient_dim, self.coefficient_dim)

        combined_dim = 2 * self.coefficient_dim
        self.pre_head = nn.Linear(combined_dim, 1)
        self.post_head = nn.Linear(combined_dim, 1)

        self.residual_query = nn.Linear(
            self.coefficient_dim,
            self.coefficient_dim,
            bias=False,
        )
        self.residual_key = nn.Linear(
            self.coefficient_dim,
            self.coefficient_dim,
            bias=False,
        )
        self.pair_in = nn.Linear(3 * self.coefficient_dim, self.coefficient_dim)
        self.pair_out = nn.Linear(self.coefficient_dim, 1)

        self.update_scale = nn.Parameter(
            torch.tensor(float(config.update_scale_init), dtype=torch.float32)
        )
        self.residual_mix_gate = nn.Parameter(torch.tensor(0.0, dtype=torch.float32))
        self._identity: Tensor
        self.register_buffer(
            "_identity",
            torch.eye(self.num_streams, dtype=torch.float32),
            persistent=False,
        )
        self._reset_identity_preserving_parameters()

    def _reset_identity_preserving_parameters(self) -> None:
        """Zero dynamic residual logits while keeping every branch trainable."""
        nn.init.zeros_(self.pre_head.weight)
        nn.init.zeros_(self.pre_head.bias)
        nn.init.zeros_(self.post_head.weight)
        nn.init.zeros_(self.post_head.bias)

        # With a non-zero query projection and a zero key projection, the
        # bilinear residual logits start at zero but the key branch immediately
        # receives gradients.  Zeroing both projections would make it stationary.
        nn.init.xavier_uniform_(self.residual_query.weight)
        nn.init.zeros_(self.residual_key.weight)
        nn.init.zeros_(self.pair_out.weight)
        nn.init.zeros_(self.pair_out.bias)

    def _bounded_residual_mix_gate(self, dtype: torch.dtype) -> Tensor:
        """Return the exact-zero, convex residual-map interpolation gate.

        Clamping at the initialized lower boundary has unit derivative in
        PyTorch, so the gate can leave zero while its effective value remains
        in ``[0, 1]`` for every optimizer or loaded state.
        """
        return self.residual_mix_gate.to(dtype=dtype).clamp(0.0, 1.0)

    @staticmethod
    def _coefficient_dtype(dtype: torch.dtype) -> torch.dtype:
        return torch.float64 if dtype == torch.float64 else torch.float32

    @staticmethod
    def _linear(x: Tensor, layer: nn.Linear, dtype: torch.dtype) -> Tensor:
        bias = None if layer.bias is None else layer.bias.to(dtype=dtype)
        return F.linear(x, layer.weight.to(dtype=dtype), bias)

    def _module_device(self) -> torch.device:
        device = self.update_scale.device
        if any(parameter.device != device for parameter in self.parameters()):
            raise RuntimeError("all mHC parameters must be on the same device")
        if self._identity.device != device:
            raise RuntimeError(
                "all mHC parameters and buffers must be on the same device"
            )
        return device

    def _validate_streams(self, streams: Tensor, valid_mask: Tensor) -> None:
        if streams.ndim < 2:
            raise ValueError(
                f"streams must have at least 2 dimensions, got {streams.ndim}"
            )
        expected_tail = (self.num_streams, self.dim)
        if streams.shape[-2:] != expected_tail:
            raise ValueError(
                "streams trailing shape must be "
                f"{expected_tail}, got {tuple(streams.shape[-2:])}"
            )
        if streams.dtype not in self._SUPPORTED_DTYPES:
            raise TypeError(
                "streams must use float16, bfloat16, float32, or float64, "
                f"got {streams.dtype}"
            )
        expected_mask_shape = streams.shape[:-1]
        if valid_mask.shape != expected_mask_shape:
            raise ValueError(
                f"valid_mask shape must be {tuple(expected_mask_shape)}, "
                f"got {tuple(valid_mask.shape)}"
            )
        if valid_mask.dtype != torch.bool:
            raise TypeError(f"valid_mask must have dtype bool, got {valid_mask.dtype}")
        if valid_mask.device != streams.device:
            raise ValueError(
                "streams and valid_mask must be on the same device, got "
                f"{streams.device} and {valid_mask.device}"
            )
        module_device = self._module_device()
        if streams.device != module_device:
            raise ValueError(
                f"streams must be on module device {module_device}, got {streams.device}"
            )

    def _stream_features(self, masked_streams: Tensor, mask: Tensor) -> Tensor:
        coefficient_dtype = self._coefficient_dtype(masked_streams.dtype)
        values = masked_streams.to(dtype=coefficient_dtype)
        rms = values.square().mean(dim=-1, keepdim=True)
        normalized = values * torch.rsqrt(rms + self.eps)
        features = F.silu(self._linear(normalized, self.stream_in, coefficient_dtype))
        features = self._linear(features, self.stream_out, coefficient_dtype)
        return features * mask.unsqueeze(-1).to(dtype=coefficient_dtype)

    def _masked_softmax(self, logits: Tensor, mask: Tensor) -> Tensor:
        fill_value = torch.finfo(logits.dtype).min
        masked_logits = logits.masked_fill(~mask, fill_value)
        maxima = masked_logits.amax(dim=-1, keepdim=True)
        numerator = torch.exp(masked_logits - maxima) * mask.to(dtype=logits.dtype)
        denominator = numerator.sum(dim=-1, keepdim=True)
        return numerator / denominator.clamp_min(self.eps)

    @staticmethod
    def _masked_logsumexp(values: Tensor, mask: Tensor, dim: int) -> Tensor:
        """Reduce valid entries without ever evaluating an all-``-inf`` row."""
        has_valid = mask.any(dim=dim, keepdim=True)
        masked = values.masked_fill(~mask, -torch.inf)
        safe = torch.where(has_valid, masked, torch.zeros_like(masked))
        reduced = torch.logsumexp(safe, dim=dim, keepdim=True)
        return torch.where(has_valid, reduced, torch.zeros_like(reduced))

    def _masked_sinkhorn(self, logits: Tensor, valid_mask: Tensor) -> Tensor:
        pair_mask = valid_mask.unsqueeze(-1) & valid_mask.unsqueeze(-2)
        log_mix = torch.where(pair_mask, logits, torch.zeros_like(logits))

        for _ in range(self.sinkhorn_iters):
            row_norm = self._masked_logsumexp(log_mix, pair_mask, dim=-1)
            log_mix = torch.where(pair_mask, log_mix - row_norm, 0.0)
            column_norm = self._masked_logsumexp(log_mix, pair_mask, dim=-2)
            log_mix = torch.where(pair_mask, log_mix - column_norm, 0.0)

        return torch.exp(log_mix) * pair_mask.to(dtype=log_mix.dtype)

    def _coefficient_maps(
        self,
        features: Tensor,
        valid_mask: Tensor,
    ) -> tuple[Tensor, Tensor, Tensor]:
        coefficient_dtype = features.dtype
        mask_values = valid_mask.unsqueeze(-1).to(dtype=coefficient_dtype)
        valid_count = mask_values.sum(dim=-2, keepdim=True).clamp_min(1.0)
        pooled = features.sum(dim=-2, keepdim=True) / valid_count
        pooled_per_stream = pooled.expand_as(features)
        per_stream = torch.cat((features, pooled_per_stream), dim=-1)

        pre_logits = self._linear(per_stream, self.pre_head, coefficient_dtype).squeeze(
            -1
        )
        post_logits = self._linear(
            per_stream, self.post_head, coefficient_dtype
        ).squeeze(-1)
        pre_weights = self._masked_softmax(pre_logits, valid_mask).unsqueeze(-2)
        post_weights = (
            2.0 * torch.sigmoid(post_logits) * valid_mask.to(coefficient_dtype)
        ).unsqueeze(-1)

        queries = self._linear(features, self.residual_query, coefficient_dtype)
        keys = self._linear(features, self.residual_key, coefficient_dtype)
        pair_logits = torch.matmul(queries, keys.transpose(-2, -1)) / math.sqrt(
            self.coefficient_dim
        )

        row_features = features.unsqueeze(-2).expand(
            *features.shape[:-2],
            self.num_streams,
            self.num_streams,
            self.coefficient_dim,
        )
        column_features = features.unsqueeze(-3).expand_as(row_features)
        pooled_pairs = pooled.unsqueeze(-2).expand_as(row_features)
        pair_features = torch.cat(
            (row_features, column_features, pooled_pairs),
            dim=-1,
        )
        pair_hidden = F.silu(
            self._linear(pair_features, self.pair_in, coefficient_dtype)
        )
        pair_logits = pair_logits + self._linear(
            pair_hidden, self.pair_out, coefficient_dtype
        ).squeeze(-1)

        pair_mask = valid_mask.unsqueeze(-1) & valid_mask.unsqueeze(-2)
        pair_values = pair_mask.to(dtype=coefficient_dtype)
        pair_count = pair_values.sum(dim=(-2, -1), keepdim=True).clamp_min(1.0)
        pair_mean = (pair_logits * pair_values).sum(
            dim=(-2, -1), keepdim=True
        ) / pair_count
        dynamic_logits = (pair_logits - pair_mean) * pair_values
        residual_logits = (
            dynamic_logits
            + self.residual_identity_bias * self._identity.to(dtype=coefficient_dtype)
        )
        sinkhorn_mix = self._masked_sinkhorn(residual_logits, valid_mask)
        identity_mix = (
            self._identity.to(dtype=coefficient_dtype)
            * valid_mask.unsqueeze(-1).to(dtype=coefficient_dtype)
        )
        mix_gate = self._bounded_residual_mix_gate(coefficient_dtype)
        residual_mix = identity_mix + mix_gate * (sinkhorn_mix - identity_mix)
        return pre_weights, residual_mix, post_weights

    def pre(
        self,
        streams: Tensor,
        valid_mask: Tensor,
    ) -> tuple[Tensor, MHCState]:
        """Project ``[..., P, D]`` streams into one mask-aware stream.

        All coefficient operations use shared functions and the valid-set mean.
        An all-invalid element explicitly returns zero projection and maps.
        """
        self._validate_streams(streams, valid_mask)
        with torch.autocast(device_type=streams.device.type, enabled=False):
            masked_streams = streams * valid_mask.unsqueeze(-1).to(dtype=streams.dtype)
            features = self._stream_features(masked_streams, valid_mask)
            pre_weights, residual_mix, post_weights = self._coefficient_maps(
                features, valid_mask
            )

            coefficient_dtype = features.dtype
            projected = torch.matmul(
                pre_weights,
                masked_streams.to(dtype=coefficient_dtype),
            ).to(dtype=streams.dtype)
        state = MHCState(
            residual_mix=residual_mix.to(dtype=streams.dtype),
            post_weights=post_weights.to(dtype=streams.dtype),
            valid_mask=valid_mask,
        )
        return projected, state

    def post(
        self,
        update: Tensor,
        residual: Tensor,
        state: MHCState,
    ) -> Tensor:
        """Write a residual-free ``[..., 1, D]`` update back to the streams."""
        if not isinstance(state, MHCState):
            raise TypeError(f"state must be MHCState, got {type(state).__name__}")
        self._validate_streams(residual, state.valid_mask)

        leading_shape = residual.shape[:-2]
        expected_update_shape = leading_shape + (1, self.dim)
        expected_mix_shape = leading_shape + (
            self.num_streams,
            self.num_streams,
        )
        expected_post_shape = leading_shape + (self.num_streams, 1)
        if update.shape != expected_update_shape:
            raise ValueError(
                f"update shape must be {tuple(expected_update_shape)}, "
                f"got {tuple(update.shape)}"
            )
        if state.residual_mix.shape != expected_mix_shape:
            raise ValueError(
                f"state.residual_mix shape must be {tuple(expected_mix_shape)}, "
                f"got {tuple(state.residual_mix.shape)}"
            )
        if state.post_weights.shape != expected_post_shape:
            raise ValueError(
                f"state.post_weights shape must be {tuple(expected_post_shape)}, "
                f"got {tuple(state.post_weights.shape)}"
            )

        tensors = {
            "update": update,
            "state.residual_mix": state.residual_mix,
            "state.post_weights": state.post_weights,
        }
        for name, tensor in tensors.items():
            if tensor.device != residual.device:
                raise ValueError(
                    f"{name} device must match residual device {residual.device}, "
                    f"got {tensor.device}"
                )
            if tensor.dtype != residual.dtype:
                raise TypeError(
                    f"{name} dtype must match residual dtype {residual.dtype}, "
                    f"got {tensor.dtype}"
                )

        with torch.autocast(device_type=residual.device.type, enabled=False):
            mask_values = state.valid_mask.unsqueeze(-1).to(dtype=residual.dtype)
            masked_residual = residual * mask_values
            residual_output = torch.matmul(state.residual_mix, masked_residual)
            update_output = state.post_weights * update
            output = (
                residual_output
                + self.update_scale.to(dtype=residual.dtype) * update_output
            )
            return output * mask_values
