#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: court_storage_ondemand_v5
# provider=codex session=01a0985c-eb87-7310-9657-5411e2818d4e issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/court-storage-ondemand}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 21199b3e29746c9d6360f287462f1ca400865690 (branch codex/court-storage-ondemand)"
git checkout 21199b3e29746c9d6360f287462f1ca400865690 2>/dev/null || echo "[repro] WARN: checkout 21199b3e29746c9d6360f287462f1ca400865690 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 .venv/bin/python scripts/experiments/benchmark_court_ondemand.py --repo /home/kamimura/projects/tennis-lab --nht-worker /home/kamimura/projects/tennis-lab/.claude/worktrees/nht-court-storage-ondemand/scripts/resident_render_worker.py --nht-python /home/kamimura/.local/share/uv/tools/nht/bin/python --output outputs/storage-ondemand/benchmark-v5 --steps 24 --geometry training
