#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i634_slcs_overfit_no_dino
# provider=codex session=019f55e6-8819-7e63-8481-72f9effc4079 issue=634
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 8ed508912eff3e6e9f532d60d8e2e4ee01e328b8 (branch feat/issue-634-slcs-overfit)"
git checkout 8ed508912eff3e6e9f532d60d8e2e4ee01e328b8 2>/dev/null || echo "[repro] WARN: checkout 8ed508912eff3e6e9f532d60d8e2e4ee01e328b8 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.slcs.scripts.train model=small data.dataset_root=data/tennis_multivew/processed/tennis_clip/dataset data.split_file=data/tennis_multivew/processed/tennis_clip/dataset/splits.json data.overfit=true data.require_dino=false data.batch_size=1 data.num_workers=2 run.output_dir=outputs/slcs/i634_overfit_no_dino training.trainer.max_epochs=100 training.trainer.check_val_every_n_epoch=10 training.trainer.log_every_n_steps=13 training.early_stopping.enabled=false training.learning_rate=3e-4 training.warmup_steps=20 training.checkpoint.save_top_k=1
