#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i832_blcs_legacy_slot_baseline_r4
# provider=codex session=01a04ddb-48b6-7342-96a7-be95090cc969 issue=832
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-832-legacy-baseline}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 01b6cb5f46bb6c7bdd7f4735007f84d93f1689de (branch experiments/issue-832-legacy-baseline-boundary)"
git checkout 01b6cb5f46bb6c7bdd7f4735007f84d93f1689de 2>/dev/null || echo "[repro] WARN: checkout 01b6cb5f46bb6c7bdd7f4735007f84d93f1689de failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
test "$PWD" = "/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-832-legacy-baseline" || { echo "wrong CWD: $PWD" >&2; exit 70; }; /home/kamimura/projects/tennis-lab/.venv/bin/python -m src.tasks.blcs.scripts.train --config-name train_tracking paths.data_root=/home/kamimura/projects/tennis-lab/data run.seed=832 run.output_dir=blcs/issue-832/legacy-slot-baseline-r4 data.augmentation.false_positive.enabled=false training.trainer.max_epochs=100 training.trainer.check_val_every_n_epoch=5 training.early_stopping.enabled=false training.qualitative_logging.enabled=false
