#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i1049-convnext-posttrain-s42-v1-20261010
# provider=codex session=01a0fb0c-97b5-7851-b805-25dae445a6a2 issue=1049 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/ball-cnn-campaign-blocking-20261010}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 8ac45d9f79bf4f6a7feb343d09428a07aa6e8847 (branch HEAD)"
git checkout 8ac45d9f79bf4f6a7feb343d09428a07aa6e8847 2>/dev/null || echo "[repro] WARN: checkout 8ac45d9f79bf4f6a7feb343d09428a07aa6e8847 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
env CUDA_LAUNCH_BLOCKING=1 CUDA_LOG_FILE=stderr OMP_NUM_THREADS=2 MKL_NUM_THREADS=2 TORCHINDUCTOR_COMPILE_THREADS=2 PYTHONUNBUFFERED=1 /home/kamimura/projects/tennis-lab/.claude/worktrees/ball-cnn-campaign-blocking-20261010/.venv/bin/python -m src.tasks.ball_detection.scripts.train_best_mdd_posttraining --manifest /home/kamimura/projects/tennis-lab/outputs/ball_detection/precompute/mdd_coordinates_36/20261008-fps124-v1/mdd_only_windows.json --pretraining-run /home/kamimura/projects/tennis-lab/outputs/ball_detection/train/mdd-cnn-comparison/convnext_v2-s42-v2-serial --augmentation-config /home/kamimura/projects/tennis-lab/.claude/worktrees/ball-cnn-campaign-blocking-20261010/src/tasks/ball_detection/configs/augmentation/mdd_posttraining.yaml --output /home/kamimura/projects/tennis-lab/outputs/ball_detection/train/mdd-query-posttraining/convnext-v2-s42-v1 --device cuda --precision bf16 --epochs 10 --freeze-epochs 1 --windows-per-epoch 6000 --learning-rate .0001 --encoder-lr-ratio .1 --warmup-updates 500 --seed 42 --batch-size 1 --jpeg-decoder nvjpeg --pin-memory --num-workers 8 --prefetch-factor 4 --cpu-threads 2 --compile-mode default --log-every 50 --preview-clips 3 --stress-evaluation
