#!/usr/bin/env python
"""Unified CLI for BLCS scene visualization and prediction.

This script provides two modes:
- visualize: Visualize ground truth BLCS scene data
- predict:   Run BLCS model predictions and visualize

The script operates on BLCS scene files generated by
:mod:`src.blcs.data.dataset_writer` (one scene per NPZ file).

Example:
    # Ground truth visualization
    python -m src.blcs.scripts.visualize visualize data/blcs/scenes/scene_000000.npz --view multi

    # Model prediction and visualization
    python -m src.blcs.scripts.visualize predict data/blcs/scenes/scene_000000.npz \
        --checkpoint outputs/blcs/checkpoints/last.ckpt --view animation

"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import TYPE_CHECKING

import matplotlib.pyplot as plt
import numpy as np
import torch

from src.blcs.data.dataset_writer import load_scene
from src.rendering import BLCSSceneRenderer

if TYPE_CHECKING:
    from typing import Any


# =============================================================================
# Common Utilities
# =============================================================================


def add_common_args(parser: argparse.ArgumentParser) -> None:
    """Add common arguments shared by all subcommands."""
    parser.add_argument(
        "scene_path",
        type=Path,
        help="Path to BLCS scene NPZ file",
    )
    parser.add_argument(
        "--frame",
        type=int,
        default=0,
        help="Frame index to visualize (for static views)",
    )
    parser.add_argument(
        "--view",
        type=str,
        choices=["3d", "2d", "camera", "multi", "animation"],
        default="multi",
        help="View type",
    )
    parser.add_argument(
        "--camera",
        type=int,
        default=0,
        help="Camera index for camera view and prediction",
    )
    parser.add_argument(
        "--animation-view",
        type=str,
        choices=["3d", "2d", "camera"],
        default="2d",
        help="View type for animation",
    )
    parser.add_argument(
        "--fps",
        type=float,
        default=None,
        help="FPS for animation (default: use scene FPS if available)",
    )
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
        help="Save figure/animation to file",
    )
    parser.add_argument(
        "--info",
        action="store_true",
        help="Print scene info and exit",
    )


def add_model_args(parser: argparse.ArgumentParser) -> None:
    """Add model-related arguments for predict subcommand."""
    parser.add_argument(
        "--checkpoint",
        type=str,
        required=True,
        help="Path to BLCS model checkpoint",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Device to run on",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Optional path to save raw prediction outputs (.pt or .json)",
    )


def validate_frame_and_camera(
    scene: dict[str, Any], args: argparse.Namespace
) -> int | None:
    """Validate frame and camera indices.

    Returns:
        None if validation passes, error code (int) otherwise.

    """
    num_frames = int(scene["ball_pos_world"].shape[0])
    if args.frame < 0 or args.frame >= num_frames:
        print(f"Error: Frame {args.frame} out of range (0-{num_frames - 1})")
        return 1

    num_cameras = int(scene["num_cameras"])
    if args.camera < 0 or args.camera >= num_cameras:
        print(f"Error: Camera {args.camera} out of range (0-{num_cameras - 1})")
        return 1

    return None


def render_scene(scene: dict[str, Any], args: argparse.Namespace) -> int:
    """Render scene based on view type.

    Returns:
        Exit code (0 for success).

    """
    renderer = BLCSSceneRenderer()

    if args.view == "animation":
        # Determine FPS
        meta = scene["meta"]
        fps = args.fps or float(meta.get("fps_out", 30.0))
        print(f"Creating animation ({args.animation_view} view)...")
        anim = renderer.create_animation(
            scene,
            view=args.animation_view,
            camera_idx=args.camera,
            fps=fps,
        )

        if anim is None:
            return 1

        if args.save:
            print(f"Saving animation to {args.save}...")
            anim.save(str(args.save), fps=fps)
            print("Done!")
        else:
            plt.show()

    elif args.view == "3d":
        print(f"Rendering 3D view (frame {args.frame})...")
        fig, ax = renderer.render_3d_view(scene, frame_idx=args.frame)

        if args.save:
            fig.savefig(str(args.save), dpi=150, bbox_inches="tight")
            print(f"Saved to {args.save}")
        else:
            plt.show()

    elif args.view == "2d":
        print(f"Rendering 2D top-down view (frame {args.frame})...")
        fig, ax = renderer.render_2d_topdown(scene, frame_idx=args.frame)

        if args.save:
            fig.savefig(str(args.save), dpi=150, bbox_inches="tight")
            print(f"Saved to {args.save}")
        else:
            plt.show()

    elif args.view == "camera":
        print(f"Rendering camera {args.camera} view (frame {args.frame})...")
        fig, ax = renderer.render_camera_view(
            scene, camera_idx=args.camera, frame_idx=args.frame
        )

        if args.save:
            fig.savefig(str(args.save), dpi=150, bbox_inches="tight")
            print(f"Saved to {args.save}")
        else:
            plt.show()

    elif args.view == "multi":
        print(f"Rendering multi-view (frame {args.frame})...")
        fig = renderer.render_multi_view(scene, frame_idx=args.frame)

        if args.save:
            fig.savefig(str(args.save), dpi=150, bbox_inches="tight")
            print(f"Saved to {args.save}")
        else:
            plt.show()

    return 0


# =============================================================================
# Subcommand: visualize (Ground Truth)
# =============================================================================


def main_visualize(args: argparse.Namespace) -> int:
    """Visualize ground truth BLCS scene data."""
    print(f"Loading scene from {args.scene_path}...")
    scene = load_scene(args.scene_path)

    renderer = BLCSSceneRenderer()

    if args.info:
        renderer.print_scene_info(scene)
        return 0

    err = validate_frame_and_camera(scene, args)
    if err is not None:
        return err

    return render_scene(scene, args)


# =============================================================================
# Subcommand: predict (Model)
# =============================================================================


def main_predict(args: argparse.Namespace) -> int:
    """Run BLCS model predictions and visualize.

    This command loads a BLCS scene, runs the model to predict the 3D
    ball trajectory from a chosen camera's 2D observations, and then
    visualizes the predicted trajectory using :class:`BLCSSceneRenderer`.

    """
    from src.blcs.inference.predictor import BLCSPredictor

    print(f"Loading checkpoint from {args.checkpoint}...")
    predictor = BLCSPredictor.load_from_checkpoint(
        checkpoint_path=args.checkpoint, device=args.device
    )

    print(f"Loading scene from {args.scene_path}...")
    scene = load_scene(args.scene_path)

    renderer = BLCSSceneRenderer()

    if args.info:
        renderer.print_scene_info(scene)
        return 0

    err = validate_frame_and_camera(scene, args)
    if err is not None:
        return err

    # Select camera
    cam = scene["cameras"][args.camera]
    ball_uv = cam["ball_uv"]  # (T, 2)
    ball_vis = cam["ball_visible"]  # (T,)
    court_kp = cam["court_kp_uv"]  # (20, 2)
    court_vis = cam["court_kp_visible"]  # (20,)

    # Convert to tensors
    ball_uv_t = torch.from_numpy(ball_uv).float()
    court_kp_t = torch.from_numpy(court_kp).float()
    ball_mask_t = torch.from_numpy(ball_vis.astype(np.float32))
    court_vis_t = torch.from_numpy(court_vis.astype(np.float32))

    # Run prediction
    print("Running BLCS prediction...")
    outputs = predictor.predict(
        ball_uv=ball_uv_t,
        court_kp=court_kp_t,
        ball_mask=ball_mask_t,
        court_vis=court_vis_t,
        denormalize=True,
    )

    # Optionally save raw outputs
    if args.output is not None:
        output_path = Path(args.output)
        if output_path.suffix == ".pt":
            torch.save(outputs, output_path)
        elif output_path.suffix == ".json":
            json_data = {k: v.squeeze(0).cpu().tolist() for k, v in outputs.items()}
            with open(output_path, "w", encoding="utf-8") as f:
                json.dump(json_data, f, indent=2, ensure_ascii=False)
        else:
            print(
                f"Warning: Unknown output format '{output_path.suffix}', "
                "only .pt and .json are supported. Skipping save."
            )
        print(f"Saved prediction outputs to {output_path}")

    # Build scene copy with predicted trajectory
    scene_pred = dict(scene)
    pred_pos = outputs["position"].squeeze(0).cpu().numpy()
    scene_pred["ball_pos_world"] = pred_pos

    return render_scene(scene_pred, args)


# =============================================================================
# Main Entry Point
# =============================================================================


def parse_args() -> argparse.Namespace:
    """Parse command line arguments with subcommands."""
    parser = argparse.ArgumentParser(
        description="BLCS scene visualization and prediction CLI",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    subparsers = parser.add_subparsers(dest="command", required=True, help="Commands")

    # Subcommand: visualize
    parser_vis = subparsers.add_parser(
        "visualize",
        help="Visualize ground truth BLCS scene data",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    add_common_args(parser_vis)

    # Subcommand: predict
    parser_pred = subparsers.add_parser(
        "predict",
        help="Run BLCS model predictions and visualize",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    add_common_args(parser_pred)
    add_model_args(parser_pred)

    return parser.parse_args()


def main() -> int:
    """Main entry point."""
    args = parse_args()

    if args.command == "visualize":
        return main_visualize(args)
    if args.command == "predict":
        return main_predict(args)

    print(f"Unknown command: {args.command}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
