#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: plcs-association-refactor-512-smoke
# provider=codex session=01a0c384-7833-7021-868a-22a9433bfc02 issue= resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/association-task-refactor}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 8a25c17bf9281f751bc6fd41b6b10af6fb40b23d (branch codex/association-task-refactor)"
git checkout 8a25c17bf9281f751bc6fd41b6b10af6fb40b23d 2>/dev/null || echo "[repro] WARN: checkout 8a25c17bf9281f751bc6fd41b6b10af6fb40b23d failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# #931: the original command ran /tmp/association_gpu_smoke.py; diagnostic.py in this bundle is its saved copy.
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 PYTHONPATH=. /home/kamimura/projects/tennis-lab/.venv/bin/python -u "$SCRIPT_DIR/diagnostic.py" plcs
