defaults:
  - paths: default
  - simulation: default
  - camera: default
  - motion_sources: default
  - run: generate_dataset
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
  job_logging: null
  hydra_logging: null

