defaults:
  - model: sequence
  - data: sequence
  - training: default
  - metrics: default
  - loss: sequence
  - run: train_sequence
  - _self_

hydra:
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false

