defaults:
  - model: multiview
  - data: multiview
  - training: default
  - metrics: default
  - loss: multiview_sequence
  - run: train_multiview
  - _self_

hydra:
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
