defaults:
  - model: frame_kp3d
  - data: frame
  - training: default
  - loss: frame_kp3d
  - metrics: default
  - run: train_kp3d
  - _self_

hydra:
  run:
    dir: ${run.output_dir}/${now:%Y-%m-%d_%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
