defaults:
  - model: multiview
  - data: multiview
  - training: default
  - metrics: default
  - loss: multiview_sequence
  - run: train
  - _self_

hydra:
  run:
    dir: outputs/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
  job:
    chdir: false
