#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i545_s4_h4_wide
# provider=claude session=fabaa2ad-e86a-4a2b-b14b-6ce71d148c0a issue=545
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/wt/i545-prune}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 674818c567169bd3bee4bab17dd417a7308fdcc6 (branch feat/training-queue-auto-prune-ckpt)"
git checkout 674818c567169bd3bee4bab17dd417a7308fdcc6 2>/dev/null || echo "[repro] WARN: checkout 674818c567169bd3bee4bab17dd417a7308fdcc6 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
MPLBACKEND=Agg PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_split model.hidden_dim=768 model.num_heads=12 model.num_layers=4 model.num_task_layers=4 data.batch_size=2 training.trainer.accumulate_grad_batches=4 data=chunked_multiview_sequence_bs8 data.seq_len_range=[64,256] loss=canonical_rot training.trainer.max_epochs=200 training.early_stopping.enabled=false run.gpus=1
