#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: scene-component-meiji-tracklets-20260925
# provider=codex session=01a0d81f-1a8d-7462-b0f8-d827f54c6a4a issue=915 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/clip-component-store}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 4211b108ae8e337bc7ecd3fa545117f07a17c0bd (branch codex/clip-component-store)"
git checkout 4211b108ae8e337bc7ecd3fa545117f07a17c0bd 2>/dev/null || echo "[repro] WARN: checkout 4211b108ae8e337bc7ecd3fa545117f07a17c0bd failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# #931: the original PYTHONPATH used a DINO extension built outside the repository; it is rebuilt from
# this checkout by the bundle's build_dino_extension.sh (copy of tests/benchmarks/build_dino_extension.sh).
DINO_EXTENSION="$(mktemp -d)/dino_extension"
bash "$SCRIPT_DIR/build_dino_extension.sh" "${TENNIS_ASSET_ROOT:-/home/kamimura/projects/tennis-lab}" "$DINO_EXTENSION" || { echo "[repro] DINO extension build failed" >&2; exit 1; }
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=4 PYTHONPATH=.:$DINO_EXTENSION/lib .venv/bin/python tests/benchmarks/component_pipeline.py --repo /home/kamimura/projects/tennis-lab --clip /home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_000 --report /home/kamimura/projects/tennis-lab/outputs/tennis_scene/evaluate/clip_components_meiji_tracklets_20260925 --device cuda
