#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i933-association-meiji-clip000-20260927
# provider=claude session=abf284fe-984d-4b6c-afec-7375982b0bb0 issue=933 resource=all logical_slot=all
set -uo pipefail
export TENNIS_GPU_RESOURCE=all
export TENNIS_GPU_SLOT=all
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/c930-i933-player-association}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: ed12854b89fd8896552bd1577098f6361a835128 (branch campaign930/i933-4-pipeline)"
git checkout ed12854b89fd8896552bd1577098f6361a835128 2>/dev/null || echo "[repro] WARN: checkout ed12854b89fd8896552bd1577098f6361a835128 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# #933: the original command built the DINO extension into the report directory under outputs/
# and read the labels through the worktree's absolute path; the repro.sh builds the extension into
# a temporary directory with the same script (as #931/#932 did) and reads the same labels from the
# checked-out commit.
DINO_EXTENSION="$(mktemp -d)/dino_extension"
bash tests/benchmarks/build_dino_extension.sh "${TENNIS_ASSET_ROOT:-/home/kamimura/projects/tennis-lab}" "$DINO_EXTENSION" || { echo "[repro] DINO extension build failed" >&2; exit 1; }
# --- original training command ---
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=4 PYTHONPATH=.:$DINO_EXTENSION/lib .venv/bin/python tests/benchmarks/component_pipeline.py --repo /home/kamimura/projects/tennis-lab --clip /home/kamimura/projects/tennis-lab/data/tennis_multivew/processed/meiji_3cam/dataset/videos/video_000/clips/clip_000 --report /home/kamimura/projects/tennis-lab/outputs/tennis_scene/evaluate/i933-association-meiji-clip000-20260927 --association-labels tests/benchmarks/labels/player_association/meiji_3cam/video_000/clip_000.json --device cuda
