#!/usr/bin/env bash
# Auto-generated by training_queue.sh — reproduce run: i647_plcs_line_small_100ep
# provider=codex session=019f6013-0a29-7183-87ae-e4c221387139 issue=647
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="${TENNIS_REPO:-/home/kamimura/projects/tennis-lab/.claude/worktrees/issue-647-court-line-token}"
cd "$REPO" || { echo "[repro] cannot cd to $REPO" >&2; exit 1; }
echo "[repro] target commit: 6fe0a82cf1c67dc9b0c6e5b7599e92f75ad39292 (branch feat/issue-647-court-line-token)"
git checkout 6fe0a82cf1c67dc9b0c6e5b7599e92f75ad39292 2>/dev/null || echo "[repro] WARN: checkout 6fe0a82cf1c67dc9b0c6e5b7599e92f75ad39292 failed; using current HEAD"
PATCH="$SCRIPT_DIR/uncommitted.patch"
if [ -s "$PATCH" ]; then git apply "$PATCH" 2>/dev/null || echo "[repro] WARN: patch did not apply cleanly"; fi
# --- original training command ---
PYTHONPATH=. PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True .venv/bin/python -m src.tasks.plcs.scripts.train model=multiview_axial_line_small data=chunked_multiview_sequence_line_bs8 data.scene_dir=data/plcs_broadcast data.chunk.chunks_dir=data/plcs_broadcast/chunks camera=broadcast data.batch_size=8 data.num_workers=4 data.num_views_range=[1,1] data.seq_len_range=[64,256] data.chunk.generation_workers=6 data.chunk.epochs_per_chunk=30 loss=canonical_rot loss.position_weight=8.0 loss.canonical_pose_weight=0.0 loss.joint_angle_weight=0.0 loss.torsion_angle_weight=0.0 loss.torso_twist_weight=0.0 loss.bone_length_weight=0.0 training.trainer.max_epochs=100 training.trainer.check_val_every_n_epoch=5 training.qualitative_logging.enabled=false training.early_stopping.enabled=false run.output_dir=outputs/plcs/issue647_line_small_100ep run.gpus=1
